#########################################################################
# Title:            Sandbox: Stash                                      #
# Author(s):        -SK, kowalski                                       #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

stash_name: stash

################################
# Paths
################################

stash_paths_folder: "{{ stash_name }}"
stash_paths_location: "{{ server_appdata_path }}/{{ stash_paths_folder }}"
stash_paths_folders_list:
  - "{{ stash_paths_location }}"
  - "{{ stash_paths_location }}/config"
  - "{{ stash_paths_location }}/metadata"
  - "{{ stash_paths_location }}/cache"
  - "{{ stash_paths_location }}/generated"
  - "/mnt/unionfs/Media/Adult"

################################
# Web
################################

stash_web_subdomain: "{{ stash_name }}"
stash_web_domain: "{{ user.domain }}"
stash_web_port: "9999"
stash_web_url: "{{ 'https://' + stash_web_subdomain + '.' + stash_web_domain }}"

################################
# DNS
################################

stash_dns_record: "{{ stash_web_subdomain }}"
stash_dns_zone: "{{ stash_web_domain }}"
stash_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

stash_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
stash_traefik_middleware_default: "{{ traefik_default_middleware + ','
                                      + lookup('vars', stash_name + '_traefik_sso_middleware', default=stash_traefik_sso_middleware)
                                   if (lookup('vars', stash_name + '_traefik_sso_middleware', default=stash_traefik_sso_middleware) | length > 0)
                                   else traefik_default_middleware }}"
stash_traefik_middleware_custom: ""
stash_traefik_middleware: "{{ stash_traefik_middleware_default + ','
                              + stash_traefik_middleware_custom
                           if (not stash_traefik_middleware_custom.startswith(',') and stash_traefik_middleware_custom | length > 0)
                           else stash_traefik_middleware_default
                              + stash_traefik_middleware_custom }}"
stash_traefik_certresolver: "{{ traefik_default_certresolver }}"
stash_traefik_enabled: true
stash_traefik_api_enabled: false
stash_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
stash_docker_container: "{{ stash_name }}"

# Image
stash_docker_image_pull: true
stash_docker_image_tag: "latest"
stash_docker_image: "cr.hotio.dev/hotio/stash:{{ stash_docker_image_tag }}"

# Ports
stash_docker_ports_defaults: []
stash_docker_ports_custom: []
stash_docker_ports: "{{ stash_docker_ports_defaults
                        + stash_docker_ports_custom }}"

# Envs
stash_docker_envs_default:
  - TZ: "{{ tz }}"
  - PUID: "{{ uid }}"
  - PGID: "{{ gid }}"
stash_docker_envs_custom: {}
stash_docker_envs: "{{ stash_docker_envs_default
                       | combine(stash_docker_envs_custom) }}"

# Commands
stash_docker_commands_default: []
stash_docker_commands_custom: []
stash_docker_commands: "{{ stash_docker_commands_default
                           + stash_docker_commands_custom }}"

# Volumes
stash_docker_volumes_default:
  - "{{ stash_paths_location }}/config:/config"
  - "{{ stash_paths_location }}/metadata:/metadata"
  - "{{ stash_paths_location }}/cache:/cache"
  - "{{ stash_paths_location }}/generated:/generated"
  - "/mnt/unionfs/Media/Adult:/data"
stash_docker_volumes_custom: []
stash_docker_volumes: "{{ stash_docker_volumes_default
                          + stash_docker_volumes_custom }}"

# Devices
stash_docker_devices_default: []
stash_docker_devices_custom: []
stash_docker_devices: "{{ stash_docker_devices_default
                          + stash_docker_devices_custom }}"

# Hosts
stash_docker_hosts_default: []
stash_docker_hosts_custom: []
stash_docker_hosts: "{{ docker_hosts_common
                        | combine(stash_docker_hosts_default)
                        | combine(stash_docker_hosts_custom) }}"

# Labels
stash_docker_labels_default: {}
stash_docker_labels_custom: {}
stash_docker_labels: "{{ docker_labels_common
                         | combine(stash_docker_labels_default)
                         | combine(stash_docker_labels_custom) }}"

# Hostname
stash_docker_hostname: "{{ stash_name }}"

# Networks
stash_docker_networks_alias: "{{ stash_name }}"
stash_docker_networks_default: []
stash_docker_networks_custom: []
stash_docker_networks: "{{ docker_networks_common
                           + stash_docker_networks_default
                           + stash_docker_networks_custom }}"

# Capabilities
stash_docker_capabilities_default: []
stash_docker_capabilities_custom: []
stash_docker_capabilities: "{{ stash_docker_capabilities_default
                               + stash_docker_capabilities_custom }}"

# Security Opts
stash_docker_security_opts_default: []
stash_docker_security_opts_custom: []
stash_docker_security_opts: "{{ stash_docker_security_opts_default
                                + stash_docker_security_opts_custom }}"

# Restart Policy
stash_docker_restart_policy: unless-stopped

# State
stash_docker_state: started
