##########################################################################
# Title:         Sandbox: Yacht | Default Variables                      #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Docker Socket Proxy
################################

yacht_role_docker_socket_proxy_envs:
  CONTAINERS: "1"
  POST: "0"
  IMAGES: "1"
  VOLUMES: "1"
  NETWORKS: "1"

################################
# Basics
################################

yacht_name: yacht

################################
# Paths
################################

yacht_role_paths_folder: "{{ yacht_name }}"
yacht_role_paths_location: "{{ server_appdata_path }}/{{ yacht_role_paths_folder }}"
yacht_role_paths_folders_list:
  - "{{ yacht_role_paths_location }}"
  - "{{ yacht_role_paths_location }}/config"
  - "{{ yacht_role_paths_location }}/storage"

################################
# Web
################################

yacht_role_web_subdomain: "{{ yacht_name }}"
yacht_role_web_domain: "{{ user.domain }}"
yacht_role_web_port: "8000"
yacht_role_web_url: "{{ 'https://' + (yacht_role_web_subdomain + '.' + yacht_role_web_domain
                if (yacht_role_web_subdomain | length > 0)
                else yacht_role_web_domain) }}"

################################
# DNS
################################

yacht_role_dns_record: "{{ yacht_role_web_subdomain }}"
yacht_role_dns_zone: "{{ yacht_role_web_domain }}"
yacht_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

yacht_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
yacht_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
yacht_role_traefik_middleware_custom: ""
yacht_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
yacht_role_traefik_enabled: true
yacht_role_traefik_api_enabled: false
yacht_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
yacht_role_docker_container: "{{ yacht_name }}"

# Image
yacht_role_docker_image_pull: true
yacht_role_docker_image_tag: "latest"
yacht_role_docker_image: "selfhostedpro/yacht:{{ yacht_role_docker_image_tag }}"

# Envs
yacht_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  ADMIN_EMAIL: "{{ user.email }}"
  SECRET_KEY: "{{ lookup('password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=16) }}"
  DOCKER_HOST: "tcp://{{ yacht_name }}-docker-socket-proxy:2375"
yacht_role_docker_envs_custom: {}
yacht_role_docker_envs: "{{ yacht_role_docker_envs_default
                       | combine(yacht_role_docker_envs_custom) }}"

# Volumes
yacht_role_docker_volumes_default:
  - "{{ yacht_role_paths_location }}/config:/config"
  - "{{ yacht_role_paths_location }}/storage:/storage"
yacht_role_docker_volumes_custom: []
yacht_role_docker_volumes: "{{ yacht_role_docker_volumes_default
                          + yacht_role_docker_volumes_custom }}"

# Hostname
yacht_role_docker_hostname: "{{ yacht_name }}"

# Networks
yacht_role_docker_networks_alias: "{{ yacht_name }}"
yacht_role_docker_networks_default: []
yacht_role_docker_networks_custom: []
yacht_role_docker_networks: "{{ docker_networks_common
                           + yacht_role_docker_networks_default
                           + yacht_role_docker_networks_custom }}"

# Restart Policy
yacht_role_docker_restart_policy: unless-stopped

# State
yacht_role_docker_state: started

# Dependencies
yacht_depends_on: "{{ yacht_name }}-docker-socket-proxy"
yacht_depends_on_delay: "0"
yacht_depends_on_healthchecks: "false"
