#########################################################################
# Title:         Sandbox: Cleanuparr | Default Variables                #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

cleanuparr_name: cleanuparr

################################
# Paths
################################

cleanuparr_role_paths_folder: "{{ cleanuparr_name }}"
cleanuparr_role_paths_location: "{{ server_appdata_path }}/{{ cleanuparr_role_paths_folder }}"
cleanuparr_role_paths_folders_list:
  - "{{ cleanuparr_role_paths_location }}"

################################
# Web
################################

cleanuparr_role_web_subdomain: "{{ cleanuparr_name }}"
cleanuparr_role_web_domain: "{{ user.domain }}"
cleanuparr_role_web_port: "11011"
cleanuparr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='cleanuparr') + '.' + lookup('role_var', '_web_domain', role='cleanuparr')
                          if (lookup('role_var', '_web_subdomain', role='cleanuparr') | length > 0)
                          else lookup('role_var', '_web_domain', role='cleanuparr')) }}"

################################
# DNS
################################

cleanuparr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='cleanuparr') }}"
cleanuparr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='cleanuparr') }}"
cleanuparr_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

cleanuparr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
cleanuparr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
cleanuparr_role_traefik_middleware_custom: ""
cleanuparr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
cleanuparr_role_traefik_enabled: true
cleanuparr_role_traefik_api_enabled: false
cleanuparr_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
cleanuparr_role_docker_container: "{{ cleanuparr_name }}"

# Image
cleanuparr_role_docker_image_pull: true
cleanuparr_role_docker_image_repo: "ghcr.io/cleanuparr/cleanuparr"
cleanuparr_role_docker_image_tag: "latest"
cleanuparr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='cleanuparr') }}:{{ lookup('role_var', '_docker_image_tag', role='cleanuparr') }}"

# Envs
cleanuparr_role_docker_envs_default:
  PORT: "{{ lookup('role_var', '_web_port', role='cleanuparr') }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "022"
  TZ: "{{ tz }}"
cleanuparr_role_docker_envs_custom: {}
cleanuparr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='cleanuparr')
                                 | combine(lookup('role_var', '_docker_envs_custom', role='cleanuparr')) }}"

# Volumes
cleanuparr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='cleanuparr') }}:/config"
cleanuparr_role_docker_volumes_custom: []
cleanuparr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='cleanuparr')
                                    + lookup('role_var', '_docker_volumes_custom', role='cleanuparr') }}"

# Hostname
cleanuparr_role_docker_hostname: "{{ cleanuparr_name }}"

# Networks
cleanuparr_role_docker_networks_alias: "{{ cleanuparr_name }}"
cleanuparr_role_docker_networks_default: []
cleanuparr_role_docker_networks_custom: []
cleanuparr_role_docker_networks: "{{ docker_networks_common
                                     + lookup('role_var', '_docker_networks_default', role='cleanuparr')
                                     + lookup('role_var', '_docker_networks_custom', role='cleanuparr') }}"

# Restart Policy
cleanuparr_role_docker_restart_policy: unless-stopped

# State
cleanuparr_role_docker_state: started
