##########################################################################
# Title:         Sandbox: Adminer | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

adminer_name: adminer

################################
# Web
################################

adminer_role_web_subdomain: "{{ adminer_name }}"
adminer_role_web_domain: "{{ user.domain }}"
adminer_role_web_port: "8080"
adminer_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='adminer') + '.' + lookup('role_var', '_web_domain', role='adminer')
                       if (lookup('role_var', '_web_subdomain', role='adminer') | length > 0)
                       else lookup('role_var', '_web_domain', role='adminer')) }}"

################################
# DNS
################################

adminer_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='adminer') }}"
adminer_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='adminer') }}"
adminer_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

adminer_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
adminer_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
adminer_role_traefik_middleware_custom: ""
adminer_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
adminer_role_traefik_enabled: true

################################
# Docker
################################

# Container
adminer_role_docker_container: "{{ adminer_name }}"

# Image
adminer_role_docker_image_pull: true
adminer_role_docker_image_repo: "adminer"
adminer_role_docker_image_tag: "latest"
adminer_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='adminer') }}:{{ lookup('role_var', '_docker_image_tag', role='adminer') }}"

# Envs
adminer_role_docker_envs_default:
  ADMINER_DEFAULT_SERVER: "mysql"
adminer_role_docker_envs_custom: {}
adminer_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='adminer')
                              | combine(lookup('role_var', '_docker_envs_custom', role='adminer')) }}"

# Hostname
adminer_role_docker_hostname: "{{ adminer_name }}"

# Networks
adminer_role_docker_networks_alias: "{{ adminer_name }}"
adminer_role_docker_networks_default: []
adminer_role_docker_networks_custom: []
adminer_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='adminer')
                                  + lookup('role_var', '_docker_networks_custom', role='adminer') }}"

# Restart Policy
adminer_role_docker_restart_policy: unless-stopped

# State
adminer_role_docker_state: started
