#########################################################################
# Title:            Sandbox: Monitorr                                   #
# Author(s):        Superduper09, Kalroth, kowalski                     #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

monitorr_name: monitorr

################################
# Paths
################################

monitorr_paths_folder: "{{ monitorr_name }}"
monitorr_paths_location: "{{ server_appdata_path }}/{{ monitorr_paths_folder }}"
monitorr_paths_folders_list:
  - "{{ monitorr_paths_location }}"

################################
# Web
################################

monitorr_web_subdomain: "{{ monitorr_name }}"
monitorr_web_domain: "{{ user.domain }}"
monitorr_web_port: "80"
monitorr_web_url: "{{ 'https://' + (monitorr_web_subdomain + '.' + monitorr_web_domain
                   if (monitorr_web_subdomain | length > 0)
                   else monitorr_web_domain) }}"

################################
# DNS
################################

monitorr_dns_record: "{{ monitorr_web_subdomain }}"
monitorr_dns_zone: "{{ monitorr_web_domain }}"
monitorr_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

monitorr_traefik_sso_middleware: ""
monitorr_traefik_middleware_default: "{{ traefik_default_middleware }}"
monitorr_traefik_middleware_custom: ""
monitorr_traefik_certresolver: "{{ traefik_default_certresolver }}"
monitorr_traefik_enabled: true
monitorr_traefik_api_enabled: false
monitorr_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
monitorr_docker_container: "{{ monitorr_name }}"

# Image
monitorr_docker_image_pull: true
monitorr_docker_image_tag: "develop"
monitorr_docker_image: "monitorr/monitorr:{{ monitorr_docker_image_tag }}"

# Ports
monitorr_docker_ports_defaults: []
monitorr_docker_ports_custom: []
monitorr_docker_ports: "{{ monitorr_docker_ports_defaults
                           + monitorr_docker_ports_custom }}"

# Envs
monitorr_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
monitorr_docker_envs_custom: {}
monitorr_docker_envs: "{{ monitorr_docker_envs_default
                          | combine(monitorr_docker_envs_custom) }}"

# Commands
monitorr_docker_commands_default: []
monitorr_docker_commands_custom: []
monitorr_docker_commands: "{{ monitorr_docker_commands_default
                              + monitorr_docker_commands_custom }}"

# Volumes
monitorr_docker_volumes_default:
  - "{{ monitorr_paths_location }}:/app"
monitorr_docker_volumes_custom: []
monitorr_docker_volumes: "{{ monitorr_docker_volumes_default
                             + monitorr_docker_volumes_custom }}"

# Devices
monitorr_docker_devices_default: []
monitorr_docker_devices_custom: []
monitorr_docker_devices: "{{ monitorr_docker_devices_default
                             + monitorr_docker_devices_custom }}"

# Hosts
monitorr_docker_hosts_default: {}
monitorr_docker_hosts_custom: {}
monitorr_docker_hosts: "{{ docker_hosts_common
                           | combine(monitorr_docker_hosts_default)
                           | combine(monitorr_docker_hosts_custom) }}"

# Labels
monitorr_docker_labels_default: {}
monitorr_docker_labels_custom: {}
monitorr_docker_labels: "{{ docker_labels_common
                            | combine(monitorr_docker_labels_default)
                            | combine(monitorr_docker_labels_custom) }}"

# Hostname
monitorr_docker_hostname: "{{ monitorr_name }}"

# Networks
monitorr_docker_networks_alias: "{{ monitorr_name }}"
monitorr_docker_networks_default: []
monitorr_docker_networks_custom: []
monitorr_docker_networks: "{{ docker_networks_common
                              + monitorr_docker_networks_default
                              + monitorr_docker_networks_custom }}"

# Capabilities
monitorr_docker_capabilities_default: []
monitorr_docker_capabilities_custom: []
monitorr_docker_capabilities: "{{ monitorr_docker_capabilities_default
                                  + monitorr_docker_capabilities_custom }}"

# Security Opts
monitorr_docker_security_opts_default: []
monitorr_docker_security_opts_custom: []
monitorr_docker_security_opts: "{{ monitorr_docker_security_opts_default
                                   + monitorr_docker_security_opts_custom }}"

# Restart Policy
monitorr_docker_restart_policy: unless-stopped

# State
monitorr_docker_state: started
