#########################################################################
# Title:            Sandbox: Monitorr                                   #
# Author(s):        Superduper09, Kalroth, kowalski                     #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

monitorr_name: monitorr

################################
# Paths
################################

monitorr_role_paths_folder: "{{ monitorr_name }}"
monitorr_role_paths_location: "{{ server_appdata_path }}/{{ monitorr_role_paths_folder }}"
monitorr_role_paths_folders_list:
  - "{{ monitorr_role_paths_location }}"

################################
# Web
################################

monitorr_role_web_subdomain: "{{ monitorr_name }}"
monitorr_role_web_domain: "{{ user.domain }}"
monitorr_role_web_port: "80"
monitorr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='monitorr') + '.' + lookup('role_var', '_web_domain', role='monitorr')
                        if (lookup('role_var', '_web_subdomain', role='monitorr') | length > 0)
                        else lookup('role_var', '_web_domain', role='monitorr')) }}"

################################
# DNS
################################

monitorr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='monitorr') }}"
monitorr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='monitorr') }}"
monitorr_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

monitorr_role_traefik_sso_middleware: ""
monitorr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
monitorr_role_traefik_middleware_custom: ""
monitorr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
monitorr_role_traefik_enabled: true
monitorr_role_traefik_api_enabled: false
monitorr_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
monitorr_role_docker_container: "{{ monitorr_name }}"

# Image
monitorr_role_docker_image_pull: true
monitorr_role_docker_image_tag: "develop"
monitorr_role_docker_image_repo: "monitorr/monitorr"
monitorr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='monitorr') }}:{{ lookup('role_var', '_docker_image_tag', role='monitorr') }}"

# Envs
monitorr_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
monitorr_role_docker_envs_custom: {}
monitorr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='monitorr')
                               | combine(lookup('role_var', '_docker_envs_custom', role='monitorr')) }}"

# Volumes
monitorr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='monitorr') }}:/app"
monitorr_role_docker_volumes_custom: []
monitorr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='monitorr')
                                  + lookup('role_var', '_docker_volumes_custom', role='monitorr') }}"

# Hostname
monitorr_role_docker_hostname: "{{ monitorr_name }}"

# Networks
monitorr_role_docker_networks_alias: "{{ monitorr_name }}"
monitorr_role_docker_networks_default: []
monitorr_role_docker_networks_custom: []
monitorr_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='monitorr')
                                   + lookup('role_var', '_docker_networks_custom', role='monitorr') }}"

# Restart Policy
monitorr_role_docker_restart_policy: unless-stopped

# State
monitorr_role_docker_state: started
