#########################################################################
# Title:            Sandbox: Filezilla                                  #
# Author(s):        chazlarson, kowalski                                #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

filezilla_name: filezilla

################################
# Paths
################################

filezilla_role_paths_folder: "{{ filezilla_name }}"
filezilla_role_paths_location: "{{ server_appdata_path }}/{{ filezilla_role_paths_folder }}"
filezilla_role_paths_folders_list:
  - "{{ filezilla_role_paths_location }}"
  - "{{ filezilla_role_paths_location }}/config"

################################
# Web
################################

filezilla_role_web_subdomain: "{{ filezilla_name }}"
filezilla_role_web_domain: "{{ user.domain }}"
filezilla_role_web_port: "5800"
filezilla_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='filezilla') + '.' + lookup('role_var', '_web_domain', role='filezilla')
                         if (lookup('role_var', '_web_subdomain', role='filezilla') | length > 0)
                         else lookup('role_var', '_web_domain', role='filezilla')) }}"

################################
# DNS
################################

filezilla_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='filezilla') }}"
filezilla_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='filezilla') }}"
filezilla_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

filezilla_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
filezilla_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
filezilla_role_traefik_middleware_custom: ""
filezilla_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
filezilla_role_traefik_enabled: true
filezilla_role_traefik_api_enabled: false
filezilla_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
filezilla_role_docker_container: "{{ filezilla_name }}"

# Image
filezilla_role_docker_image_pull: true
filezilla_role_docker_image_repo: "jlesage/filezilla"
filezilla_role_docker_image_tag: "latest"
filezilla_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='filezilla') }}:{{ lookup('role_var', '_docker_image_tag', role='filezilla') }}"

# Envs
filezilla_role_docker_envs_default:
  USER_ID: "{{ uid }}"
  GROUP_ID: "{{ gid }}"
  TZ: "{{ tz }}"
  KEEP_APP_RUNNING: "1"
filezilla_role_docker_envs_custom: {}
filezilla_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='filezilla')
                                | combine(lookup('role_var', '_docker_envs_custom', role='filezilla')) }}"

# Volumes
filezilla_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='filezilla') }}/config:/config"
  - "/home/{{ user.name }}:/storage"
filezilla_role_docker_volumes_custom: []
filezilla_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='filezilla')
                                   + lookup('role_var', '_docker_volumes_custom', role='filezilla') }}"

# Hostname
filezilla_role_docker_hostname: "{{ filezilla_name }}"

# Networks
filezilla_role_docker_networks_alias: "{{ filezilla_name }}"
filezilla_role_docker_networks_default: []
filezilla_role_docker_networks_custom: []
filezilla_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='filezilla')
                                    + lookup('role_var', '_docker_networks_custom', role='filezilla') }}"

# Restart Policy
filezilla_role_docker_restart_policy: unless-stopped

# State
filezilla_role_docker_state: started
