#########################################################################
# Title:            Sandbox: Filezilla                                  #
# Author(s):        chazlarson, kowalski                                #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

filezilla_name: filezilla

################################
# Paths
################################

filezilla_paths_folder: "{{ filezilla_name }}"
filezilla_paths_location: "{{ server_appdata_path }}/{{ filezilla_paths_folder }}"
filezilla_paths_folders_list:
  - "{{ filezilla_paths_location }}"
  - "{{ filezilla_paths_location }}/config"

################################
# Web
################################

filezilla_web_subdomain: "{{ filezilla_name }}"
filezilla_web_domain: "{{ user.domain }}"
filezilla_web_port: "5800"
filezilla_web_url: "{{ 'https://' + (filezilla_web_subdomain + '.' + filezilla_web_domain
                    if (filezilla_web_subdomain | length > 0)
                    else filezilla_web_domain) }}"

################################
# DNS
################################

filezilla_dns_record: "{{ filezilla_web_subdomain }}"
filezilla_dns_zone: "{{ filezilla_web_domain }}"
filezilla_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

filezilla_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
filezilla_traefik_middleware_default: "{{ traefik_default_middleware }}"
filezilla_traefik_middleware_custom: ""
filezilla_traefik_certresolver: "{{ traefik_default_certresolver }}"
filezilla_traefik_enabled: true
filezilla_traefik_api_enabled: false
filezilla_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
filezilla_docker_container: "{{ filezilla_name }}"

# Image
filezilla_docker_image_pull: true
filezilla_docker_image_tag: "latest"
filezilla_docker_image: "jlesage/filezilla:{{ filezilla_docker_image_tag }}"

# Ports
filezilla_docker_ports_defaults: []
filezilla_docker_ports_custom: []
filezilla_docker_ports: "{{ filezilla_docker_ports_defaults
                            + filezilla_docker_ports_custom }}"

# Envs
filezilla_docker_envs_default:
  USER_ID: "{{ uid }}"
  GROUP_ID: "{{ gid }}"
  TZ: "{{ tz }}"
  KEEP_APP_RUNNING: "1"
filezilla_docker_envs_custom: {}
filezilla_docker_envs: "{{ filezilla_docker_envs_default
                           | combine(filezilla_docker_envs_custom) }}"

# Commands
filezilla_docker_commands_default: []
filezilla_docker_commands_custom: []
filezilla_docker_commands: "{{ filezilla_docker_commands_default
                               + filezilla_docker_commands_custom }}"

# Volumes
filezilla_docker_volumes_default:
  - "{{ filezilla_paths_location }}/config:/config"
  - "/home/{{ user.name }}:/storage"
filezilla_docker_volumes_custom: []
filezilla_docker_volumes: "{{ filezilla_docker_volumes_default
                              + filezilla_docker_volumes_custom }}"

# Devices
filezilla_docker_devices_default: []
filezilla_docker_devices_custom: []
filezilla_docker_devices: "{{ filezilla_docker_devices_default
                              + filezilla_docker_devices_custom }}"

# Hosts
filezilla_docker_hosts_default: {}
filezilla_docker_hosts_custom: {}
filezilla_docker_hosts: "{{ docker_hosts_common
                            | combine(filezilla_docker_hosts_default)
                            | combine(filezilla_docker_hosts_custom) }}"

# Labels
filezilla_docker_labels_default: {}
filezilla_docker_labels_custom: {}
filezilla_docker_labels: "{{ docker_labels_common
                             | combine(filezilla_docker_labels_default)
                             | combine(filezilla_docker_labels_custom) }}"

# Hostname
filezilla_docker_hostname: "{{ filezilla_name }}"

# Networks
filezilla_docker_networks_alias: "{{ filezilla_name }}"
filezilla_docker_networks_default: []
filezilla_docker_networks_custom: []
filezilla_docker_networks: "{{ docker_networks_common
                               + filezilla_docker_networks_default
                               + filezilla_docker_networks_custom }}"

# Capabilities
filezilla_docker_capabilities_default: []
filezilla_docker_capabilities_custom: []
filezilla_docker_capabilities: "{{ filezilla_docker_capabilities_default
                                   + filezilla_docker_capabilities_custom }}"

# Security Opts
filezilla_docker_security_opts_default: []
filezilla_docker_security_opts_custom: []
filezilla_docker_security_opts: "{{ filezilla_docker_security_opts_default
                                    + filezilla_docker_security_opts_custom }}"

# Restart Policy
filezilla_docker_restart_policy: unless-stopped

# State
filezilla_docker_state: started
