#########################################################################
# Title:         Sandbox: Sanity Check | Touch Logs                     #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Touch Logs | Get 'sandbox.yml' info."
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/sandbox.yml"
  register: sandbox_yml

- name: "Touch Logs | Touch 'sandbox.log'"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/sandbox.log"
    state: touch
    owner: "{{ sandbox_yml.stat.uid }}"
    group: "{{ sandbox_yml.stat.gid }}"
    mode: "0664"
