#########################################################################
# Title:            Sandbox: Firefox                                    #
# Author(s):        keldian                                             #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Import default `{{ lookup('role_var', '_paths_env_file_location', role='firefox') | basename }}` if necessary
  ansible.builtin.template:
    src: env.j2
    dest: "{{ lookup('role_var', '_paths_env_file_location', role='firefox') }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
    force: false

- name: Docker Devices Task
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when: gpu.intel or use_nvidia

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Wait for service availability
  ansible.builtin.wait_for:
    host: "{{ lookup('role_var', '_docker_networks_alias', role='firefox') }}"
    port: "{{ lookup('role_var', '_web_port', role='firefox') }}"

- name: Remove empty subdirectories of `{{ lookup('role_var', '_paths_location', role='firefox') }}`
  ansible.builtin.shell: find "{{ lookup('role_var', '_paths_location', role='firefox') }}" -maxdepth 1 -type d -empty -exec rmdir {} +
