##########################################################################
# Title:         Sandbox: Jellyseerr | Default Variables                 #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

jellyseerr_instances: ["jellyseerr"]

################################
# Settings
################################

jellyseerr_log_level: "INFO"
jellyseerr_emby: false

################################
# Paths
################################

jellyseerr_paths_folder: "{{ jellyseerr_name }}"
jellyseerr_paths_location: "{{ server_appdata_path }}/{{ jellyseerr_paths_folder }}"
jellyseerr_paths_folders_list:
  - "{{ jellyseerr_paths_location }}"

################################
# Web
################################

jellyseerr_web_subdomain: "{{ jellyseerr_name }}"
jellyseerr_web_domain: "{{ user.domain }}"
jellyseerr_web_port: "5055"
jellyseerr_web_url: "{{ 'https://' + (lookup('vars', jellyseerr_name + '_web_subdomain', default=jellyseerr_web_subdomain) + '.' + lookup('vars', jellyseerr_name + '_web_domain', default=jellyseerr_web_domain)
                     if (lookup('vars', jellyseerr_name + '_web_subdomain', default=jellyseerr_web_subdomain) | length > 0)
                     else lookup('vars', jellyseerr_name + '_web_domain', default=jellyseerr_web_domain)) }}"

################################
# DNS
################################

jellyseerr_dns_record: "{{ lookup('vars', jellyseerr_name + '_web_subdomain', default=jellyseerr_web_subdomain) }}"
jellyseerr_dns_zone: "{{ lookup('vars', jellyseerr_name + '_web_domain', default=jellyseerr_web_domain) }}"
jellyseerr_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

jellyseerr_traefik_sso_middleware: ""
jellyseerr_traefik_middleware_default: "{{ traefik_default_middleware }}"
jellyseerr_traefik_middleware_custom: ""
jellyseerr_traefik_certresolver: "{{ traefik_default_certresolver }}"
jellyseerr_traefik_enabled: true
jellyseerr_traefik_api_enabled: false
jellyseerr_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
jellyseerr_docker_container: "{{ jellyseerr_name }}"

# Image
jellyseerr_docker_image_pull: true
jellyseerr_docker_image_repo: "fallenbagel/jellyseerr"
jellyseerr_docker_image_tag: "latest"
jellyseerr_docker_image: "{{ lookup('vars', jellyseerr_name + '_docker_image_repo', default=jellyseerr_docker_image_repo)
                             + ':' + lookup('vars', jellyseerr_name + '_docker_image_tag', default=jellyseerr_docker_image_tag) }}"

# Ports
jellyseerr_docker_ports_defaults: []
jellyseerr_docker_ports_custom: []
jellyseerr_docker_ports: "{{ lookup('vars', jellyseerr_name + '_docker_ports_defaults', default=jellyseerr_docker_ports_defaults)
                             + lookup('vars', jellyseerr_name + '_docker_ports_custom', default=jellyseerr_docker_ports_custom) }}"

# Envs
jellyseerr_docker_envs_default:
  UMASK: "002"
  TZ: "{{ tz }}"
  LOG_LEVEL: "{{ jellyseerr_log_level }}"
  JELLYFIN_TYPE: "{{ 'emby' if jellyseerr_emby else omit }}"
jellyseerr_docker_envs_custom: {}
jellyseerr_docker_envs: "{{ lookup('vars', jellyseerr_name + '_docker_envs_default', default=jellyseerr_docker_envs_default)
                            | combine(lookup('vars', jellyseerr_name + '_docker_envs_custom', default=jellyseerr_docker_envs_custom)) }}"

# Commands
jellyseerr_docker_commands_default: []
jellyseerr_docker_commands_custom: []
jellyseerr_docker_commands: "{{ lookup('vars', jellyseerr_name + '_docker_commands_default', default=jellyseerr_docker_commands_default)
                                + lookup('vars', jellyseerr_name + '_docker_commands_custom', default=jellyseerr_docker_commands_custom) }}"

# Volumes
jellyseerr_docker_volumes_default:
  - "{{ jellyseerr_paths_location }}:/app/config"
jellyseerr_docker_volumes_custom: []
jellyseerr_docker_volumes: "{{ lookup('vars', jellyseerr_name + '_docker_volumes_default', default=jellyseerr_docker_volumes_default)
                               + lookup('vars', jellyseerr_name + '_docker_volumes_custom', default=jellyseerr_docker_volumes_custom) }}"

# Devices
jellyseerr_docker_devices_default: []
jellyseerr_docker_devices_custom: []
jellyseerr_docker_devices: "{{ lookup('vars', jellyseerr_name + '_docker_devices_default', default=jellyseerr_docker_devices_default)
                               + lookup('vars', jellyseerr_name + '_docker_devices_custom', default=jellyseerr_docker_devices_custom) }}"

# Hosts
jellyseerr_docker_hosts_default: {}
jellyseerr_docker_hosts_custom: {}
jellyseerr_docker_hosts: "{{ docker_hosts_common
                             | combine(lookup('vars', jellyseerr_name + '_docker_hosts_default', default=jellyseerr_docker_hosts_default))
                             | combine(lookup('vars', jellyseerr_name + '_docker_hosts_custom', default=jellyseerr_docker_hosts_custom)) }}"

# Labels
jellyseerr_docker_labels_default: {}
jellyseerr_docker_labels_custom: {}
jellyseerr_docker_labels: "{{ docker_labels_common
                              | combine(lookup('vars', jellyseerr_name + '_docker_labels_default', default=jellyseerr_docker_labels_default))
                              | combine(lookup('vars', jellyseerr_name + '_docker_labels_custom', default=jellyseerr_docker_labels_custom)) }}"

# Hostname
jellyseerr_docker_hostname: "{{ jellyseerr_name }}"

# Network Mode
jellyseerr_docker_network_mode_default: "{{ docker_networks_name_common }}"
jellyseerr_docker_network_mode: "{{ lookup('vars', jellyseerr_name + '_docker_network_mode_default', default=jellyseerr_docker_network_mode_default) }}"

# Networks
jellyseerr_docker_networks_alias: "{{ jellyseerr_name }}"
jellyseerr_docker_networks_default: []
jellyseerr_docker_networks_custom: []
jellyseerr_docker_networks: "{{ docker_networks_common
                                + lookup('vars', jellyseerr_name + '_docker_networks_default', default=jellyseerr_docker_networks_default)
                                + lookup('vars', jellyseerr_name + '_docker_networks_custom', default=jellyseerr_docker_networks_custom) }}"

# Capabilities
jellyseerr_docker_capabilities_default: []
jellyseerr_docker_capabilities_custom: []
jellyseerr_docker_capabilities: "{{ lookup('vars', jellyseerr_name + '_docker_capabilities_default', default=jellyseerr_docker_capabilities_default)
                                    + lookup('vars', jellyseerr_name + '_docker_capabilities_custom', default=jellyseerr_docker_capabilities_custom) }}"

# Security Opts
jellyseerr_docker_security_opts_default: []
jellyseerr_docker_security_opts_custom: []
jellyseerr_docker_security_opts: "{{ lookup('vars', jellyseerr_name + '_docker_security_opts_default', default=jellyseerr_docker_security_opts_default)
                                     + lookup('vars', jellyseerr_name + '_docker_security_opts_custom', default=jellyseerr_docker_security_opts_custom) }}"

# Restart Policy
jellyseerr_docker_restart_policy: unless-stopped

# State
jellyseerr_docker_state: started

# User
jellyseerr_docker_user: "{{ uid }}:{{ gid }}"
