##########################################################################
# Title:         Sandbox: Vaultwarden | Default Variables                #
# Author(s):     salty, TABLE                                            #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

vaultwarden_name: vaultwarden

################################
# Paths
################################

vaultwarden_paths_folder: "{{ vaultwarden_name }}"
vaultwarden_paths_location: "{{ server_appdata_path }}/{{ vaultwarden_paths_folder }}"
vaultwarden_paths_folders_list:
  - "{{ vaultwarden_paths_location }}"
vaultwarden_paths_config_location: "{{ vaultwarden_paths_location }}/env"

################################
# Web
################################

vaultwarden_web_subdomain: "{{ vaultwarden_name }}"
vaultwarden_web_domain: "{{ user.domain }}"
vaultwarden_web_port: "6423"
vaultwarden_web_url: "{{ 'https://' + (vaultwarden_web_subdomain + '.' + vaultwarden_web_domain
                      if (vaultwarden_web_subdomain | length > 0)
                      else vaultwarden_web_domain) }}"

################################
# DNS
################################

vaultwarden_dns_record: "{{ vaultwarden_web_subdomain }}"
vaultwarden_dns_zone: "{{ vaultwarden_web_domain }}"
vaultwarden_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

vaultwarden_traefik_sso_middleware: ""
vaultwarden_traefik_middleware_default: "{{ traefik_default_middleware }}"
vaultwarden_traefik_middleware_custom: ""
vaultwarden_traefik_certresolver: "{{ traefik_default_certresolver }}"
vaultwarden_traefik_enabled: true
vaultwarden_traefik_api_enabled: false
vaultwarden_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
vaultwarden_docker_container: "{{ vaultwarden_name }}"

# Image
vaultwarden_docker_image_pull: true
vaultwarden_docker_image_tag: "latest"
vaultwarden_docker_image: "vaultwarden/server:{{ vaultwarden_docker_image_tag }}"

# Ports
vaultwarden_docker_ports_defaults: []
vaultwarden_docker_ports_custom: []
vaultwarden_docker_ports: "{{ vaultwarden_docker_ports_defaults
                              + vaultwarden_docker_ports_custom }}"

# Envs
vaultwarden_docker_envs_default:
  TZ: "{{ tz }}"
  ROCKET_PORT: "{{ vaultwarden_web_port }}"
vaultwarden_docker_envs_custom: {}
vaultwarden_docker_envs: "{{ vaultwarden_docker_envs_default
                             | combine(vaultwarden_docker_envs_custom) }}"

# Commands
vaultwarden_docker_commands_default: []
vaultwarden_docker_commands_custom: []
vaultwarden_docker_commands: "{{ vaultwarden_docker_commands_default
                                 + vaultwarden_docker_commands_custom }}"

# Volumes
vaultwarden_docker_volumes_default:
  - "{{ vaultwarden_paths_location }}:/data"
  - "{{ vaultwarden_paths_location }}/env:/.env"
vaultwarden_docker_volumes_custom: []
vaultwarden_docker_volumes: "{{ vaultwarden_docker_volumes_default
                                + vaultwarden_docker_volumes_custom }}"

# Devices
vaultwarden_docker_devices_default: []
vaultwarden_docker_devices_custom: []
vaultwarden_docker_devices: "{{ vaultwarden_docker_devices_default
                                + vaultwarden_docker_devices_custom }}"

# Hosts
vaultwarden_docker_hosts_default: {}
vaultwarden_docker_hosts_custom: {}
vaultwarden_docker_hosts: "{{ docker_hosts_common
                              | combine(vaultwarden_docker_hosts_default)
                              | combine(vaultwarden_docker_hosts_custom) }}"

# Labels
vaultwarden_docker_labels_default: {}
vaultwarden_docker_labels_custom: {}
vaultwarden_docker_labels: "{{ docker_labels_common
                               | combine(vaultwarden_docker_labels_default)
                               | combine(vaultwarden_docker_labels_custom) }}"

# Hostname
vaultwarden_docker_hostname: "{{ vaultwarden_name }}"

# Networks
vaultwarden_docker_networks_alias: "{{ vaultwarden_name }}"
vaultwarden_docker_networks_default: []
vaultwarden_docker_networks_custom: []
vaultwarden_docker_networks: "{{ docker_networks_common
                                 + vaultwarden_docker_networks_default
                                 + vaultwarden_docker_networks_custom }}"

# Capabilities
vaultwarden_docker_capabilities_default: []
vaultwarden_docker_capabilities_custom: []
vaultwarden_docker_capabilities: "{{ vaultwarden_docker_capabilities_default
                                     + vaultwarden_docker_capabilities_custom }}"

# Security Opts
vaultwarden_docker_security_opts_default: []
vaultwarden_docker_security_opts_custom: []
vaultwarden_docker_security_opts: "{{ vaultwarden_docker_security_opts_default
                                      + vaultwarden_docker_security_opts_custom }}"

# Restart Policy
vaultwarden_docker_restart_policy: unless-stopped

# State
vaultwarden_docker_state: started
