##########################################################################
# Title:            Sandbox: Paperless-AI | Default Variables            #
# Author(s):        salty                                                #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

paperless_ai_name: paperless-ai

################################
# Paths
################################

paperless_ai_role_paths_folder: "{{ paperless_ai_name }}"
paperless_ai_role_paths_location: "{{ server_appdata_path }}/{{ paperless_ai_role_paths_folder }}"
paperless_ai_role_paths_folders_list:
  - "{{ paperless_ai_role_paths_location }}"

################################
# Web
################################

paperless_ai_role_web_subdomain: "{{ paperless_ai_name }}"
paperless_ai_role_web_domain: "{{ user.domain }}"
paperless_ai_role_web_port: "3000"
paperless_ai_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='paperless_ai') + '.' + lookup('role_var', '_web_domain', role='paperless_ai')
                            if (lookup('role_var', '_web_subdomain', role='paperless_ai') | length > 0)
                            else lookup('role_var', '_web_domain', role='paperless_ai')) }}"

################################
# DNS
################################

paperless_ai_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='paperless_ai') }}"
paperless_ai_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='paperless_ai') }}"
paperless_ai_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

paperless_ai_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
paperless_ai_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
paperless_ai_role_traefik_middleware_custom: ""
paperless_ai_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
paperless_ai_role_traefik_enabled: true
paperless_ai_role_traefik_api_enabled: false
paperless_ai_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
paperless_ai_role_docker_container: "{{ paperless_ai_name }}"

# Image
paperless_ai_role_docker_image_pull: true
paperless_ai_role_docker_image_tag: "latest"
paperless_ai_role_docker_image_repo: "clusterzx/paperless-ai"
paperless_ai_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='paperless_ai') }}:{{ lookup('role_var', '_docker_image_tag', role='paperless_ai') }}"

# Envs
paperless_ai_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
paperless_ai_role_docker_envs_custom: {}
paperless_ai_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='paperless_ai')
                                   | combine(lookup('role_var', '_docker_envs_custom', role='paperless_ai')) }}"

# Volumes
paperless_ai_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='paperless_ai') }}:/app/data"
paperless_ai_role_docker_volumes_custom: []
paperless_ai_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='paperless_ai')
                                      + lookup('role_var', '_docker_volumes_custom', role='paperless_ai') }}"

# Hostname
paperless_ai_role_docker_hostname: "{{ paperless_ai_name }}"

# Networks
paperless_ai_role_docker_networks_alias: "{{ paperless_ai_name }}"
paperless_ai_role_docker_networks_default: []
paperless_ai_role_docker_networks_custom: []
paperless_ai_role_docker_networks: "{{ docker_networks_common
                                       + lookup('role_var', '_docker_networks_default', role='paperless_ai')
                                       + lookup('role_var', '_docker_networks_custom', role='paperless_ai') }}"

# Restart Policy
paperless_ai_role_docker_restart_policy: unless-stopped

# State
paperless_ai_role_docker_state: started

# Create Docker Container Timeout
paperless_ai_docker_create_timeout: 300
