##########################################################################
# Title:            Sandbox: Your Spotify | Default Variables            #
# Author(s):        salty                                                #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

your_spotify_name: your-spotify

################################
# Settings
################################

your_spotify_role_public_key: ""
your_spotify_role_secret_key: ""

################################
# Web
################################

your_spotify_role_web_subdomain: "spotify"
your_spotify_role_web_domain: "{{ user.domain }}"
your_spotify_role_web_port: "80"
your_spotify_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='your_spotify') + '.' + lookup('role_var', '_web_domain', role='your_spotify')
                            if (lookup('role_var', '_web_subdomain', role='your_spotify') | length > 0)
                            else lookup('role_var', '_web_domain', role='your_spotify')) }}"

################################
# DNS
################################

your_spotify_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='your_spotify') }}"
your_spotify_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='your_spotify') }}"
your_spotify_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

your_spotify_role_traefik_sso_middleware: ""
your_spotify_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
your_spotify_role_traefik_middleware_custom: ""
your_spotify_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
your_spotify_role_traefik_enabled: true
your_spotify_role_traefik_api_enabled: false
your_spotify_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
your_spotify_role_docker_container: "{{ your_spotify_name }}"

# Image
your_spotify_role_docker_image_pull: true
your_spotify_role_docker_image_repo: "lscr.io/linuxserver/your_spotify"
your_spotify_role_docker_image_tag: "latest"
your_spotify_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='your_spotify') }}:{{ lookup('role_var', '_docker_image_tag', role='your_spotify') }}"

# Envs
your_spotify_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  APP_URL: "{{ lookup('role_var', '_web_url', role='your_spotify') }}"
  SPOTIFY_PUBLIC: "{{ your_spotify_role_public_key }}"
  SPOTIFY_SECRET: "{{ your_spotify_role_secret_key }}"
  CORS: "{{ lookup('role_var', '_web_url', role='your_spotify') + ':443' }}"
  MONGO_ENDPOINT: "mongodb://your-spotify-db:27017/your_spotify"
your_spotify_role_docker_envs_custom: {}
your_spotify_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='your_spotify')
                                   | combine(lookup('role_var', '_docker_envs_custom', role='your_spotify')) }}"

# Hostname
your_spotify_role_docker_hostname: "{{ your_spotify_name }}"

# Networks
your_spotify_role_docker_networks_alias: "{{ your_spotify_name }}"
your_spotify_role_docker_networks_default: []
your_spotify_role_docker_networks_custom: []
your_spotify_role_docker_networks: "{{ docker_networks_common
                                       + lookup('role_var', '_docker_networks_default', role='your_spotify')
                                       + lookup('role_var', '_docker_networks_custom', role='your_spotify') }}"

# Restart Policy
your_spotify_role_docker_restart_policy: unless-stopped

# State
your_spotify_role_docker_state: started

# Dependencies
your_spotify_role_depends_on: "your-spotify-db"
your_spotify_role_depends_on_delay: "0"
your_spotify_role_depends_on_healthchecks: "false"
