#########################################################################
# Title:            Sandbox: Transmission                               #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

transmission_instances: ["transmission"]

################################
# Paths
################################

transmission_role_paths_folder: "{{ transmission_name }}"
transmission_role_paths_location: "{{ server_appdata_path }}/{{ transmission_role_paths_folder }}"
transmission_role_paths_downloads_location: "{{ downloads_torrents_path }}/{{ transmission_role_paths_folder }}"
transmission_role_paths_folders_list:
  - "{{ transmission_role_paths_location }}"
  - "{{ transmission_role_paths_downloads_location }}"
  - "{{ transmission_role_paths_downloads_location }}/completed"
  - "{{ transmission_role_paths_downloads_location }}/incoming"
  - "{{ transmission_role_paths_downloads_location }}/watched"
  - "{{ transmission_role_paths_downloads_location }}/torrents"
transmission_role_paths_setttings_location: "{{ transmission_role_paths_location }}/settings.json"

################################
# Web
################################

transmission_role_web_subdomain: "{{ transmission_name }}"
transmission_role_web_domain: "{{ user.domain }}"
transmission_role_web_port: "9091"
transmission_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='transmission') + '.' + lookup('role_var', '_web_domain', role='transmission')
                            if (lookup('role_var', '_web_subdomain', role='transmission') | length > 0)
                            else lookup('role_var', '_web_domain', role='transmission')) }}"

################################
# DNS
################################

transmission_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='transmission') }}"
transmission_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='transmission') }}"
transmission_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

transmission_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
transmission_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
transmission_role_traefik_middleware_custom: ""
transmission_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
transmission_role_traefik_enabled: true
transmission_role_traefik_api_enabled: true
transmission_role_traefik_api_endpoint: "PathPrefix(`/rpc`)"

################################
# Docker
################################

# Container
transmission_role_docker_container: "{{ transmission_name }}"

# Image
transmission_role_docker_image_pull: true
transmission_role_docker_image_repo: "lscr.io/linuxserver/transmission"
transmission_role_docker_image_tag: "latest"
transmission_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='transmission') }}:{{ lookup('role_var', '_docker_image_tag', role='transmission') }}"

# Ports
# - Internal and External ports need to match for the next set of ports
# - Lookup available ports and set docker ports accordingly
transmission_role_docker_ports_51413: "{{ port_lookup_51413.meta.port
                                       if (port_lookup_51413.meta.port is defined) and (port_lookup_51413.meta.port | trim | length > 0)
                                       else '51413' }}"
transmission_role_docker_ports_default:
  - "{{ lookup('role_var', '_docker_ports_51413', role='transmission') }}:{{ lookup('role_var', '_docker_ports_51413', role='transmission') }}"
  - "{{ lookup('role_var', '_docker_ports_51413', role='transmission') }}:{{ lookup('role_var', '_docker_ports_51413', role='transmission') }}/udp"
transmission_role_docker_ports_custom: []
transmission_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='transmission')
                                    + lookup('role_var', '_docker_ports_custom', role='transmission') }}"

# Envs
transmission_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  UMASK: "002"
  USER: "{{ user.name }}"
  PASS: "{{ user.pass }}"
transmission_role_docker_envs_custom: {}
transmission_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='transmission')
                                   | combine(lookup('role_var', '_docker_envs_custom', role='transmission')) }}"

# Volumes
transmission_role_docker_volumes_default:
  - "{{ transmission_role_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "{{ transmission_role_paths_downloads_location }}/watched:/watch"
transmission_role_docker_volumes_custom: []
transmission_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='transmission')
                                      + lookup('role_var', '_docker_volumes_custom', role='transmission') }}"

# Hostname
transmission_role_docker_hostname: "{{ transmission_name }}"

# Networks
transmission_role_docker_networks_alias: "{{ transmission_name }}"
transmission_role_docker_networks_default: []
transmission_role_docker_networks_custom: []
transmission_role_docker_networks: "{{ docker_networks_common
                                       + lookup('role_var', '_docker_networks_default', role='transmission')
                                       + lookup('role_var', '_docker_networks_custom', role='transmission') }}"

# Restart Policy
transmission_role_docker_restart_policy: unless-stopped

# Stop Timeout
transmission_role_docker_stop_timeout: 900

# State
transmission_role_docker_state: started
