#########################################################################
# Title:            Sandbox: comicstreamer                              #
# Author(s):        theotocopulitos, kowalski                           #
# URL:              https://github.com/saltyorg/Sandbox                 #
# Docker Image(s):  kalinon/comicstreamer                               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

comicstreamer_name: comicstreamer

################################
# Paths
################################

comicstreamer_paths_folder: "{{ comicstreamer_name }}"
comicstreamer_paths_location: "{{ server_appdata_path }}/{{ comicstreamer_paths_folder }}"
comicstreamer_paths_folders_list:
  - "{{ comicstreamer_paths_location }}"
  - "/mnt/local/Media/Comics"

################################
# Web
################################

comicstreamer_web_subdomain: "{{ comicstreamer_name }}"
comicstreamer_web_domain: "{{ user.domain }}"
comicstreamer_web_port: "32500"
comicstreamer_web_url: "{{ 'https://' + (comicstreamer_web_subdomain + '.' + comicstreamer_web_domain
                        if (comicstreamer_web_subdomain | length > 0)
                        else comicstreamer_web_domain) }}"

################################
# DNS
################################

comicstreamer_dns_record: "{{ comicstreamer_web_subdomain }}"
comicstreamer_dns_zone: "{{ comicstreamer_web_domain }}"
comicstreamer_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

comicstreamer_traefik_sso_middleware: ""
comicstreamer_traefik_middleware_default: "{{ traefik_default_middleware }}"
comicstreamer_traefik_middleware_custom: ""
comicstreamer_traefik_certresolver: "{{ traefik_default_certresolver }}"
comicstreamer_traefik_enabled: true

################################
# Docker
################################

# Container
comicstreamer_docker_container: "{{ comicstreamer_name }}"

# Image
comicstreamer_docker_image_pull: true
comicstreamer_docker_image_tag: "latest"
comicstreamer_docker_image: "kalinon/comicstreamer:{{ comicstreamer_docker_image_tag }}"

# Ports
comicstreamer_docker_ports_defaults: []
comicstreamer_docker_ports_custom: []
comicstreamer_docker_ports: "{{ comicstreamer_docker_ports_defaults
                                + comicstreamer_docker_ports_custom }}"

# Envs
comicstreamer_docker_envs_default:
comicstreamer_docker_envs_custom: {}
comicstreamer_docker_envs: "{{ comicstreamer_docker_envs_default
                               | combine(comicstreamer_docker_envs_custom) }}"

# Commands
comicstreamer_docker_commands_default: []
comicstreamer_docker_commands_custom: []
comicstreamer_docker_commands: "{{ comicstreamer_docker_commands_default
                                   + comicstreamer_docker_commands_custom }}"

# Volumes
comicstreamer_docker_volumes_default:
  - "{{ comicstreamer_paths_location }}:/config"
  - "/mnt/unionfs/Media/Comics:/comics"
comicstreamer_docker_volumes_custom: []
comicstreamer_docker_volumes: "{{ comicstreamer_docker_volumes_default
                                  + comicstreamer_docker_volumes_custom }}"

# Devices
comicstreamer_docker_devices_default: []
comicstreamer_docker_devices_custom: []
comicstreamer_docker_devices: "{{ comicstreamer_docker_devices_default
                                  + comicstreamer_docker_devices_custom }}"

# Hosts
comicstreamer_docker_hosts_default: {}
comicstreamer_docker_hosts_custom: {}
comicstreamer_docker_hosts: "{{ docker_hosts_common
                                | combine(comicstreamer_docker_hosts_default)
                                | combine(comicstreamer_docker_hosts_custom) }}"

# Labels
comicstreamer_docker_labels_default: {}
comicstreamer_docker_labels_custom: {}
comicstreamer_docker_labels: "{{ docker_labels_common
                                 | combine(comicstreamer_docker_labels_default)
                                 | combine(comicstreamer_docker_labels_custom) }}"

# Hostname
comicstreamer_docker_hostname: "{{ comicstreamer_name }}"

# Networks
comicstreamer_docker_networks_alias: "{{ comicstreamer_name }}"
comicstreamer_docker_networks_default: []
comicstreamer_docker_networks_custom: []
comicstreamer_docker_networks: "{{ docker_networks_common
                                   + comicstreamer_docker_networks_default
                                   + comicstreamer_docker_networks_custom }}"

# Capabilities
comicstreamer_docker_capabilities_default: []
comicstreamer_docker_capabilities_custom: []
comicstreamer_docker_capabilities: "{{ comicstreamer_docker_capabilities_default
                                       + comicstreamer_docker_capabilities_custom }}"

# Security Opts
comicstreamer_docker_security_opts_default: []
comicstreamer_docker_security_opts_custom: []
comicstreamer_docker_security_opts: "{{ comicstreamer_docker_security_opts_default
                                        + comicstreamer_docker_security_opts_custom }}"

# Restart Policy
comicstreamer_docker_restart_policy: unless-stopped

# State
comicstreamer_docker_state: started
