##########################################################################
# Title:            Sandbox: Lunasea | Default Variables                 #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

lunasea_name: lunasea

################################
# Paths
################################

lunasea_paths_folder: "{{ lunasea_name }}"
lunasea_paths_location: {}
lunasea_paths_folders_list: []
################################
# Web
################################

lunasea_web_subdomain: "{{ lunasea_name }}"
lunasea_web_domain: "{{ user.domain }}"
lunasea_web_port: "80"
lunasea_web_url: "{{ 'https://' + (lunasea_web_subdomain + '.' + lunasea_web_domain
                  if (lunasea_web_subdomain | length > 0)
                  else lunasea_web_domain) }}"

################################
# DNS
################################

lunasea_dns_record: "{{ lunasea_web_subdomain }}"
lunasea_dns_zone: "{{ lunasea_web_domain }}"
lunasea_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

lunasea_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
lunasea_traefik_middleware_default: "{{ traefik_default_middleware }}"
lunasea_traefik_middleware_custom: ""
lunasea_traefik_certresolver: "{{ traefik_default_certresolver }}"
lunasea_traefik_enabled: true
lunasea_traefik_api_enabled: false
lunasea_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
lunasea_docker_container: "{{ lunasea_name }}"

# Image
lunasea_docker_image_pull: true
lunasea_docker_image_tag: "stable"
lunasea_docker_image: "ghcr.io/jagandeepbrar/lunasea:{{ lunasea_docker_image_tag }}"

# Ports
lunasea_docker_ports_defaults: []
lunasea_docker_ports_custom: []
lunasea_docker_ports: "{{ lunasea_docker_ports_defaults
                          + lunasea_docker_ports_custom }}"

# Envs
lunasea_docker_envs_default:
  TZ: "{{ tz }}"
lunasea_docker_envs_custom: {}
lunasea_docker_envs: "{{ lunasea_docker_envs_default
                         | combine(lunasea_docker_envs_custom) }}"

# Commands
lunasea_docker_commands_default: []
lunasea_docker_commands_custom: []
lunasea_docker_commands: "{{ lunasea_docker_commands_default
                             + lunasea_docker_commands_custom }}"

# Volumes
lunasea_docker_volumes_default: []
lunasea_docker_volumes_custom: []
lunasea_docker_volumes: "{{ lunasea_docker_volumes_default
                            + lunasea_docker_volumes_custom }}"

# Devices
lunasea_docker_devices_default: []
lunasea_docker_devices_custom: []
lunasea_docker_devices: "{{ lunasea_docker_devices_default
                            + lunasea_docker_devices_custom }}"

# Hosts
lunasea_docker_hosts_default: {}
lunasea_docker_hosts_custom: {}
lunasea_docker_hosts: "{{ docker_hosts_common
                          | combine(lunasea_docker_hosts_default)
                          | combine(lunasea_docker_hosts_custom) }}"

# Labels
lunasea_docker_labels_default: {}
lunasea_docker_labels_custom: {}
lunasea_docker_labels: "{{ docker_labels_common
                           | combine(lunasea_docker_labels_default)
                           | combine(lunasea_docker_labels_custom) }}"

# Hostname
lunasea_docker_hostname: "{{ lunasea_name }}"

# Networks
lunasea_docker_networks_alias: "{{ lunasea_name }}"
lunasea_docker_networks_default: []
lunasea_docker_networks_custom: []
lunasea_docker_networks: "{{ docker_networks_common
                             + lunasea_docker_networks_default
                             + lunasea_docker_networks_custom }}"

# Capabilities
lunasea_docker_capabilities_default: []
lunasea_docker_capabilities_custom: []
lunasea_docker_capabilities: "{{ lunasea_docker_capabilities_default
                                 + lunasea_docker_capabilities_custom }}"

# Security Opts
lunasea_docker_security_opts_default: []
lunasea_docker_security_opts_custom: []
lunasea_docker_security_opts: "{{ lunasea_docker_security_opts_default
                                  + lunasea_docker_security_opts_custom }}"

# Restart Policy
lunasea_docker_restart_policy: unless-stopped

# State
lunasea_docker_state: started
