#########################################################################
# Title:         Sandbox: Plex-Credits-Detect                           #
# Author(s):     owine                                             #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

plex_credits_detect_name: plex-credits-detect

################################
# Paths
################################

plex_credits_detect_paths_folder: "{{ plex_credits_detect_name }}"
plex_credits_detect_paths_location: "{{ server_appdata_path }}/{{ plex_credits_detect_paths_folder }}"
plex_credits_detect_config_location: "{{ plex_credits_detect_paths_location }}/fingerprint.ini"
plex_credits_detect_paths_folders_list:
  - "{{ plex_credits_detect_paths_location }}"
  - "{{ plex_credits_detect_paths_location }}/plex-credits-detect"

################################
# Docker
################################

# Container
plex_credits_detect_docker_container: "{{ plex_credits_detect_name }}"

# Image
plex_credits_detect_docker_image_pull: true
plex_credits_detect_docker_image_tag: "main"
plex_credits_detect_docker_image: "cjmanca/plex-credits-detect:{{ plex_credits_detect_docker_image_tag }}"

# Envs
plex_credits_detect_docker_envs_default:
  TZ: "{{ tz }}"
plex_credits_detect_docker_envs_custom: {}
plex_credits_detect_docker_envs: "{{ plex_credits_detect_docker_envs_default
                                     | combine(plex_credits_detect_docker_envs_custom) }}"

# Commands
plex_credits_detect_docker_commands_default: []
plex_credits_detect_docker_commands_custom: []
plex_credits_detect_docker_commands: "{{ plex_credits_detect_docker_commands_default
                                         + plex_credits_detect_docker_commands_custom }}"

# Volumes
plex_credits_detect_docker_volumes_default:
  - "{{ plex_credits_detect_paths_location }}:/config"
  - "{{ plex_paths_db_location }}:/plexdb/com.plexapp.plugins.library.db"
plex_credits_detect_docker_volumes_custom: []
plex_credits_detect_docker_volumes: "{{ plex_credits_detect_docker_volumes_default
                                        + plex_credits_detect_docker_volumes_custom }}"

# Devices
plex_credits_detect_docker_devices_default: []
plex_credits_detect_docker_devices_custom: []
plex_credits_detect_docker_devices: "{{ plex_credits_detect_docker_devices_default
                                        + plex_credits_detect_docker_devices_custom }}"

# Hosts
plex_credits_detect_docker_hosts_default: []
plex_credits_detect_docker_hosts_custom: []
plex_credits_detect_docker_hosts: "{{ docker_hosts_common
                                      | combine(plex_credits_detect_docker_hosts_default)
                                      | combine(plex_credits_detect_docker_hosts_custom) }}"

# Labels
plex_credits_detect_docker_labels_default: {}
plex_credits_detect_docker_labels_custom: {}
plex_credits_detect_docker_labels: "{{ docker_labels_common
                                       | combine(plex_credits_detect_docker_labels_default)
                                       | combine(plex_credits_detect_docker_labels_custom) }}"

# Hostname
plex_credits_detect_docker_hostname: "{{ plex_credits_detect_name }}"

# Networks
plex_credits_detect_docker_networks_alias: "{{ plex_credits_detect_name }}"
plex_credits_detect_docker_networks_default: []
plex_credits_detect_docker_networks_custom: []
plex_credits_detect_docker_networks: "{{ docker_networks_common
                                         + plex_credits_detect_docker_networks_default
                                         + plex_credits_detect_docker_networks_custom }}"

# Capabilities
plex_credits_detect_docker_capabilities_default: []
plex_credits_detect_docker_capabilities_custom: []
plex_credits_detect_docker_capabilities: "{{ plex_credits_detect_docker_capabilities_default
                                             + plex_credits_detect_docker_capabilities_custom }}"

# Security Opts
plex_credits_detect_docker_security_opts_default: []
plex_credits_detect_docker_security_opts_custom: []
plex_credits_detect_docker_security_opts: "{{ plex_credits_detect_docker_security_opts_default
                                              + plex_credits_detect_docker_security_opts_custom }}"

# Restart Policy
plex_credits_detect_docker_restart_policy: unless-stopped

# State
plex_credits_detect_docker_state: started

# Stop Timeout
plex_credits_detect_docker_stop_timeout: 10

# User
plex_credits_detect_docker_user: "{{ uid }}:{{ gid }}"
