#########################################################################
# Title:            Sandbox: InvoiceNinja v5 app                        #
# Author(s):        addbee                                              #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb
  vars:
    mariadb_name: "{{ invoiceninjav5_name }}_mariadb"  # Remove when instance support merged into Saltbox
    mariadb_instances: ["{{ invoiceninjav5_name }}_mariadb"]
    mariadb_docker_env_db: "{{ invoiceninjav5_name }}"
    mariadb_paths_folder: "{{ invoiceninjav5_name }}"
    mariadb_paths_location: "{{ server_appdata_path }}/{{ mariadb_paths_folder }}/mariadb"

- name: Permissions | Create invoiceninja group
  ansible.builtin.group:
    name: invoiceninja
    state: present
    gid: 1500
  ignore_errors: true
- name: Import Default MariaDB variables
  ansible.builtin.include_vars: /srv/git/saltbox/roles/mariadb/defaults/main.yml

- name: Permissions | Add to invoiceninja group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: invoiceninja
    append: yes
  ignore_errors: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1500"
    group: "invoiceninja"
    mode: "0775"
    recurse: true
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: "Settings | Check if in-vhost.conf exists"
  ansible.builtin.stat:
    path: "{{ invoiceninjav5_conf_path }}"
  register: invoiceninjav5_config

- name: "Settings | Import in-vhost.conf"
  ansible.builtin.template:
    src: in-vhost.conf.j2
    dest: '{{ invoiceninjav5_conf_path }}'
    owner: "{{ user.name }}"
    group: "invoiceninja"
    mode: "0775"
    force: yes
  when: not invoiceninjav5_config.stat.exists

- name: Remove existing legacy PostgreSQL container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    _var_prefix: "invoiceninja-nginx"

- name: "Execute nginx role"
  ansible.builtin.include_role:
    name: nginx
  vars:
    nginx_docker_image: "nginx:latest"
    nginx_paths_folder: ""
    nginx_paths_folders_list: []
    nginx_web_subdomain: "{{ invoiceninjav5_nginx_web_subdomain }}"
    nginx_web_domain: "{{ invoiceninjav5_nginx_web_domain }}"
    nginx_dns_record: "{{ invoiceninjav5_nginx_dns_record }}"
    nginx_dns_zone: "{{ invoiceninjav5_nginx_dns_zone }}"
    nginx_dns_proxy: "{{ invoiceninjav5_nginx_dns_proxy }}"
    nginx_instances: ["invoiceninja_nginx"]
    nginx_traefik_middleware: "{{ invoiceninjav5_nginx_traefik_middleware }}"
    nginx_traefik_certresolver: "{{ invoiceninjav5_nginx_traefik_certresolver }}"
    nginx_docker_volumes_default:
      - "{{ invoiceninjav5_paths_location }}/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro"
      - "{{ invoiceninjav5_paths_location }}/public:/var/www/app/public"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
