##########################################################################
# Title:         Sandbox: AirDC++ Role | Default Variables               #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

airdcpp_name: airdcpp

################################
# Paths
################################

airdcpp_role_paths_folder: "{{ airdcpp_name }}"
airdcpp_role_paths_location: "{{ server_appdata_path }}/{{ airdcpp_role_paths_folder }}"
airdcpp_role_paths_folders_list:
  - "{{ airdcpp_role_paths_location }}"
  - /mnt/local/downloads/airdcpp
  - /mnt/local/downloads/airdcpp/Movies
  - /mnt/local/downloads/airdcpp/TV
  - /mnt/local/downloads/airdcpp/4K
  - /mnt/local/downloads/airdcpp/4K/Movies
  - /mnt/local/downloads/airdcpp/4K/TV

################################
# Web
################################

airdcpp_role_web_subdomain: "{{ airdcpp_name }}"
airdcpp_role_web_domain: "{{ user.domain }}"
airdcpp_role_web_port: "5600"
airdcpp_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='airdcpp') + '.' + lookup('role_var', '_web_domain', role='airdcpp')
                       if (lookup('role_var', '_web_subdomain', role='airdcpp') | length > 0)
                       else lookup('role_var', '_web_domain', role='airdcpp')) }}"

################################
# DNS
################################

airdcpp_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='airdcpp') }}"
airdcpp_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='airdcpp') }}"
airdcpp_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

airdcpp_role_traefik_sso_middleware: ""
airdcpp_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
airdcpp_role_traefik_middleware_custom: ""
airdcpp_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
airdcpp_role_traefik_enabled: true
airdcpp_role_traefik_api_enabled: false
airdcpp_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
airdcpp_role_docker_container: "{{ airdcpp_name }}"

# Image
airdcpp_role_docker_image_pull: true
airdcpp_role_docker_image_repo: "gangefors/airdcpp-webclient"
airdcpp_role_docker_image_tag: "latest"
airdcpp_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='airdcpp') }}:{{ lookup('role_var', '_docker_image_tag', role='airdcpp') }}"

# Ports
airdcpp_role_docker_ports_defaults:
  - "21248:21248"
  - "21248:21248/udp"
  - "21249:21249"
airdcpp_role_docker_ports_custom: []
airdcpp_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults', role='airdcpp')
                               + lookup('role_var', '_docker_ports_custom', role='airdcpp') }}"

# Envs
airdcpp_role_docker_envs_default:
  TZ: "{{ tz }}"
airdcpp_role_docker_envs_custom: {}
airdcpp_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='airdcpp')
                              | combine(lookup('role_var', '_docker_envs_custom', role='airdcpp')) }}"

# Volumes
airdcpp_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='airdcpp') }}:/.airdcpp"
  - "/mnt/local/downloads/airdcpp:/Downloads"
airdcpp_role_docker_volumes_custom: []
airdcpp_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='airdcpp')
                                 + lookup('role_var', '_docker_volumes_custom', role='airdcpp') }}"

# Hostname
airdcpp_role_docker_hostname: "{{ airdcpp_name }}"

# Networks
airdcpp_role_docker_networks_alias: "{{ airdcpp_name }}"
airdcpp_role_docker_networks_default: []
airdcpp_role_docker_networks_custom: []
airdcpp_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='airdcpp')
                                  + lookup('role_var', '_docker_networks_custom', role='airdcpp') }}"

# Restart Policy
airdcpp_role_docker_restart_policy: unless-stopped

# State
airdcpp_role_docker_state: started

# User
airdcpp_role_docker_user: "{{ uid }}:{{ gid }}"
