##########################################################################
# Title:         Sandbox: AirDC++ Role | Default Variables               #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

airdcpp_name: airdcpp

################################
# Paths
################################

airdcpp_paths_folder: "{{ airdcpp_name }}"
airdcpp_paths_location: "{{ server_appdata_path }}/{{ airdcpp_paths_folder }}"
airdcpp_paths_folders_list:
  - "{{ airdcpp_paths_location }}"
  - /mnt/local/downloads/airdcpp
  - /mnt/local/downloads/airdcpp/Movies
  - /mnt/local/downloads/airdcpp/TV
  - /mnt/local/downloads/airdcpp/4K
  - /mnt/local/downloads/airdcpp/4K/Movies
  - /mnt/local/downloads/airdcpp/4K/TV

################################
# Web
################################

airdcpp_web_subdomain: "{{ airdcpp_name }}"
airdcpp_web_domain: "{{ user.domain }}"
airdcpp_web_port: "5600"
airdcpp_web_url: "{{ 'https://' + (airdcpp_web_subdomain + '.' + airdcpp_web_domain
                  if (airdcpp_web_subdomain | length > 0)
                  else airdcpp_web_domain) }}"

################################
# DNS
################################

airdcpp_dns_record: "{{ airdcpp_web_subdomain }}"
airdcpp_dns_zone: "{{ airdcpp_web_domain }}"
airdcpp_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

airdcpp_traefik_sso_middleware: ""
airdcpp_traefik_middleware_default: "{{ traefik_default_middleware }}"
airdcpp_traefik_middleware_custom: ""
airdcpp_traefik_certresolver: "{{ traefik_default_certresolver }}"
airdcpp_traefik_enabled: true
airdcpp_traefik_api_enabled: false
airdcpp_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
airdcpp_docker_container: "{{ airdcpp_name }}"

# Image
airdcpp_docker_image_pull: true
airdcpp_docker_image_tag: "latest"
airdcpp_docker_image: "gangefors/airdcpp-webclient:{{ airdcpp_docker_image_tag }}"

# Ports
airdcpp_docker_ports_defaults:
  - "21248:21248"
  - "21248:21248/udp"
  - "21249:21249"
airdcpp_docker_ports_custom: []
airdcpp_docker_ports: "{{ airdcpp_docker_ports_defaults
                          + airdcpp_docker_ports_custom }}"

# Envs
airdcpp_docker_envs_default:
  TZ: "{{ tz }}"
airdcpp_docker_envs_custom: {}
airdcpp_docker_envs: "{{ airdcpp_docker_envs_default
                         | combine(airdcpp_docker_envs_custom) }}"

# Commands
airdcpp_docker_commands_default: []
airdcpp_docker_commands_custom: []
airdcpp_docker_commands: "{{ airdcpp_docker_commands_default
                             + airdcpp_docker_commands_custom }}"

# Volumes
airdcpp_docker_volumes_default:
  - "{{ airdcpp_paths_location }}:/.airdcpp"
  - "/mnt/local/downloads/airdcpp:/Downloads"
airdcpp_docker_volumes_custom: []
airdcpp_docker_volumes: "{{ airdcpp_docker_volumes_default
                            + airdcpp_docker_volumes_custom }}"

# Devices
airdcpp_docker_devices_default: []
airdcpp_docker_devices_custom: []
airdcpp_docker_devices: "{{ airdcpp_docker_devices_default
                            + airdcpp_docker_devices_custom }}"

# Hosts
airdcpp_docker_hosts_default: {}
airdcpp_docker_hosts_custom: {}
airdcpp_docker_hosts: "{{ docker_hosts_common
                          | combine(airdcpp_docker_hosts_default)
                          | combine(airdcpp_docker_hosts_custom) }}"

# Labels
airdcpp_docker_labels_default: {}
airdcpp_docker_labels_custom: {}
airdcpp_docker_labels: "{{ docker_labels_common
                           | combine(airdcpp_docker_labels_default)
                           | combine(airdcpp_docker_labels_custom) }}"

# Hostname
airdcpp_docker_hostname: "{{ airdcpp_name }}"

# Networks
airdcpp_docker_networks_alias: "{{ airdcpp_name }}"
airdcpp_docker_networks_default: []
airdcpp_docker_networks_custom: []
airdcpp_docker_networks: "{{ docker_networks_common
                             + airdcpp_docker_networks_default
                             + airdcpp_docker_networks_custom }}"

# Capabilities
airdcpp_docker_capabilities_default: []
airdcpp_docker_capabilities_custom: []
airdcpp_docker_capabilities: "{{ airdcpp_docker_capabilities_default
                                 + airdcpp_docker_capabilities_custom }}"

# Security Opts
airdcpp_docker_security_opts_default: []
airdcpp_docker_security_opts_custom: []
airdcpp_docker_security_opts: "{{ airdcpp_docker_security_opts_default
                                  + airdcpp_docker_security_opts_custom }}"

# Restart Policy
airdcpp_docker_restart_policy: unless-stopped

# State
airdcpp_docker_state: started

# User
airdcpp_docker_user: "{{ uid }}:{{ gid }}"
