##########################################################################
# Title:            Sandbox: tdarr_node   | Default Variables            #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tdarr_node_name: tdarr-node

################################
# Settings
################################

tdarr_node_server_ip: "tdarr"
tdarr_node_server_port: "8266"
tdarr_node_node_id: "MainNode"
tdarr_node_node_port: "8267"
tdarr_node_external: false

################################
# Docker
################################

# Container
tdarr_node_docker_container: "{{ tdarr_node_name }}"

# Image
tdarr_node_docker_image_pull: true
tdarr_node_docker_image_tag: "latest"
tdarr_node_docker_image: "haveagitgat/tdarr_node:{{ tdarr_node_docker_image_tag }}"

# Ports
tdarr_node_docker_ports_defaults:
  - "{{ tdarr_node_node_port }}:{{ tdarr_node_node_port }}"
tdarr_node_docker_ports_custom: []
tdarr_node_docker_ports: "{{ tdarr_node_docker_ports_defaults if (tdarr_node_external) else []
                             + tdarr_node_docker_ports_custom }}"

# Envs
tdarr_node_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  serverIP: "{{ tdarr_node_server_ip }}"
  serverPort: "{{ tdarr_node_server_port }}"
  nodeName: "{{ tdarr_node_node_id }}"
  inContainer: "true"
tdarr_node_docker_envs_custom: {}
tdarr_node_docker_envs: "{{ tdarr_node_docker_envs_default
                            | combine(tdarr_node_docker_envs_custom) }}"

# Commands
tdarr_node_docker_commands_default: []
tdarr_node_docker_commands_custom: []
tdarr_node_docker_commands: "{{ tdarr_node_docker_commands_default
                                + tdarr_node_docker_commands_custom }}"

# Volumes
tdarr_node_docker_volumes_default:
  - "{{ tdarr_paths_configs_location }}:/app/configs"
  - "{{ tdarr_paths_logs_location }}:/app/logs"
  - "{{ tdarr_paths_transcodes_location }}:/temp"
  - "/mnt/unionfs/Media:/media"
  - "/mnt/unionfs/Media/Movies:/movies"
  - "/mnt/unionfs/Media/TV:/tv"
  - "/dev/shm:/dev/shm"

tdarr_node_docker_volumes_custom: []
tdarr_node_docker_volumes: "{{ tdarr_node_docker_volumes_default
                               + tdarr_node_docker_volumes_custom }}"

# Devices
tdarr_node_docker_devices_default: []
tdarr_node_docker_devices_custom: []
tdarr_node_docker_devices: "{{ tdarr_node_docker_devices_default
                               + tdarr_node_docker_devices_custom }}"

# Hosts
tdarr_node_docker_hosts_default: {}
tdarr_node_docker_hosts_custom: {}
tdarr_node_docker_hosts: "{{ docker_hosts_common
                             | combine(tdarr_node_docker_hosts_default)
                             | combine(tdarr_node_docker_hosts_custom) }}"

# Labels
tdarr_node_docker_labels_default: {}
tdarr_node_docker_labels_custom: {}
tdarr_node_docker_labels: "{{ docker_labels_common
                              | combine(tdarr_node_docker_labels_default)
                              | combine(tdarr_node_docker_labels_custom) }}"

# Hostname
tdarr_node_docker_hostname: "{{ tdarr_node_name }}"

# Networks
tdarr_node_docker_networks_alias: "{{ tdarr_node_name }}"
tdarr_node_docker_networks_default: []
tdarr_node_docker_networks_custom: []
tdarr_node_docker_networks: "{{ docker_networks_common
                                + tdarr_node_docker_networks_default
                                + tdarr_node_docker_networks_custom }}"

# Capabilities
tdarr_node_docker_capabilities_default: []
tdarr_node_docker_capabilities_custom: []
tdarr_node_docker_capabilities: "{{ tdarr_node_docker_capabilities_default
                                    + tdarr_node_docker_capabilities_custom }}"

# Security Opts
tdarr_node_docker_security_opts_default: []
tdarr_node_docker_security_opts_custom: []
tdarr_node_docker_security_opts: "{{ tdarr_node_docker_security_opts_default
                                     + tdarr_node_docker_security_opts_custom }}"

# Restart Policy
tdarr_node_docker_restart_policy: unless-stopped

# State
tdarr_node_docker_state: started
