#########################################################################
# Title:            Sandbox: plexshare                                  #
# Author(s):        JigSawFr                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
# Repository: https://github.com/Chewbaka69/PlexShare/blob/master/docker-compose.yml
---
- name: Check if db folder exists
  ansible.builtin.stat:
    path: "{{ server_appdata_path }}/{{ plexshare_paths_folder }}/mariadb"
  register: stat_plexshare_db_folder

- name: Remove legacy MariaDB Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ plexshare_name }}_mariadb"

- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb
  vars:
    mariadb_instances: ["{{ plexshare_name }}-mariadb"]
    mariadb_docker_image_tag: "latest"
    mariadb_paths_folder: "{{ plexshare_name }}"
    mariadb_paths_location: "{{ server_appdata_path }}/{{ plexshare_paths_folder }}/mariadb"

- name: MariaDB | Create plexshare database
  community.mysql.mysql_db:
    name: "plexshare"
    login_host: "{{ plexshare_name }}-mariadb"
    login_user: "root"
    login_password: "{{ mariadb_docker_env_password }}"
    state: present
  when: not stat_plexshare_db_folder.stat.exists

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Print Tweaking Info
  ansible.builtin.debug:
    msg: "For custom docker envs, please visit: https://github.com/Chewbaka69/PlexShare"
