##########################################################################
# Title:         Sandbox: Krusader | Default Variables                   #
# Author(s):     ChuckNorris9939                                         #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Docker Socket Proxy
################################

krusader_role_docker_socket_proxy_envs:
  CONTAINERS: "1"
  POST: "0"

################################
# Basics
################################

krusader_name: krusader

################################
# Paths
################################

krusader_role_paths_folder: "{{ krusader_name }}"
krusader_role_paths_location: "{{ server_appdata_path }}/{{ krusader_role_paths_folder }}"
krusader_role_paths_folders_list:
  - "{{ krusader_role_paths_location }}"
  - "{{ krusader_role_paths_location }}/config"

################################
# Web
################################

krusader_role_web_subdomain: "{{ krusader_name }}"
krusader_role_web_domain: "{{ user.domain }}"
krusader_role_web_port: "6080"
krusader_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='krusader') + '.' + lookup('role_var', '_web_domain', role='krusader')
                        if (lookup('role_var', '_web_subdomain', role='krusader') | length > 0)
                        else lookup('role_var', '_web_domain', role='krusader')) }}"

################################
# DNS
################################

krusader_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='krusader') }}"
krusader_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='krusader') }}"
krusader_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

krusader_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
krusader_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
krusader_role_traefik_middleware_api: "{{ traefik_global_middleware }}"
krusader_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
krusader_role_traefik_enabled: true
krusader_role_traefik_api_enabled: false
krusader_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
krusader_role_docker_container: "{{ krusader_name }}"

# Image
krusader_role_docker_image_pull: true
krusader_role_docker_image_tag: "latest"
krusader_role_docker_image_repo: "binhex/arch-krusader"
krusader_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='krusader') }}:{{ lookup('role_var', '_docker_image_tag', role='krusader') }}"

# Envs
krusader_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  VNC_PASSWORD: "{{ user.pass }}"
  DOCKER_HOST: "tcp://{{ krusader_name }}-docker-socket-proxy:2375"
  WEBPAGE_TITLE: "Krusader File Manager Web"
  TEMP_FOLDER: "/tmp"
krusader_role_docker_envs_custom: {}
krusader_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='krusader')
                               | combine(lookup('role_var', '_docker_envs_custom', role='krusader')) }}"

# Volumes
krusader_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='krusader') }}/config:/config"
krusader_role_docker_volumes_custom: []
krusader_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='krusader')
                                  + lookup('role_var', '_docker_volumes_custom', role='krusader') }}"

# Hostname
krusader_role_docker_hostname: "{{ krusader_name }}"

# Networks
krusader_role_docker_networks_alias: "{{ krusader_name }}"
krusader_role_docker_networks_default: []
krusader_role_docker_networks_custom: []
krusader_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='krusader')
                                   + lookup('role_var', '_docker_networks_custom', role='krusader') }}"

# Restart Policy
krusader_role_docker_restart_policy: unless-stopped

# State
krusader_role_docker_state: started

# Dependencies
krusader_role_depends_on: "{{ krusader_name }}-docker-socket-proxy"
krusader_role_depends_on_delay: "0"
krusader_role_depends_on_healthchecks: "false"
