#########################################################################
# Title:         Sandbox: Shelfmark                                     #
# Author(s):     keldian                                                #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute shelfmark roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    shelfmark_name: "{{ instance }}"
  with_items: "{{ shelfmark_instances }}"
  loop_control:
    loop_var: instance
