#########################################################################
# Title:            Saltbox: minecraft                                  #
# Author(s):        jolbol1, salty                                      #
# URL:              https://github.com/saltyorg/Saltbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

minecraft_instances: ["minecraft"]
minecraft_dynmap_router_enabled: false

################################
# Paths
################################

minecraft_role_paths_folder: "minecraft"
minecraft_role_paths_location: "{{ server_appdata_path }}/{{ minecraft_role_paths_folder }}"
minecraft_role_paths_folders_list:
  - "{{ minecraft_role_paths_location }}/"
  - "{{ minecraft_role_paths_location }}/{{ minecraft_name }}"
  - "{{ minecraft_role_paths_location }}/{{ minecraft_name }}/data"
minecraft_role_paths_recursive: true

################################
# Web
################################

minecraft_role_web_subdomain: "{{ minecraft_name }}"
minecraft_role_web_domain: "{{ user.domain }}"
# Dynmap
minecraft_role_web_port: "8123"

################################
# DNS
################################

minecraft_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='minecraft') }}"
minecraft_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='minecraft') }}"
minecraft_role_dns_proxy: false

################################
# Traefik
################################

minecraft_role_traefik_sso_middleware: ""
minecraft_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
minecraft_role_traefik_middleware_custom: ""
minecraft_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
minecraft_role_traefik_enabled: "{{ lookup('role_var', '_dynmap_router_enabled', role='minecraft') }}"

################################
# Ports
################################
minecraft_role_docker_ports_25565: "{{ port_lookup_minecraft_tcp.meta.port
                                    if (port_lookup_minecraft_tcp.meta.port is defined) and (port_lookup_minecraft_tcp.meta.port | trim | length > 0)
                                    else '25565' }}"

################################
# Docker
################################

# Container
minecraft_role_docker_container: "{{ minecraft_name }}"

# Image
minecraft_role_docker_image_pull: true
minecraft_role_docker_image_repo: "itzg/minecraft-server"
minecraft_role_docker_image_tag: "latest"
minecraft_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='minecraft') }}:{{ lookup('role_var', '_docker_image_tag', role='minecraft') }}"

# Ports
minecraft_role_docker_ports_defaults:
  - "{{ minecraft_role_docker_ports_25565 }}:25565/tcp"
minecraft_role_docker_ports_custom: []
minecraft_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults', role='minecraft')
                                 + lookup('role_var', '_docker_ports_custom', role='minecraft') }}"

# Envs
minecraft_role_docker_envs_default:
  TZ: "{{ tz }}"
  EULA: "TRUE"
  UID: "{{ uid }}"
  GID: "{{ gid }}"
minecraft_role_docker_envs_custom: {}
minecraft_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='minecraft')
                                | combine(lookup('role_var', '_docker_envs_custom', role='minecraft')) }}"

# Volumes
minecraft_role_docker_volumes_default:
  - "{{ minecraft_role_paths_location }}/{{ minecraft_name }}/data:/data"
minecraft_role_docker_volumes_custom: []
minecraft_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='minecraft')
                                   + lookup('role_var', '_docker_volumes_custom', role='minecraft') }}"

# Hostname
minecraft_role_docker_hostname: "{{ minecraft_name }}"

# Networks
minecraft_role_docker_networks_alias: "{{ minecraft_name }}"
minecraft_role_docker_networks_default: []
minecraft_role_docker_networks_custom: []
minecraft_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='minecraft')
                                    + lookup('role_var', '_docker_networks_custom', role='minecraft') }}"

# Restart Policy
minecraft_role_docker_restart_policy: unless-stopped

# Stop Timeout
minecraft_role_docker_stop_timeout: 900

# State
minecraft_role_docker_state: started
