#########################################################################
# Title:            Sandbox: BookStack                                  #
# Author(s):        Thomvh, kowalski                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

bookstack_name: bookstack

################################
# Paths
################################

bookstack_role_paths_folder: "{{ bookstack_name }}"
bookstack_role_paths_location: "{{ server_appdata_path }}/{{ bookstack_role_paths_folder }}"
bookstack_role_paths_folders_list:
  - "{{ bookstack_role_paths_location }}"

################################
# Web
################################

bookstack_role_web_subdomain: "{{ bookstack_name }}"
bookstack_role_web_domain: "{{ user.domain }}"
bookstack_role_web_port: "80"
bookstack_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='bookstack') + '.' + lookup('role_var', '_web_domain', role='bookstack')
                    if (lookup('role_var', '_web_subdomain', role='bookstack') | length > 0)
                    else lookup('role_var', '_web_domain', role='bookstack')) }}"

################################
# DNS
################################

bookstack_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='bookstack') }}"
bookstack_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='bookstack') }}"
bookstack_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

bookstack_role_traefik_sso_middleware: ""
bookstack_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
bookstack_role_traefik_middleware_custom: ""
bookstack_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
bookstack_role_traefik_enabled: true

################################
# Docker
################################

# Container
bookstack_role_docker_container: "{{ bookstack_name }}"

# Image
bookstack_role_docker_image_pull: true
bookstack_role_docker_image_repo: "lscr.io/linuxserver/bookstack"
bookstack_role_docker_image_tag: "latest"
bookstack_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='bookstack') }}:{{ lookup('role_var', '_docker_image_tag', role='bookstack') }}"

# Envs
bookstack_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  APP_KEY: "{{ bookstack_saltbox_facts.facts.app_key }}"
  APP_URL: "{{ lookup('role_var', '_web_url', role='bookstack') }}"
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_PASSWORD: "{{ lookup('role_var', '_docker_env_password', role='mariadb') }}"
  DB_DATABASE: bookstackapp
bookstack_role_docker_envs_custom: {}
bookstack_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='bookstack')
                                | combine(lookup('role_var', '_docker_envs_custom', role='bookstack')) }}"

# Volumes
bookstack_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='bookstack') }}:/config"
bookstack_role_docker_volumes_custom: []
bookstack_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='bookstack')
                                   + lookup('role_var', '_docker_volumes_custom', role='bookstack') }}"

# Hostname
bookstack_role_docker_hostname: "{{ bookstack_name }}"

# Networks
bookstack_role_docker_networks_alias: "{{ bookstack_name }}"
bookstack_role_docker_networks_default: []
bookstack_role_docker_networks_custom: []
bookstack_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='bookstack')
                                    + lookup('role_var', '_docker_networks_custom', role='bookstack') }}"

# Restart Policy
bookstack_role_docker_restart_policy: unless-stopped

# State
bookstack_role_docker_state: started

# Dependencies
bookstack_role_depends_on: "mariadb"
bookstack_role_depends_on_delay: "0"
bookstack_role_depends_on_healthchecks: "false"
