##########################################################################
# Title:         Sandbox: Ombi | Default Variables                       #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

ombi_instances: ["ombi"]

################################
# Paths
################################

ombi_role_paths_folder: "{{ ombi_name }}"
ombi_role_paths_location: "{{ server_appdata_path }}/{{ ombi_role_paths_folder }}"
ombi_role_paths_folders_list:
  - "{{ ombi_role_paths_location }}"

################################
# Web
################################

ombi_role_web_subdomain: "{{ ombi_name }}"
ombi_role_web_domain: "{{ user.domain }}"
ombi_role_web_port: "3579"
ombi_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='ombi') + '.' + lookup('role_var', '_web_domain', role='ombi')
                    if (lookup('role_var', '_web_subdomain', role='ombi') | length > 0)
                    else lookup('role_var', '_web_domain', role='ombi')) }}"

################################
# DNS
################################

ombi_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='ombi') }}"
ombi_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='ombi') }}"
ombi_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

ombi_role_traefik_sso_middleware: ""
ombi_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
ombi_role_traefik_middleware_custom: ""
ombi_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
ombi_role_traefik_enabled: true
ombi_role_traefik_api_enabled: false
ombi_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
ombi_role_docker_container: "{{ ombi_name }}"

# Image
ombi_role_docker_image_pull: true
ombi_role_docker_image_repo: "lscr.io/linuxserver/ombi"
ombi_role_docker_image_tag: "latest"
ombi_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='ombi') }}:{{ lookup('role_var', '_docker_image_tag', role='ombi') }}"
# Envs
ombi_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
ombi_role_docker_envs_custom: {}
ombi_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='ombi')
                           | combine(lookup('role_var', '_docker_envs_custom', role='ombi')) }}"

# Volumes
ombi_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='ombi') }}:/config"
ombi_role_docker_volumes_custom: []
ombi_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='ombi')
                              + lookup('role_var', '_docker_volumes_custom', role='ombi') }}"

# Hostname
ombi_role_docker_hostname: "{{ ombi_name }}"

# Networks
ombi_role_docker_networks_alias: "{{ ombi_name }}"
ombi_role_docker_networks_default: []
ombi_role_docker_networks_custom: []
ombi_role_docker_networks: "{{ docker_networks_common
                               + lookup('role_var', '_docker_networks_default', role='ombi')
                               + lookup('role_var', '_docker_networks_custom', role='ombi') }}"

# Restart Policy
ombi_role_docker_restart_policy: unless-stopped

# State
ombi_role_docker_state: started
