##########################################################################
# Title:            Sandbox: EmbyStat                                    #
# Author(s):        Satz, kowalski                                       #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

embystat_name: embystat

################################
# Paths
################################

embystat_paths_folder: "{{ embystat_name }}"
embystat_paths_location: "{{ server_appdata_path }}/{{ embystat_paths_folder }}"
embystat_paths_folders_list:
  - "{{ embystat_paths_location }}"
  - "{{ embystat_paths_location }}/config"

################################
# Web
################################

embystat_web_subdomain: "{{ embystat_name }}"
embystat_web_domain: "{{ user.domain }}"
embystat_web_port: "6555"
embystat_web_url: "{{ 'https://' + (embystat_web_subdomain + '.' + embystat_web_domain
                   if (embystat_web_subdomain | length > 0)
                   else embystat_web_domain) }}"

################################
# DNS
################################

embystat_dns_record: "{{ embystat_web_subdomain }}"
embystat_dns_zone: "{{ embystat_web_domain }}"
embystat_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

embystat_traefik_sso_middleware: ""
embystat_traefik_middleware_default: "{{ traefik_default_middleware }}"
embystat_traefik_middleware_custom: ""
embystat_traefik_certresolver: "{{ traefik_default_certresolver }}"
embystat_traefik_enabled: true
embystat_traefik_api_enabled: false
embystat_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
embystat_docker_container: "{{ embystat_name }}"

# Image
embystat_docker_image_pull: true
embystat_docker_image_tag: "beta-linux-x64"
embystat_docker_image: "uping/embystat:{{ embystat_docker_image_tag }}"

# Ports
embystat_docker_ports_defaults: []
embystat_docker_ports_custom: []
embystat_docker_ports: "{{ embystat_docker_ports_defaults
                           + embystat_docker_ports_custom }}"

# Envs
embystat_docker_envs_default: {}
embystat_docker_envs_custom: {}
embystat_docker_envs: "{{ embystat_docker_envs_default
                          | combine(embystat_docker_envs_custom) }}"

# Commands
embystat_docker_commands_default: []
embystat_docker_commands_custom: []
embystat_docker_commands: "{{ embystat_docker_commands_default
                              + embystat_docker_commands_custom }}"

# Volumes
embystat_docker_volumes_default:
  - "{{ embystat_paths_location }}/config:/app/data"
embystat_docker_volumes_custom: []
embystat_docker_volumes: "{{ embystat_docker_volumes_default
                             + embystat_docker_volumes_custom }}"

# Devices
embystat_docker_devices_default: []
embystat_docker_devices_custom: []
embystat_docker_devices: "{{ embystat_docker_devices_default
                             + embystat_docker_devices_custom }}"

# Hosts
embystat_docker_hosts_default: {}
embystat_docker_hosts_custom: {}
embystat_docker_hosts: "{{ docker_hosts_common
                           | combine(embystat_docker_hosts_default)
                           | combine(embystat_docker_hosts_custom) }}"

# Labels
embystat_docker_labels_default: {}
embystat_docker_labels_custom: {}
embystat_docker_labels: "{{ docker_labels_common
                            | combine(embystat_docker_labels_default)
                            | combine(embystat_docker_labels_custom) }}"

# Hostname
embystat_docker_hostname: "{{ embystat_name }}"

# Networks
embystat_docker_networks_alias: "{{ embystat_name }}"
embystat_docker_networks_default: []
embystat_docker_networks_custom: []
embystat_docker_networks: "{{ docker_networks_common
                              + embystat_docker_networks_default
                              + embystat_docker_networks_custom }}"

# Capabilities
embystat_docker_capabilities_default: []
embystat_docker_capabilities_custom: []
embystat_docker_capabilities: "{{ embystat_docker_capabilities_default
                                  + embystat_docker_capabilities_custom }}"

# Security Opts
embystat_docker_security_opts_default: []
embystat_docker_security_opts_custom: []
embystat_docker_security_opts: "{{ embystat_docker_security_opts_default
                                   + embystat_docker_security_opts_custom }}"

# Restart Policy
embystat_docker_restart_policy: unless-stopped

# State
embystat_docker_state: started
