##########################################################################
# Title:            Sandbox: EmbyStat                                    #
# Author(s):        Satz, kowalski                                       #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

embystat_name: embystat

################################
# Paths
################################

embystat_role_paths_folder: "{{ embystat_name }}"
embystat_role_paths_location: "{{ server_appdata_path }}/{{ embystat_role_paths_folder }}"
embystat_role_paths_folders_list:
  - "{{ embystat_role_paths_location }}"
  - "{{ embystat_role_paths_location }}/config"

################################
# Web
################################

embystat_role_web_subdomain: "{{ embystat_name }}"
embystat_role_web_domain: "{{ user.domain }}"
embystat_role_web_port: "6555"
embystat_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='embystat') + '.' + lookup('role_var', '_web_domain', role='embystat')
                        if (lookup('role_var', '_web_subdomain', role='embystat') | length > 0)
                        else lookup('role_var', '_web_domain', role='embystat')) }}"

################################
# DNS
################################

embystat_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='embystat') }}"
embystat_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='embystat') }}"
embystat_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

embystat_role_traefik_sso_middleware: ""
embystat_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
embystat_role_traefik_middleware_custom: ""
embystat_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
embystat_role_traefik_enabled: true
embystat_role_traefik_api_enabled: false
embystat_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
embystat_role_docker_container: "{{ embystat_name }}"

# Image
embystat_role_docker_image_pull: true
embystat_role_docker_image_repo: "uping/embystat"
embystat_role_docker_image_tag: "beta-linux-x64"
embystat_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='embystat') }}:{{ lookup('role_var', '_docker_image_tag', role='embystat') }}"

# Volumes
embystat_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='embystat') }}/config:/app/data"
embystat_role_docker_volumes_custom: []
embystat_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='embystat')
                                  + lookup('role_var', '_docker_volumes_custom', role='embystat') }}"

# Hostname
embystat_role_docker_hostname: "{{ embystat_name }}"

# Networks
embystat_role_docker_networks_alias: "{{ embystat_name }}"
embystat_role_docker_networks_default: []
embystat_role_docker_networks_custom: []
embystat_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='embystat')
                                   + lookup('role_var', '_docker_networks_custom', role='embystat') }}"

# Restart Policy
embystat_role_docker_restart_policy: unless-stopped

# State
embystat_role_docker_state: started
