##########################################################################
# Title:         Sandbox: alternatrr | Default Variables                 #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

alternatrr_name: alternatrr

################################
# Paths
################################

alternatrr_paths_folder: "{{ alternatrr_name }}"
alternatrr_paths_location: "{{ server_appdata_path }}/{{ alternatrr_paths_folder }}"
alternatrr_paths_folders_list:
  - "{{ alternatrr_paths_location }}"
  - "{{ alternatrr_paths_location }}/app"

################################
# Web
################################

alternatrr_web_subdomain: "{{ alternatrr_name }}"
alternatrr_web_domain: "{{ user.domain }}"
alternatrr_web_port: "80"
alternatrr_web_url: "{{ 'https://' + alternatrr_web_subdomain + '.' + alternatrr_web_domain }}"

################################
# DNS
################################

alternatrr_dns_record: "{{ alternatrr_web_subdomain }}"
alternatrr_dns_zone: "{{ alternatrr_web_domain }}"
alternatrr_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

alternatrr_traefik_middleware: "{{ traefik_default_middleware }}"
alternatrr_traefik_certresolver: "{{ traefik_default_certresolver }}"
alternatrr_traefik_enabled: true

################################
# Docker
################################

# Container
alternatrr_docker_container: "{{ alternatrr_name }}"

# Image
alternatrr_docker_image_pull: true
alternatrr_docker_image_tag: "latest"
alternatrr_docker_image: "theultimatecoder/alternatrr:{{ alternatrr_docker_image_tag }}"

# Ports
alternatrr_docker_ports_defaults: []
alternatrr_docker_ports_custom: []
alternatrr_docker_ports: "{{ alternatrr_docker_ports_defaults
                             + alternatrr_docker_ports_custom }}"

# Envs
alternatrr_docker_envs_default:
  ConnectionStrings__DefaultConnection: Data Source=/opt/alternatrr/app/alternatrr.db
  ConnectionStrings__sonarr: Data Source=/opt/sonarr/sonarr.db
  Login__Username: "{{ user.name }}"
  Login__Password: "{{ user.pass }}"
alternatrr_docker_envs_custom: {}
alternatrr_docker_envs: "{{ alternatrr_docker_envs_default
                            | combine(alternatrr_docker_envs_custom) }}"

# Commands
alternatrr_docker_commands_default: []
alternatrr_docker_commands_custom: []
alternatrr_docker_commands: "{{ alternatrr_docker_commands_default
                                + alternatrr_docker_commands_custom }}"

# Volumes
alternatrr_docker_volumes_default:
  - "{{ alternatrr_paths_location }}/app:/opt/alternatrr/app"
  - "{{ sonarr_paths_location }}:/opt/sonarr"
alternatrr_docker_volumes_custom: []
alternatrr_docker_volumes: "{{ alternatrr_docker_volumes_default
                               + alternatrr_docker_volumes_custom }}"

# Devices
alternatrr_docker_devices_default: []
alternatrr_docker_devices_custom: []
alternatrr_docker_devices: "{{ alternatrr_docker_devices_default
                               + alternatrr_docker_devices_custom }}"

# Hosts
alternatrr_docker_hosts_default: []
alternatrr_docker_hosts_custom: []
alternatrr_docker_hosts: "{{ docker_hosts_common
                             | combine(alternatrr_docker_hosts_default)
                             | combine(alternatrr_docker_hosts_custom) }}"

# Labels
alternatrr_docker_labels_default: {}
alternatrr_docker_labels_custom: {}
alternatrr_docker_labels: "{{ docker_labels_common
                              | combine(alternatrr_docker_labels_default)
                              | combine(alternatrr_docker_labels_custom) }}"

# Hostname
alternatrr_docker_hostname: "{{ alternatrr_name }}"

# Networks
alternatrr_docker_networks_alias: "{{ alternatrr_name }}"
alternatrr_docker_networks_default: []
alternatrr_docker_networks_custom: []
alternatrr_docker_networks: "{{ docker_networks_common
                                + alternatrr_docker_networks_default
                                + alternatrr_docker_networks_custom }}"

# Capabilities
alternatrr_docker_capabilities_default: []
alternatrr_docker_capabilities_custom: []
alternatrr_docker_capabilities: "{{ alternatrr_docker_capabilities_default
                                    + alternatrr_docker_capabilities_custom }}"

# Security Opts
alternatrr_docker_security_opts_default: []
alternatrr_docker_security_opts_custom: []
alternatrr_docker_security_opts: "{{ alternatrr_docker_security_opts_default
                                     + alternatrr_docker_security_opts_custom }}"

# Restart Policy
alternatrr_docker_restart_policy: unless-stopped

# State
alternatrr_docker_state: started
