#########################################################################
# Title:         Sandbox: Extended Personal Media Scanner (EPMS)        #
#                           Plugin for Plex                             #
# Author(s):     maximuskowalski                                        #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Gather list of running Docker containers
  shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' | xargs echo -n"
  register: docker_running_containers
  ignore_errors: true

- name: Convert to list
  set_fact:
    docker_running_containers: "{{ (docker_running_containers.stdout).split() }}"

- name: Stop Plex container
  docker_container:
    name: plex
    state: stopped
    container_default_behavior: compatibility
    tls_hostname: localhost

  when: ('plex' in docker_running_containers)

- name: Create Extended Personal Media Scanner directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: true
  with_items:
    - '/opt/plex/Library/Application Support/Plex Media Server/Scanners'
    - '/opt/plex/Library/Application Support/Plex Media Server/Scanners/Series'

- name: Get latest Extended Personal Media Scanner.py
  get_url:
    url: https://bitbucket.org/mjarends/plex-scanners/raw/e6b21a46375cb456af44aea437316faa644c5bb4/Series/Extended%20Personal%20Media%20Scanner.py
    dest: '/opt/plex/Library/Application Support/Plex Media Server/Scanners/Series/Extended Personal Media Scanner.py'
    mode: '0775'

- name: Set Extended Personal Media Scanner directory permissions
  file:
    path: '/opt/plex/Library/Application Support/Plex Media Server/Scanners'
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: true

- name: Clone Extended Personal Media Scanner Bundle
  git:
    repo: https://bitbucket.org/mjarends/extendedpersonalmedia-agent.bundle.git
    dest: '/opt/plex/Library/Application Support/Plex Media Server/Plug-ins/ExtendedPersonalMedia-Agent.bundle'
    clone: true
    version: HEAD
    force: true
  become: true
  become_user: "{{ user.name }}"

- name: Set Extended Personal Media Scanner directory permissions
  file:
    path: '/opt/plex/Library/Application Support/Plex Media Server/Plug-ins/ExtendedPersonalMedia-Agent.bundle'
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: true

- name: Start Plex container
  docker_container:
    name: plex
    state: started

  when: ('plex' in docker_running_containers)
