#########################################################################
# Title:            Sandbox: Archive Box                                #
# Author(s):        4everfun, kowalski                                  #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

archivebox_name: archivebox

################################
# Paths
################################

archivebox_role_paths_folder: "{{ archivebox_name }}"
archivebox_role_paths_location: "{{ server_appdata_path }}/{{ archivebox_role_paths_folder }}"
archivebox_role_paths_folders_list:
  - "{{ archivebox_role_paths_location }}"

################################
# Web
################################

archivebox_role_web_subdomain: "{{ archivebox_name }}"
archivebox_role_web_domain: "{{ user.domain }}"
archivebox_role_web_port: "8000"
archivebox_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='archivebox') + '.' + lookup('role_var', '_web_domain', role='archivebox')
                          if (lookup('role_var', '_web_subdomain', role='archivebox') | length > 0)
                          else lookup('role_var', '_web_domain', role='archivebox')) }}"

################################
# DNS
################################

archivebox_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='archivebox') }}"
archivebox_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='archivebox') }}"
archivebox_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

archivebox_role_traefik_sso_middleware: ""
archivebox_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
archivebox_role_traefik_middleware_custom: ""
archivebox_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
archivebox_role_traefik_enabled: true

################################
# Docker
################################

# Container
archivebox_role_docker_container: "{{ archivebox_name }}"

# Image
archivebox_role_docker_image_pull: true
archivebox_role_docker_image_repo: "archivebox/archivebox"
archivebox_role_docker_image_tag: "latest"
archivebox_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='archivebox') }}:{{ lookup('role_var', '_docker_image_tag', role='archivebox') }}"

# Envs
archivebox_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
archivebox_role_docker_envs_custom: {}
archivebox_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='archivebox')
                                 | combine(lookup('role_var', '_docker_envs_custom', role='archivebox')) }}"

# Volumes
archivebox_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='archivebox') }}:/data"
archivebox_role_docker_volumes_custom: []
archivebox_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='archivebox')
                                    + lookup('role_var', '_docker_volumes_custom', role='archivebox') }}"

# Hostname
archivebox_role_docker_hostname: "{{ archivebox_name }}"

# Networks
archivebox_role_docker_networks_alias: "{{ archivebox_name }}"
archivebox_role_docker_networks_default: []
archivebox_role_docker_networks_custom: []
archivebox_role_docker_networks: "{{ docker_networks_common
                                     + lookup('role_var', '_docker_networks_default', role='archivebox')
                                     + lookup('role_var', '_docker_networks_custom', role='archivebox') }}"

# Restart Policy
archivebox_role_docker_restart_policy: unless-stopped

# State
archivebox_role_docker_state: started
