##########################################################################
# Title:         Sandbox: FileBot | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

filebot_name: filebot

################################
# Paths
################################

filebot_role_paths_folder: "{{ filebot_name }}"
filebot_role_paths_location: "{{ server_appdata_path }}/{{ filebot_role_paths_folder }}"
filebot_role_paths_folders_list:
  - "{{ filebot_role_paths_location }}"
filebot_role_paths_config_location: "{{ filebot_role_paths_location }}/config.yml"

################################
# Web
################################

filebot_role_web_subdomain: "{{ filebot_name }}"
filebot_role_web_domain: "{{ user.domain }}"
filebot_role_web_port: "5800"
filebot_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='filebot') + '.' + lookup('role_var', '_web_domain', role='filebot')
                       if (lookup('role_var', '_web_subdomain', role='filebot') | length > 0)
                       else lookup('role_var', '_web_domain', role='filebot')) }}"

################################
# DNS
################################

filebot_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='filebot') }}"
filebot_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='filebot') }}"
filebot_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

filebot_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
filebot_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
filebot_role_traefik_middleware_custom: ""
filebot_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
filebot_role_traefik_enabled: true
filebot_role_traefik_api_enabled: true
filebot_role_traefik_api_endpoint: "PathPrefix(`/websockify`)"

################################
# Docker
################################

# Container
filebot_role_docker_container: "{{ filebot_name }}"

# Image
filebot_role_docker_image_pull: true
filebot_role_docker_image_repo: "jlesage/filebot"
filebot_role_docker_image_tag: "latest"
filebot_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='filebot') }}:{{ lookup('role_var', '_docker_image_tag', role='filebot') }}"

# Envs
filebot_role_docker_envs_default:
  TZ: "{{ tz }}"
  USER_ID: "{{ uid }}"
  GROUP_ID: "{{ gid }}"
  UMASK: "022"
filebot_role_docker_envs_custom: {}
filebot_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='filebot')
                              | combine(lookup('role_var', '_docker_envs_custom', role='filebot')) }}"

# Volumes
filebot_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='filebot') }}:/config"
  - "/mnt/unionfs/Media/:/storage/Media/"
  - "/mnt/unionfs/downloads:/storage/downloads"
filebot_role_docker_volumes_custom: []
filebot_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='filebot')
                                 + lookup('role_var', '_docker_volumes_custom', role='filebot') }}"

# Hostname
filebot_role_docker_hostname: "{{ filebot_name }}"

# Networks
filebot_role_docker_networks_alias: "{{ filebot_name }}"
filebot_role_docker_networks_default: []
filebot_role_docker_networks_custom: []
filebot_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='filebot')
                                  + lookup('role_var', '_docker_networks_custom', role='filebot') }}"

# Restart Policy
filebot_role_docker_restart_policy: unless-stopped

# State
filebot_role_docker_state: started
