#########################################################################
# Title:            Sandbox: komga                                      #
# Author(s):        theotocopulitos, crowquill                          #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

komga_name: komga

################################
# Paths
################################

komga_role_paths_folder: "{{ komga_name }}"
komga_role_paths_location: "{{ server_appdata_path }}/{{ komga_role_paths_folder }}"
komga_role_paths_folders_list:
  - "{{ komga_role_paths_location }}"
  - "{{ server_local_folder_path }}/Media/Comics"

################################
# Web
################################

komga_role_web_subdomain: "{{ komga_name }}"
komga_role_web_domain: "{{ user.domain }}"
komga_role_web_port: "25600"
komga_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='komga') + '.' + lookup('role_var', '_web_domain', role='komga')
                     if (lookup('role_var', '_web_subdomain', role='komga') | length > 0)
                     else lookup('role_var', '_web_domain', role='komga')) }}"

################################
# DNS
################################

komga_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='komga') }}"
komga_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='komga') }}"
komga_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

komga_role_traefik_sso_middleware: ""
komga_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
komga_role_traefik_middleware_custom: ""
komga_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
komga_role_traefik_enabled: true
komga_role_traefik_api_enabled: false
komga_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
komga_role_docker_container: "{{ komga_name }}"

# Image
komga_role_docker_image_pull: true
komga_role_docker_image_tag: "latest"
komga_role_docker_image_repo: "gotson/komga"
komga_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='komga') }}:{{ lookup('role_var', '_docker_image_tag', role='komga') }}"

# Envs
komga_role_docker_envs_default:
  KOMGA_CORS_ALLOWEDORIGINS: "*"
komga_role_docker_envs_custom: {}
komga_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='komga')
                            | combine(lookup('role_var', '_docker_envs_custom', role='komga')) }}"

# Volumes
komga_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='komga') }}:/config"
  - "/mnt/unionfs/Media/Comics:/comics"
komga_role_docker_volumes_custom: []
komga_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='komga')
                               + lookup('role_var', '_docker_volumes_custom', role='komga') }}"

# Hostname
komga_role_docker_hostname: "{{ komga_name }}"

# Networks
komga_role_docker_networks_alias: "{{ komga_name }}"
komga_role_docker_networks_default: []
komga_role_docker_networks_custom: []
komga_role_docker_networks: "{{ docker_networks_common
                                + lookup('role_var', '_docker_networks_default', role='komga')
                                + lookup('role_var', '_docker_networks_custom', role='komga') }}"

# Restart Policy
komga_role_docker_restart_policy: unless-stopped

# State
komga_role_docker_state: started

# User
komga_role_docker_user: "{{ uid }}:{{ gid }}"
