##########################################################################
# Title:            Sandbox: JDownloader2 | Legacy                       #
# Author(s):        kowalski, desimaniac                                 #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Legacy | Check if '/opt/myjdownloader' exists
  stat:
    path: "/opt/myjdownloader"
  register: opt_myjdownloader

- name: Legacy | Migration Block
  block:

    - name: Legacy | Stop and remove myjdownloader container
      docker_container:
        name: myjdownloader
        state: absent

    - name: Legacy | Move opt folder 'myjdownloader' to 'jdownloader2'
      shell: |
        mv /opt/myjdownloader "{{ jdownloader2_paths_location }}"
        chown -R {{ user.name }}:{{ user.name }} "{{ jdownloader2_paths_location }}"

  when: (opt_myjdownloader.stat.exists)
