##########################################################################
# Title:            Sandbox: JDownloader2 | Legacy                       #
# Author(s):        kowalski, desimaniac                                 #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Legacy | Check if '/opt/myjdownloader' exists
  ansible.builtin.stat:
    path: "/opt/myjdownloader"
  register: opt_myjdownloader

- name: Legacy | Migration Block
  when: (opt_myjdownloader.stat.exists)
  block:
    - name: Legacy | Stop and remove myjdownloader container
      community.docker.docker_container:
        name: myjdownloader
        state: absent

    - name: Legacy | Move opt folder 'myjdownloader' to 'jdownloader2'
      ansible.builtin.shell: |
        mv /opt/myjdownloader "{{ jdownloader2_paths_location }}"

    - name: Legacy | Set permissions on 'jdownloader2'
      ansible.builtin.file:
        path: "{{ jdownloader2_paths_location }}"
        state: directory
        recurse: yes
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
