#########################################################################
# Title:            Sandbox: Suwayomi                                   #
# Author(s):        JohnClementine                                      #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Check if `{{ lookup('role_var', '_paths_config_location') | basename }}` exists
  ansible.builtin.stat:
    path: "{{ lookup('role_var', '_paths_config_location') }}"
  register: suwayomi_config

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Wait for config file to be generated
  ansible.builtin.wait_for:
    path: "{{ lookup('role_var', '_paths_config_location') }}"
    state: present
    timeout: 60
  when: (not suwayomi_config.stat.exists) and (not continuous_integration)

- name: Stop Docker container for config modification
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"
  when: (not suwayomi_config.stat.exists) and (not continuous_integration)

- name: Set downloads path in config
  ansible.builtin.lineinfile:
    path: "{{ lookup('role_var', '_paths_config_location') }}"
    regexp: '^server\.downloadsPath\s*='
    line: 'server.downloadsPath = "/comics"'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
  when: (not suwayomi_config.stat.exists) and (not continuous_integration)

- name: Start Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
  when: (not suwayomi_config.stat.exists) and (not continuous_integration)
