##########################################################################
# Title:            Sandbox: Dockwatch | Default Variables               #
# Author(s):        owine                                                #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Settings
################################

dockwatch_post_enable: false

################################
# Docker Socket Proxy
################################

dockwatch_role_docker_socket_proxy_envs:
  ALLOW_START: "1"
  ALLOW_STOP: "1"
  ALLOW_RESTARTS: "1"
  CONTAINERS: "1"
  IMAGES: "1"
  NETWORKS: "1"
  PORTS: "1"
  POST: "{{ '1' if dockwatch_post_enable else omit }}"
  VOLUMES: "1"

################################
# Basics
################################

dockwatch_name: dockwatch

################################
# Paths
################################

dockwatch_role_paths_folder: "{{ dockwatch_name }}"
dockwatch_role_paths_location: "{{ server_appdata_path }}/{{ dockwatch_role_paths_folder }}"
dockwatch_role_paths_folders_list:
  - "{{ dockwatch_role_paths_location }}"
  - "{{ dockwatch_role_paths_location }}/icons"

################################
# Web
################################

dockwatch_role_web_subdomain: "{{ dockwatch_name }}"
dockwatch_role_web_domain: "{{ user.domain }}"
dockwatch_role_web_port: "80"
dockwatch_role_web_url: "{{ 'https://' + (dockwatch_role_web_subdomain + '.' + dockwatch_role_web_domain
                    if (dockwatch_role_web_subdomain | length > 0)
                    else dockwatch_role_web_domain) }}"

################################
# DNS
################################

dockwatch_role_dns_record: "{{ dockwatch_role_web_subdomain }}"
dockwatch_role_dns_zone: "{{ dockwatch_role_web_domain }}"
dockwatch_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

dockwatch_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
dockwatch_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
dockwatch_role_traefik_middleware_custom: ""
dockwatch_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
dockwatch_role_traefik_enabled: true
dockwatch_role_traefik_api_enabled: true
dockwatch_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
dockwatch_role_docker_container: "{{ dockwatch_name }}"

# Image
dockwatch_role_docker_image_pull: true
dockwatch_role_docker_image_tag: "main"
dockwatch_role_docker_image: "ghcr.io/notifiarr/dockwatch:{{ dockwatch_role_docker_image_tag }}"

# Envs
dockwatch_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  DOCKER_HOST: "{{ dockwatch_name }}-docker-socket-proxy:2375"
dockwatch_role_docker_envs_custom: {}
dockwatch_role_docker_envs: "{{ dockwatch_role_docker_envs_default
                           | combine(dockwatch_role_docker_envs_custom) }}"

# Volumes
dockwatch_role_docker_volumes_default:
  - "{{ dockwatch_role_paths_location }}:/config"
dockwatch_role_docker_volumes_custom: []
dockwatch_role_docker_volumes: "{{ dockwatch_role_docker_volumes_default
                              + dockwatch_role_docker_volumes_custom }}"

# Hostname
dockwatch_role_docker_hostname: "{{ dockwatch_name }}"

# Networks
dockwatch_role_docker_networks_alias: "{{ dockwatch_name }}"
dockwatch_role_docker_networks_default: []
dockwatch_role_docker_networks_custom: []
dockwatch_role_docker_networks: "{{ docker_networks_common
                               + dockwatch_role_docker_networks_default
                               + dockwatch_role_docker_networks_custom }}"

# Restart Policy
dockwatch_role_docker_restart_policy: unless-stopped

# State
dockwatch_role_docker_state: started

# Dependencies
dockwatch_depends_on: "{{ dockwatch_name }}-docker-socket-proxy"
dockwatch_depends_on_delay: "0"
dockwatch_depends_on_healthchecks: "false"
