#########################################################################
# Title:            Sandbox: Immich                                     #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove legacy redis Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    container_name: "{{ immich_name }}_redis"

- name: Import Redis Role
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_instances: ["{{ immich_name }}-redis"]
    redis_role_docker_image_tag: "8-alpine"
    redis_role_paths_folder: "{{ immich_name }}"
    redis_role_paths_location: "{{ server_appdata_path }}/{{ lookup('role_var', '_paths_folder', role='redis') }}/redis"

- name: Remove legacy PostgreSQL Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    container_name: "{{ immich_name }}_postgres"

- name: "Import Postgres Role"
  ansible.builtin.include_role:
    name: postgres
  vars:
    postgres_instances: ["{{ lookup('role_var', '_postgres_name', role='immich') }}"]
    postgres_role_docker_image_tag: "{{ lookup('role_var', '_postgres_docker_image_tag', role='immich') }}"
    postgres_role_docker_image_repo: "{{ lookup('role_var', '_postgres_docker_image_repo', role='immich') }}"
    postgres_role_paths_folder: "{{ lookup('role_var', '_postgres_paths_folder', role='immich') }}"
    postgres_role_paths_location: "{{ lookup('role_var', '_postgres_paths_location', role='immich') }}"
    postgres_role_docker_env_db: "{{ lookup('role_var', '_postgres_docker_env_db', role='immich') }}"
    postgres_role_docker_env_user_include: "{{ lookup('role_var', '_postgres_user', role='immich') }}"
    postgres_role_docker_env_password_include: "{{ lookup('role_var', '_postgres_password', role='immich') }}"
    postgres_role_docker_healthcheck: "{{ lookup('role_var', '_postgres_docker_healthcheck', role='immich') }}"
    postgres_role_docker_shm_size: "{{ lookup('role_var', '_postgres_docker_shm_size', role='immich') }}"
    postgres_role_docker_envs_custom: "{{ lookup('role_var', '_postgres_docker_envs_custom', role='immich') }}"
  when: lookup('role_var', '_postgres_deploy', role='immich')

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Docker Devices Task
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/set_docker_devices_variable.yml"
  when: use_intel or use_nvidia

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
