##########################################################################
# Title:         Sandbox: Private Bin | Default Variables                #
# Author(s):     tipdec-siblyn, thatsnasty, salty                        #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

privatebin_name: privatebin

################################
# Paths
################################

privatebin_paths_folder: "{{ privatebin_name }}"
privatebin_paths_location: "{{ server_appdata_path }}/{{ privatebin_paths_folder }}"
privatebin_paths_folders_list:
  - "{{ privatebin_paths_location }}"

################################
# Web
################################

privatebin_web_subdomain: "{{ privatebin_name }}"
privatebin_web_domain: "{{ user.domain }}"
privatebin_web_port: "8080"
privatebin_web_url: "{{ 'https://' + (privatebin_web_subdomain + '.' + privatebin_web_domain
                     if (privatebin_web_subdomain | length > 0)
                     else privatebin_web_domain) }}"

################################
# DNS
################################

privatebin_dns_record: "{{ privatebin_web_subdomain }}"
privatebin_dns_zone: "{{ privatebin_web_domain }}"
privatebin_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

privatebin_traefik_sso_middleware: ""
privatebin_traefik_middleware_default: "{{ traefik_default_middleware }}"
privatebin_traefik_middleware_custom: ""
privatebin_traefik_certresolver: "{{ traefik_default_certresolver }}"
privatebin_traefik_enabled: true
privatebin_traefik_api_enabled: false
privatebin_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
privatebin_docker_container: "{{ privatebin_name }}"

# Image
privatebin_docker_image_pull: true
privatebin_docker_image_tag: "latest"
privatebin_docker_image: "privatebin/nginx-fpm-alpine:{{ privatebin_docker_image_tag }}"

# Ports
privatebin_docker_ports_defaults: []
privatebin_docker_ports_custom: []
privatebin_docker_ports: "{{ privatebin_docker_ports_defaults
                             + privatebin_docker_ports_custom }}"

# Envs
privatebin_docker_envs_default:
  TZ: "{{ tz }}"
  PHP_TZ: "{{ tz }}"
privatebin_docker_envs_custom: {}
privatebin_docker_envs: "{{ privatebin_docker_envs_default
                            | combine(privatebin_docker_envs_custom) }}"

# Commands
privatebin_docker_commands_default: []
privatebin_docker_commands_custom: []
privatebin_docker_commands: "{{ privatebin_docker_commands_default
                                + privatebin_docker_commands_custom }}"

# Volumes
privatebin_docker_volumes_default:
  - "{{ privatebin_paths_location }}:/srv/data"
  - "{{ privatebin_paths_location }}/conf.php:/srv/cfg/conf.php:ro"
  - "{{ lookup('vars', role_name + '_docker_container') }}_tmpfs_run:/run"
privatebin_docker_volumes_custom: []
privatebin_docker_volumes: "{{ privatebin_docker_volumes_default
                               + privatebin_docker_volumes_custom }}"

# Mounts
privatebin_docker_mounts_default:
  - target: /tmp
    type: tmpfs
  - target: /var/lib/nginx/tmp
    type: tmpfs
privatebin_docker_mounts_custom: []
privatebin_docker_mounts: "{{ privatebin_docker_mounts_default
                              + privatebin_docker_mounts_custom }}"

# Devices
privatebin_docker_devices_default: []
privatebin_docker_devices_custom: []
privatebin_docker_devices: "{{ privatebin_docker_devices_default
                               + privatebin_docker_devices_custom }}"

# Hosts
privatebin_docker_hosts_default: {}
privatebin_docker_hosts_custom: {}
privatebin_docker_hosts: "{{ docker_hosts_common
                             | combine(privatebin_docker_hosts_default)
                             | combine(privatebin_docker_hosts_custom) }}"

# Labels
privatebin_docker_labels_default: {}
privatebin_docker_labels_custom: {}
privatebin_docker_labels: "{{ docker_labels_common
                              | combine(privatebin_docker_labels_default)
                              | combine(privatebin_docker_labels_custom) }}"

# Hostname
privatebin_docker_hostname: "{{ privatebin_name }}"

# Networks
privatebin_docker_networks_alias: "{{ privatebin_name }}"
privatebin_docker_networks_default: []
privatebin_docker_networks_custom: []
privatebin_docker_networks: "{{ docker_networks_common
                                + privatebin_docker_networks_default
                                + privatebin_docker_networks_custom }}"

# Capabilities
privatebin_docker_capabilities_default: []
privatebin_docker_capabilities_custom: []
privatebin_docker_capabilities: "{{ privatebin_docker_capabilities_default
                                    + privatebin_docker_capabilities_custom }}"

# Security Opts
privatebin_docker_security_opts_default: []
privatebin_docker_security_opts_custom: []
privatebin_docker_security_opts: "{{ privatebin_docker_security_opts_default
                                     + privatebin_docker_security_opts_custom }}"

# Read Only
privatebin_docker_read_only: yes

# Restart Policy
privatebin_docker_restart_policy: unless-stopped

# State
privatebin_docker_state: started

# User
privatebin_docker_user: "{{ uid }}:{{ gid }}"
