##########################################################################
# Title:            Sandbox: unmanic   | Default Variables               #
# Author(s):        chazlarson, kowalski                                 #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

unmanic_name: unmanic

################################
# Paths
################################

unmanic_paths_folder: "{{ unmanic_name }}"
unmanic_paths_location: "{{ server_appdata_path }}/{{ unmanic_paths_folder }}"
unmanic_paths_transcodes_location: "{{ transcodes_path }}/{{ unmanic_paths_folder }}"
unmanic_paths_folders_list:
  - "{{ unmanic_paths_location }}"
  - "{{ unmanic_paths_transcodes_location }}"

################################
# Web
################################

unmanic_web_subdomain: "{{ unmanic_name }}"
unmanic_web_domain: "{{ user.domain }}"
unmanic_web_port: "8888"
unmanic_web_url: "{{ 'https://' + (unmanic_web_subdomain + '.' + unmanic_web_domain
                  if (unmanic_web_subdomain | length > 0)
                  else unmanic_web_domain) }}"

################################
# DNS
################################

unmanic_dns_record: "{{ unmanic_web_subdomain }}"
unmanic_dns_zone: "{{ unmanic_web_domain }}"
unmanic_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

unmanic_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
unmanic_traefik_middleware_default: "{{ traefik_default_middleware }}"
unmanic_traefik_middleware_custom: ""
unmanic_traefik_certresolver: "{{ traefik_default_certresolver }}"
unmanic_traefik_enabled: true
unmanic_traefik_api_enabled: false
unmanic_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
unmanic_docker_container: "{{ unmanic_name }}"

# Image
unmanic_docker_image_pull: true
unmanic_docker_image_tag: "latest"
unmanic_docker_image: "josh5/unmanic:{{ unmanic_docker_image_tag }}"

# Ports
unmanic_docker_ports_defaults: []
unmanic_docker_ports_custom: []
unmanic_docker_ports: "{{ unmanic_docker_ports_defaults
                          + unmanic_docker_ports_custom }}"

# Envs
unmanic_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
unmanic_docker_envs_custom: {}
unmanic_docker_envs: "{{ unmanic_docker_envs_default
                         | combine(unmanic_docker_envs_custom) }}"

# Commands
unmanic_docker_commands_default: []
unmanic_docker_commands_custom: []
unmanic_docker_commands: "{{ unmanic_docker_commands_default
                             + unmanic_docker_commands_custom }}"

# Volumes
unmanic_docker_volumes_default:
  - "{{ unmanic_paths_location }}:/config"
  - "{{ unmanic_paths_transcodes_location }}:/tmp/unmanic"
  - "/mnt/unionfs/Media:/library"
unmanic_docker_volumes_custom: []
unmanic_docker_volumes: "{{ unmanic_docker_volumes_default
                            + unmanic_docker_volumes_custom }}"

# Devices
unmanic_docker_devices_default: []
unmanic_docker_devices_custom: []
unmanic_docker_devices: "{{ unmanic_docker_devices_default
                            + unmanic_docker_devices_custom }}"

# Hosts
unmanic_docker_hosts_default: {}
unmanic_docker_hosts_custom: {}
unmanic_docker_hosts: "{{ docker_hosts_common
                          | combine(unmanic_docker_hosts_default)
                          | combine(unmanic_docker_hosts_custom) }}"

# Labels
unmanic_docker_labels_default: {}
unmanic_docker_labels_custom: {}
unmanic_docker_labels: "{{ docker_labels_common
                           | combine(unmanic_docker_labels_default)
                           | combine(unmanic_docker_labels_custom) }}"

# Hostname
unmanic_docker_hostname: "{{ unmanic_name }}"

# Networks
unmanic_docker_networks_alias: "{{ unmanic_name }}"
unmanic_docker_networks_default: []
unmanic_docker_networks_custom: []
unmanic_docker_networks: "{{ docker_networks_common
                             + unmanic_docker_networks_default
                             + unmanic_docker_networks_custom }}"

# Capabilities
unmanic_docker_capabilities_default: []
unmanic_docker_capabilities_custom: []
unmanic_docker_capabilities: "{{ unmanic_docker_capabilities_default
                                 + unmanic_docker_capabilities_custom }}"

# Security Opts
unmanic_docker_security_opts_default: []
unmanic_docker_security_opts_custom: []
unmanic_docker_security_opts: "{{ unmanic_docker_security_opts_default
                                  + unmanic_docker_security_opts_custom }}"

# Restart Policy
unmanic_docker_restart_policy: unless-stopped

# State
unmanic_docker_state: started
