#########################################################################
# Title:            Sandbox: cockpit | Default Variables                #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

cockpit_name: cockpit

################################
# Settings
################################

cockpit_vm_enabled: false
cockpit_service_after: docker.service
put_cockpit_dpkg_into_hold: true
put_cockpit_machines_dpkg_into_hold: true

################################
# Paths
################################

cockpit_role_paths_socket_location: "/etc/systemd/system/cockpit.socket.d/listen.conf"
cockpit_role_paths_socket_override_location: "/etc/systemd/system/cockpit.socket.d/override.conf"
cockpit_role_paths_config_location: "/etc/cockpit/cockpit.conf"
cockpit_role_paths_traefik_location: "/opt/traefik/cockpit.yml"
cockpit_role_paths_service_location: "/lib/systemd/system/cockpit.service"
cockpit_role_paths_override_location: "/etc/systemd/system/cockpit.service.d/override.conf"
cockpit_role_paths_folders_list:
  - "/etc/systemd/system/cockpit.socket.d"
  - "/etc/systemd/system/cockpit.service.d"
  - "/etc/cockpit"

################################
# Web
################################

cockpit_role_web_subdomain: "{{ cockpit_name }}"
cockpit_role_web_domain: "{{ user.domain }}"
cockpit_role_web_port: "1337"
cockpit_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='cockpit') + '.' + lookup('role_var', '_web_domain', role='cockpit')
                       if (lookup('role_var', '_web_subdomain', role='cockpit') | length > 0)
                       else lookup('role_var', '_web_domain', role='cockpit')) }}"

################################
# DNS
################################

cockpit_role_dns_record: "{{ cockpit_role_web_subdomain }}"
cockpit_role_dns_zone: "{{ cockpit_role_web_domain }}"
cockpit_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

cockpit_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
cockpit_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
cockpit_role_traefik_middleware_custom: ""
cockpit_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
cockpit_role_traefik_enabled: true
cockpit_role_traefik_api_enabled: false
