##########################################################################
# Title:            Sandbox: homarr_legacy | Default Variables           #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

homarr_legacy_name: homarr-legacy

################################
# Docker Socket Proxy
################################

homarr_legacy_role_docker_socket_proxy_envs:
  CONTAINERS: "1"
  POST: "0"

################################
# Paths
################################

homarr_legacy_role_paths_folder: "{{ homarr_legacy_name }}"
homarr_legacy_role_paths_location: "{{ server_appdata_path }}/{{ homarr_legacy_role_paths_folder }}"
homarr_legacy_role_paths_folders_list:
  - "{{ homarr_legacy_role_paths_location }}"
  - "{{ homarr_legacy_role_paths_location }}/icons"

################################
# Web
################################

homarr_legacy_role_web_subdomain: "{{ homarr_legacy_name }}"
homarr_legacy_role_web_domain: "{{ user.domain }}"
homarr_legacy_role_web_port: "7575"
homarr_legacy_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='homarr_legacy') + '.' + lookup('role_var', '_web_domain', role='homarr_legacy')
                             if (lookup('role_var', '_web_subdomain', role='homarr_legacy') | length > 0)
                             else lookup('role_var', '_web_domain', role='homarr_legacy')) }}"

################################
# DNS
################################

homarr_legacy_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='homarr_legacy') }}"
homarr_legacy_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='homarr_legacy') }}"
homarr_legacy_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

homarr_legacy_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
homarr_legacy_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
homarr_legacy_role_traefik_middleware_custom: ""
homarr_legacy_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
homarr_legacy_role_traefik_enabled: true
homarr_legacy_role_traefik_api_enabled: false
homarr_legacy_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
homarr_legacy_role_docker_container: "{{ homarr_legacy_name }}"

# Image
homarr_legacy_role_docker_image_pull: true
homarr_legacy_role_docker_image_repo: "ghcr.io/ajnart/homarr"
homarr_legacy_role_docker_image_tag: "latest"
homarr_legacy_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='homarr_legacy') }}:{{ lookup('role_var', '_docker_image_tag', role='homarr_legacy') }}"

# Envs
homarr_legacy_role_docker_envs_default:
  TZ: "{{ tz }}"
  BASE_URL: "{{ lookup('role_var', '_web_subdomain', role='homarr_legacy') + '.' + lookup('role_var', '_web_domain', role='homarr_legacy') }}"
  PASSWORD: "{{ user.pass }}"
  DOCKER_HOST: "tcp://{{ homarr_legacy_name }}-docker-socket-proxy:2375"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
homarr_legacy_role_docker_envs_custom: {}
homarr_legacy_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='homarr_legacy')
                                    | combine(lookup('role_var', '_docker_envs_custom', role='homarr_legacy')) }}"

# Volumes
homarr_legacy_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='homarr_legacy') }}:/app/data/configs"
  - "{{ lookup('role_var', '_paths_location', role='homarr_legacy') }}/icons:/app/public/icons"
homarr_legacy_role_docker_volumes_custom: []
homarr_legacy_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='homarr_legacy')
                                       + lookup('role_var', '_docker_volumes_custom', role='homarr_legacy') }}"

# Hostname
homarr_legacy_role_docker_hostname: "{{ homarr_legacy_name }}"

# Networks
homarr_legacy_role_docker_networks_alias: "{{ homarr_legacy_name }}"
homarr_legacy_role_docker_networks_default: []
homarr_legacy_role_docker_networks_custom: []
homarr_legacy_role_docker_networks: "{{ docker_networks_common
                                        + lookup('role_var', '_docker_networks_default', role='homarr_legacy')
                                        + lookup('role_var', '_docker_networks_custom', role='homarr_legacy') }}"

# Restart Policy
homarr_legacy_role_docker_restart_policy: unless-stopped

# State
homarr_legacy_role_docker_state: started

# Init
homarr_legacy_role_docker_init: true

# Dependencies
homarr_legacy_role_depends_on: "{{ homarr_legacy_name }}-docker-socket-proxy"
homarr_legacy_role_depends_on_delay: "0"
homarr_legacy_role_depends_on_healthchecks: "false"
