#########################################################################
# Title:         Sandbox: MeTube | Default Variables                    #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

metube_name: metube

################################
# Paths
################################

metube_role_paths_folder: "{{ metube_name }}"
metube_role_paths_location: "{{ server_appdata_path }}/{{ metube_role_paths_folder }}"
metube_role_paths_downloads_location: "{{ downloads_root_path }}/{{ metube_name }}"
metube_role_paths_folders_list:
  - "{{ metube_role_paths_location }}"
  - "{{ metube_role_paths_downloads_location }}"

################################
# Web
################################

metube_role_web_subdomain: "{{ metube_name }}"
metube_role_web_domain: "{{ user.domain }}"
metube_role_web_port: "8081"
metube_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='metube') + '.' + lookup('role_var', '_web_domain', role='metube')
                      if (lookup('role_var', '_web_subdomain', role='metube') | length > 0)
                      else lookup('role_var', '_web_domain', role='metube')) }}"

################################
# DNS
################################

metube_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='metube') }}"
metube_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='metube') }}"
metube_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

metube_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
metube_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
metube_role_traefik_middleware_custom: ""
metube_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
metube_role_traefik_enabled: true
metube_role_traefik_api_enabled: false
metube_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
metube_role_docker_container: "{{ metube_name }}"

# Image
metube_role_docker_image_pull: true
metube_role_docker_image_repo: "ghcr.io/alexta69/metube"
metube_role_docker_image_tag: "latest"
metube_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='metube') }}:{{ lookup('role_var', '_docker_image_tag', role='metube') }}"

# Envs
metube_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "022"
  TZ: "{{ tz }}"
metube_role_docker_envs_custom: {}
metube_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='metube')
                             | combine(lookup('role_var', '_docker_envs_custom', role='metube')) }}"

# Volumes
metube_role_docker_volumes_download: false
metube_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='metube') }}:/config"
  - "{{ lookup('role_var', '_paths_downloads_location', role='metube') }}:/downloads"
metube_role_docker_volumes_custom: []
metube_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='metube')
                                + lookup('role_var', '_docker_volumes_custom', role='metube') }}"

# Hostname
metube_role_docker_hostname: "{{ metube_name }}"

# Networks
metube_role_docker_networks_alias: "{{ metube_name }}"
metube_role_docker_networks_default: []
metube_role_docker_networks_custom: []
metube_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='metube')
                                 + lookup('role_var', '_docker_networks_custom', role='metube') }}"

# Restart Policy
metube_role_docker_restart_policy: unless-stopped

# State
metube_role_docker_state: started
