##########################################################################
# Title:         Sandbox: linkding | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

linkding_name: linkding

################################
# Paths
################################

linkding_role_paths_folder: "{{ linkding_name }}"
linkding_role_paths_location: "{{ server_appdata_path }}/{{ linkding_role_paths_folder }}"
linkding_role_paths_folders_list:
  - "{{ linkding_role_paths_location }}"

################################
# Web
################################

linkding_role_web_subdomain: "{{ linkding_name }}"
linkding_role_web_domain: "{{ user.domain }}"
linkding_role_web_port: "9090"
linkding_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='linkding') + '.' + lookup('role_var', '_web_domain', role='linkding')
                        if (lookup('role_var', '_web_subdomain', role='linkding') | length > 0)
                        else lookup('role_var', '_web_domain', role='linkding')) }}"

################################
# DNS
################################

linkding_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='linkding') }}"
linkding_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='linkding') }}"
linkding_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

linkding_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
linkding_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
linkding_role_traefik_middleware_custom: ""
linkding_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
linkding_role_traefik_enabled: true
linkding_role_traefik_api_enabled: true
linkding_role_traefik_api_endpoint: "PathPrefix(`/api`)"
linkding_role_traefik_api_middleware_http: "{{ 'dropsecurityheaders@file,' + traefik_default_middleware_http_api }}"
linkding_role_traefik_api_middleware: "{{ 'dropsecurityheaders@file,' + traefik_default_middleware_api }}"

################################
# Docker
################################

# Container
linkding_role_docker_container: "{{ linkding_name }}"

# Image
linkding_role_docker_image_pull: true
linkding_role_docker_image_tag: "latest"
linkding_role_docker_image_repo: "sissbruecker/linkding"
linkding_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='linkding') }}:{{ lookup('role_var', '_docker_image_tag', role='linkding') }}"

# Envs
linkding_role_docker_envs_default:
  TZ: "{{ tz }}"
  LD_CONTAINER_NAME: "{{ linkding_name }}"
  LD_HOST_PORT: "9090"
  LD_HOST_DATA_DIR: "./data"
  LD_SUPERUSER_NAME: "{{ user.name }}"
  LD_SUPERUSER_PASSWORD: "{{ user.pass }}"
  LD_DISABLE_BACKGROUND_TASKS: "false"
  LD_DISABLE_URL_VALIDATION: "false"
  LD_ENABLE_AUTH_PROXY: "false"
  LD_CSRF_TRUSTED_ORIGINS: "{{ lookup('role_var', '_web_url', role='linkding') }}"
linkding_role_docker_envs_custom: {}
linkding_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='linkding')
                               | combine(lookup('role_var', '_docker_envs_custom', role='linkding')) }}"

# Volumes
linkding_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='linkding') }}:/etc/linkding/data"
linkding_role_docker_volumes_custom: []
linkding_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='linkding')
                                  + lookup('role_var', '_docker_volumes_custom', role='linkding') }}"

# Hostname
linkding_role_docker_hostname: "{{ linkding_name }}"

# Networks
linkding_role_docker_networks_alias: "{{ linkding_name }}"
linkding_role_docker_networks_default: []
linkding_role_docker_networks_custom: []
linkding_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='linkding')
                                   + lookup('role_var', '_docker_networks_custom', role='linkding') }}"

# Restart Policy
linkding_role_docker_restart_policy: unless-stopped

# State
linkding_role_docker_state: started
