##########################################################################
# Title:            Sandbox: Jirafeau | Default Variables                #
# Author(s):        zhdenny, kowalski                                    #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

jirafeau_name: jirafeau

################################
# Paths
################################

jirafeau_paths_folder: "{{ jirafeau_name }}"
jirafeau_paths_location: "{{ server_appdata_path }}/{{ jirafeau_paths_folder }}"
jirafeau_paths_folders_list:
  - "{{ jirafeau_paths_location }}/www"
  - "{{ jirafeau_paths_location }}/data"
  - "{{ jirafeau_paths_location }}/cfg"

################################
# Web
################################

jirafeau_web_subdomain: "{{ jirafeau_name }}"
jirafeau_web_domain: "{{ user.domain }}"
jirafeau_web_port: "80"
jirafeau_web_url: "{{ 'https://' + jirafeau_web_subdomain + '.' + jirafeau_web_domain }}"

################################
# DNS
################################

jirafeau_dns_record: "{{ jirafeau_web_subdomain }}"
jirafeau_dns_zone: "{{ jirafeau_web_domain }}"
jirafeau_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

jirafeau_traefik_middleware: "{{ traefik_default_middleware }}"
jirafeau_traefik_certresolver: "{{ traefik_default_certresolver }}"
jirafeau_traefik_enabled: true

################################
# Docker
################################

# Container
jirafeau_docker_container: "{{ jirafeau_name }}"

# Image
jirafeau_docker_image_pull: true
jirafeau_docker_image_tag: "latest"
jirafeau_docker_image: "jgeusebroek/jirafeau:{{ jirafeau_docker_image_tag }}"

# Ports
jirafeau_docker_ports_defaults: []
jirafeau_docker_ports_custom: []
jirafeau_docker_ports: "{{ jirafeau_docker_ports_defaults
                           + jirafeau_docker_ports_custom }}"

# Envs
jirafeau_docker_envs_default:
  UID: "{{ uid }}"
  GID: "{{ gid }}"
jirafeau_docker_envs_custom: {}
jirafeau_docker_envs: "{{ jirafeau_docker_envs_default
                          | combine(jirafeau_docker_envs_custom) }}"

# Commands
jirafeau_docker_commands_default: []
jirafeau_docker_commands_custom: []
jirafeau_docker_commands: "{{ jirafeau_docker_commands_default
                              + jirafeau_docker_commands_custom }}"

# Volumes
jirafeau_docker_volumes_default:
  - "{{ jirafeau_paths_location }}/cfg:/cfg:rw"
  - "{{ jirafeau_paths_location }}/data:/data:rw"

jirafeau_docker_volumes_custom: []
jirafeau_docker_volumes: "{{ jirafeau_docker_volumes_default
                             + jirafeau_docker_volumes_custom }}"

# Devices
jirafeau_docker_devices_default: []
jirafeau_docker_devices_custom: []
jirafeau_docker_devices: "{{ jirafeau_docker_devices_default
                             + jirafeau_docker_devices_custom }}"

# Hosts
jirafeau_docker_hosts_default: []
jirafeau_docker_hosts_custom: []
jirafeau_docker_hosts: "{{ docker_hosts_common
                           | combine(jirafeau_docker_hosts_default)
                           | combine(jirafeau_docker_hosts_custom) }}"

# Labels
jirafeau_docker_labels_default: {}
jirafeau_docker_labels_custom: {}
jirafeau_docker_labels: "{{ docker_labels_common
                            | combine(jirafeau_docker_labels_default)
                            | combine(jirafeau_docker_labels_custom) }}"

# Hostname
jirafeau_docker_hostname: "{{ jirafeau_name }}"

# Networks
jirafeau_docker_networks_alias: "{{ jirafeau_name }}"
jirafeau_docker_networks_default: []
jirafeau_docker_networks_custom: []
jirafeau_docker_networks: "{{ docker_networks_common
                              + jirafeau_docker_networks_default
                              + jirafeau_docker_networks_custom }}"

# Capabilities
jirafeau_docker_capabilities_default: []
jirafeau_docker_capabilities_custom: []
jirafeau_docker_capabilities: "{{ jirafeau_docker_capabilities_default
                                  + jirafeau_docker_capabilities_custom }}"

# Security Opts
jirafeau_docker_security_opts_default: []
jirafeau_docker_security_opts_custom: []
jirafeau_docker_security_opts: "{{ jirafeau_docker_security_opts_default
                                   + jirafeau_docker_security_opts_custom }}"

# Restart Policy
jirafeau_docker_restart_policy: unless-stopped

# State
jirafeau_docker_state: started
