##########################################################################
# Title:         Sandbox: OliveTin | Default Variables                   #
# Author(s):     owine                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

olivetin_name: olivetin

################################
# Paths
################################

olivetin_role_paths_folder: "{{ olivetin_name }}"
olivetin_role_paths_location: "{{ server_appdata_path }}/{{ olivetin_role_paths_folder }}"
olivetin_role_paths_config_location: "{{ olivetin_role_paths_location }}/config.yaml"
olivetin_role_paths_folders_list:
  - "{{ olivetin_role_paths_location }}"

################################
# Web
################################

olivetin_role_web_subdomain: "{{ olivetin_name }}"
olivetin_role_web_domain: "{{ user.domain }}"
olivetin_role_web_port: "1337"
olivetin_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='olivetin') + '.' + lookup('role_var', '_web_domain', role='olivetin')
                        if (lookup('role_var', '_web_subdomain', role='olivetin') | length > 0)
                        else lookup('role_var', '_web_domain', role='olivetin')) }}"

################################
# DNS
################################

olivetin_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='olivetin') }}"
olivetin_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='olivetin') }}"
olivetin_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

olivetin_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
olivetin_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
olivetin_role_traefik_middleware_custom: ""
olivetin_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
olivetin_role_traefik_enabled: true
olivetin_role_traefik_api_enabled: false
olivetin_role_traefik_api_endpoint: ""

olivetin_role_traefik_middleware_api: "{{ traefik_global_middleware }}"

################################
# Docker
################################

# Container
olivetin_role_docker_container: "{{ olivetin_name }}"

# Image
olivetin_role_docker_image_pull: true
olivetin_role_docker_image_tag: "latest"
olivetin_role_docker_image_repo: "jamesread/olivetin"
olivetin_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='olivetin') }}:{{ lookup('role_var', '_docker_image_tag', role='olivetin') }}"

# Envs
olivetin_role_docker_envs_default:
  TZ: "{{ tz }}"
olivetin_role_docker_envs_custom: {}
olivetin_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='olivetin')
                               | combine(lookup('role_var', '_docker_envs_custom', role='olivetin')) }}"

# Volumes
olivetin_role_docker_volumes_default:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "{{ lookup('role_var', '_paths_location', role='olivetin') }}:/config"
olivetin_role_docker_volumes_custom: []
olivetin_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='olivetin')
                                  + lookup('role_var', '_docker_volumes_custom', role='olivetin') }}"

# Hostname
olivetin_role_docker_hostname: "{{ olivetin_name }}"

# Networks
olivetin_role_docker_networks_alias: "{{ olivetin_name }}"
olivetin_role_docker_networks_default: []
olivetin_role_docker_networks_custom: []
olivetin_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='olivetin')
                                   + lookup('role_var', '_docker_networks_custom', role='olivetin') }}"

# Restart Policy
olivetin_role_docker_restart_policy: unless-stopped

# State
olivetin_role_docker_state: started

# User
olivetin_role_docker_user: "0:0"
