##########################################################################
# Title:         Sandbox: MovieMatch | Default Variables                 #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

moviematch_name: moviematch

################################
# Settings
################################

moviematch_role_plex_url: "http://plex:32400"
moviematch_role_libraries: "Movies"

################################
# Paths
################################

moviematch_role_paths_folder: "{{ moviematch_name }}"
moviematch_role_paths_location: "{{ server_appdata_path }}/{{ moviematch_role_paths_folder }}"
moviematch_role_paths_folders_list:
  - "{{ moviematch_role_paths_location }}"

################################
# Web
################################

moviematch_role_web_subdomain: "{{ moviematch_name }}"
moviematch_role_web_domain: "{{ user.domain }}"
moviematch_role_web_port: "8000"
moviematch_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='moviematch') + '.' + lookup('role_var', '_web_domain', role='moviematch')
                          if (lookup('role_var', '_web_subdomain', role='moviematch') | length > 0)
                          else lookup('role_var', '_web_domain', role='moviematch')) }}"

################################
# DNS
################################

moviematch_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='moviematch') }}"
moviematch_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='moviematch') }}"
moviematch_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

moviematch_role_traefik_sso_middleware: ""
moviematch_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
moviematch_role_traefik_middleware_custom: ""
moviematch_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
moviematch_role_traefik_enabled: true
moviematch_role_traefik_api_enabled: false
moviematch_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
moviematch_role_docker_container: "{{ moviematch_name }}"

# Image
moviematch_role_docker_image_pull: true
moviematch_role_docker_image_tag: "latest"
moviematch_role_docker_image_repo: "lukechannings/moviematch"
moviematch_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='moviematch') }}:{{ lookup('role_var', '_docker_image_tag', role='moviematch') }}"

# Envs
moviematch_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  PLEX_URL: "{{ lookup('role_var', '_plex_url', role='moviematch') }}"
  PLEX_TOKEN: "{{ plex_auth_token }}"
  LOG_LEVEL: DEBUG
  LIBRARY_FILTER: "{{ lookup('role_var', '_libraries', role='moviematch') }}"
moviematch_role_docker_envs_custom: {}
moviematch_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='moviematch')
                                 | combine(lookup('role_var', '_docker_envs_custom', role='moviematch')) }}"

# Hostname
moviematch_role_docker_hostname: "{{ moviematch_name }}"

# Networks
moviematch_role_docker_networks_alias: "{{ moviematch_name }}"
moviematch_role_docker_networks_default: []
moviematch_role_docker_networks_custom: []
moviematch_role_docker_networks: "{{ docker_networks_common
                                     + lookup('role_var', '_docker_networks_default', role='moviematch')
                                     + lookup('role_var', '_docker_networks_custom', role='moviematch') }}"

# Restart Policy
moviematch_role_docker_restart_policy: unless-stopped

# State
moviematch_role_docker_state: started
