##########################################################################
# Title:         Sandbox: MovieMatch | Default Variables                 #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

moviematch_name: moviematch

################################
# Paths
################################

moviematch_paths_folder: "{{ moviematch_name }}"
moviematch_paths_location: "{{ server_appdata_path }}/{{ moviematch_paths_folder }}"
moviematch_paths_folders_list:
  - "{{ moviematch_paths_location }}"

################################
# Web
################################

moviematch_web_subdomain: "{{ moviematch_name }}"
moviematch_web_domain: "{{ user.domain }}"
moviematch_web_port: "8000"
moviematch_web_url: "{{ 'https://' + (moviematch_web_subdomain + '.' + moviematch_web_domain
                     if (moviematch_web_subdomain | length > 0)
                     else moviematch_web_domain) }}"

################################
# DNS
################################

moviematch_dns_record: "{{ moviematch_web_subdomain }}"
moviematch_dns_zone: "{{ moviematch_web_domain }}"
moviematch_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

moviematch_traefik_sso_middleware: ""
moviematch_traefik_middleware_default: "{{ traefik_default_middleware }}"
moviematch_traefik_middleware_custom: ""
moviematch_traefik_certresolver: "{{ traefik_default_certresolver }}"
moviematch_traefik_enabled: true
moviematch_traefik_api_enabled: false
moviematch_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
moviematch_docker_container: "{{ moviematch_name }}"

# Image
moviematch_docker_image_pull: true
moviematch_docker_image_tag: "latest"
moviematch_docker_image: "lukechannings/moviematch:{{ moviematch_docker_image_tag }}"

# Ports
moviematch_docker_ports_defaults: []
moviematch_docker_ports_custom: []
moviematch_docker_ports: "{{ moviematch_docker_ports_defaults
                             + moviematch_docker_ports_custom }}"

# Envs
moviematch_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  PLEX_URL: "{{ moviematch.plex_url }}"
  PLEX_TOKEN: "{{ plex_auth_token }}"
  LOG_LEVEL: DEBUG
  LIBRARY_FILTER: "{{ moviematch.libraries }}"
moviematch_docker_envs_custom: {}
moviematch_docker_envs: "{{ moviematch_docker_envs_default
                            | combine(moviematch_docker_envs_custom) }}"

# Commands
moviematch_docker_commands_default: []
moviematch_docker_commands_custom: []
moviematch_docker_commands: "{{ moviematch_docker_commands_default
                                + moviematch_docker_commands_custom }}"

# Volumes
moviematch_docker_volumes_default: []
moviematch_docker_volumes_custom: []
moviematch_docker_volumes: "{{ moviematch_docker_volumes_default
                               + moviematch_docker_volumes_custom }}"

# Devices
moviematch_docker_devices_default: []
moviematch_docker_devices_custom: []
moviematch_docker_devices: "{{ moviematch_docker_devices_default
                               + moviematch_docker_devices_custom }}"

# Hosts
moviematch_docker_hosts_default: {}
moviematch_docker_hosts_custom: {}
moviematch_docker_hosts: "{{ docker_hosts_common
                             | combine(moviematch_docker_hosts_default)
                             | combine(moviematch_docker_hosts_custom) }}"

# Labels
moviematch_docker_labels_default: {}
moviematch_docker_labels_custom: {}
moviematch_docker_labels: "{{ docker_labels_common
                              | combine(moviematch_docker_labels_default)
                              | combine(moviematch_docker_labels_custom) }}"

# Hostname
moviematch_docker_hostname: "{{ moviematch_name }}"

# Networks
moviematch_docker_networks_alias: "{{ moviematch_name }}"
moviematch_docker_networks_default: []
moviematch_docker_networks_custom: []
moviematch_docker_networks: "{{ docker_networks_common
                                + moviematch_docker_networks_default
                                + moviematch_docker_networks_custom }}"

# Capabilities
moviematch_docker_capabilities_default: []
moviematch_docker_capabilities_custom: []
moviematch_docker_capabilities: "{{ moviematch_docker_capabilities_default
                                    + moviematch_docker_capabilities_custom }}"

# Security Opts
moviematch_docker_security_opts_default: []
moviematch_docker_security_opts_custom: []
moviematch_docker_security_opts: "{{ moviematch_docker_security_opts_default
                                     + moviematch_docker_security_opts_custom }}"

# Restart Policy
moviematch_docker_restart_policy: unless-stopped

# State
moviematch_docker_state: started
