##########################################################################
# Title:            Sandbox: Notifiarr Client | Default Variables        #
# Author(s):        kowalski, salty                                      #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

notifiarr_name: notifiarr

################################
# Settings
################################

notifiarr_privileged: false

################################
# Paths
################################

notifiarr_role_paths_folder: "{{ notifiarr_name }}"
notifiarr_role_paths_location: "{{ server_appdata_path }}/{{ notifiarr_role_paths_folder }}"
notifiarr_role_paths_folders_list:
  - "{{ notifiarr_role_paths_location }}"
notifiarr_role_paths_recursive: true
notifiarr_role_paths_config_location: "{{ notifiarr_role_paths_location }}/notifiarr.conf"
notifiarr_radarr_config: "{{ lookup('role_var', '_paths_location', role='radarr') }}/config.xml"
notifiarr_sonarr_config: "{{ lookup('role_var', '_paths_location', role='sonarr') }}/config.xml"
notifiarr_tautulli_config: "{{ lookup('role_var', '_paths_location', role='tautulli') }}/config.ini"
tautulli_api_key: "{{ (lookup('ini', 'api_key section=General file={{ notifiarr_tautulli_config }}')) if tautulli_config.stat.exists else '' }}"

################################
# Web
################################

notifiarr_role_web_subdomain: "{{ notifiarr_name }}"
notifiarr_role_web_domain: "{{ user.domain }}"
notifiarr_role_web_port: "5454"
notifiarr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='notifiarr') + '.' + lookup('role_var', '_web_domain', role='notifiarr')
                         if (lookup('role_var', '_web_subdomain', role='notifiarr') | length > 0)
                         else lookup('role_var', '_web_domain', role='notifiarr')) }}"

################################
# DNS
################################

notifiarr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='notifiarr') }}"
notifiarr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='notifiarr') }}"
notifiarr_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

notifiarr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
notifiarr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
notifiarr_role_traefik_middleware_custom: ""
notifiarr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
notifiarr_role_traefik_enabled: true
notifiarr_role_traefik_api_enabled: true
notifiarr_role_traefik_api_endpoint: "PathPrefix(`/api`) || PathPrefix(`/plex`)"

################################
# Docker
################################

# Container
notifiarr_role_docker_container: "{{ notifiarr_name }}"

# Image
notifiarr_role_docker_image_pull: true
notifiarr_role_docker_image_tag: "latest"
notifiarr_role_docker_image_repo: "golift/notifiarr"
notifiarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='notifiarr') }}:{{ lookup('role_var', '_docker_image_tag', role='notifiarr') }}"

# Envs
notifiarr_role_docker_envs_default:
  TZ: "{{ tz }}"
notifiarr_role_docker_envs_custom: {}
notifiarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='notifiarr')
                                | combine(lookup('role_var', '_docker_envs_custom', role='notifiarr')) }}"

# Volumes
notifiarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='notifiarr') }}:/config"
  - "/var/run/utmp:/var/run/utmp"
notifiarr_role_docker_volumes_custom: []
notifiarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='notifiarr')
                                   + lookup('role_var', '_docker_volumes_custom', role='notifiarr') }}"

# Mounts
notifiarr_role_docker_mounts_default:
  - target: /tmp
    type: tmpfs
notifiarr_role_docker_mounts_custom: []
notifiarr_role_docker_mounts: "{{ lookup('role_var', '_docker_mounts_default', role='notifiarr')
                                  + lookup('role_var', '_docker_mounts_custom', role='notifiarr') }}"

# Hostname
notifiarr_role_docker_hostname: "{{ traefik_host }}"

# Networks
notifiarr_role_docker_networks_alias: "{{ notifiarr_name }}"
notifiarr_role_docker_networks_default: []
notifiarr_role_docker_networks_custom: []
notifiarr_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='notifiarr')
                                    + lookup('role_var', '_docker_networks_custom', role='notifiarr') }}"

# Restart Policy
notifiarr_role_docker_restart_policy: unless-stopped

# State
notifiarr_role_docker_state: started

# User
notifiarr_role_docker_user: "{{ uid }}:{{ gid }}"

# Privileged
notifiarr_role_docker_privileged: "{{ notifiarr_privileged | bool }}"
