#########################################################################
# Title:         Sandbox: Plex-Credits-Detect                           #
# Author(s):     owine                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check config exists
  ansible.builtin.stat:
    path: "{{ plex_credits_detect_config_location }}"
  register: plex_credits_detect_config

- name: Set Default Plex instance
  ansible.builtin.set_fact:
    plex_name: "{{ plex_name | default(plex_instances[0]) }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Import default config
  ansible.builtin.template:
    src: fingerprint.ini.j2
    dest: "{{ plex_credits_detect_config_location }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: not plex_credits_detect_config.stat.exists

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
