#########################################################################
# Title:            Sandbox: Teamspeak                                  #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb

- name: MariaDB | Create {{ teamspeak_name }} database
  community.mysql.mysql_db:
    name: "{{ teamspeak_name }}"
    login_host: "mariadb"
    login_user: "root"
    login_password: "{{ mariadb_docker_env_password }}"
    state: present

- name: Get next available port within the range of '9987-9997' # noqa fqcn[action]
  find_open_port:
    low_bound: 9987
    high_bound: 9997
    protocol: udp
  register: port_lookup_voice
  ignore_errors: true

- name: Get next available port within the range of '10011-10021' # noqa fqcn[action]
  find_open_port:
    low_bound: 10011
    high_bound: 10021
    protocol: tcp
  register: port_lookup_webquery
  ignore_errors: true

- name: Get next available port within the range of '30033-30043' # noqa fqcn[action]
  find_open_port:
    low_bound: 30033
    high_bound: 30043
    protocol: tcp
  register: port_lookup_file
  ignore_errors: true

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Add SRV record
  community.general.cloudflare_dns:
    account_api_key: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    port: "{{ teamspeak_docker_ports_9987 }}"
    priority: 10
    proto: udp
    proxied: false
    record: "{{ _dns_tasker_record }}"
    service: "ts3"
    solo: true
    state: present
    type: SRV
    value: "{{ _dns_tasker_record }}.{{ _dns_tasker_zone }}"
    weight: 20
    zone: "{{ _dns_tasker_zone }}"
  when: cloudflare_is_enabled

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Port Information
  ansible.builtin.debug:
    msg:
      - "Voice port is: {{ teamspeak_docker_ports_9987 }}"
      - "Web Query port is: {{ teamspeak_docker_ports_10011 }}"
      - "File port is: {{ teamspeak_docker_ports_30033 }}"
