##########################################################################
# Title:         Sandbox: Mylar3 | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

mylar3_name: mylar3

################################
# Paths
################################

mylar3_paths_folder: "{{ mylar3_name }}"
mylar3_paths_location: "{{ server_appdata_path }}/{{ mylar3_paths_folder }}"
mylar3_paths_folders_list:
  - "{{ mylar3_paths_location }}"
  - /mnt/local/Media/Comics

################################
# Web
################################

mylar3_web_subdomain: "{{ mylar3_name }}"
mylar3_web_domain: "{{ user.domain }}"
mylar3_web_port: "8090"
mylar3_web_url: "{{ 'https://' + (mylar3_web_subdomain + '.' + mylar3_web_domain
                 if (mylar3_web_subdomain | length > 0)
                 else mylar3_web_domain) }}"

################################
# DNS
################################

mylar3_dns_record: "{{ mylar3_web_subdomain }}"
mylar3_dns_zone: "{{ mylar3_web_domain }}"
mylar3_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

mylar3_traefik_sso_middleware: ""
mylar3_traefik_middleware_default: "{{ traefik_default_middleware }}"
mylar3_traefik_middleware_custom: ""
mylar3_traefik_certresolver: "{{ traefik_default_certresolver }}"
mylar3_traefik_enabled: true
mylar3_traefik_api_enabled: false
mylar3_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
mylar3_docker_container: "{{ mylar3_name }}"

# Image
mylar3_docker_image_pull: true
mylar3_docker_image_tag: "latest"
mylar3_docker_image: "lscr.io/linuxserver/mylar3:{{ mylar3_docker_image_tag }}"

# Ports
mylar3_docker_ports_defaults: []
mylar3_docker_ports_custom: []
mylar3_docker_ports: "{{ mylar3_docker_ports_defaults
                         + mylar3_docker_ports_custom }}"

# Envs
mylar3_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
mylar3_docker_envs_custom: {}
mylar3_docker_envs: "{{ mylar3_docker_envs_default
                        | combine(mylar3_docker_envs_custom) }}"

# Commands
mylar3_docker_commands_default: []
mylar3_docker_commands_custom: []
mylar3_docker_commands: "{{ mylar3_docker_commands_default
                            + mylar3_docker_commands_custom }}"

# Volumes
mylar3_docker_volumes_default:
  - "{{ mylar3_paths_location }}:/config"
  - "/mnt/unionfs/Media/Comics:/comics"
mylar3_docker_volumes_custom: []
mylar3_docker_volumes: "{{ mylar3_docker_volumes_default
                           + mylar3_docker_volumes_custom }}"

# Devices
mylar3_docker_devices_default: []
mylar3_docker_devices_custom: []
mylar3_docker_devices: "{{ mylar3_docker_devices_default
                           + mylar3_docker_devices_custom }}"

# Hosts
mylar3_docker_hosts_default: {}
mylar3_docker_hosts_custom: {}
mylar3_docker_hosts: "{{ docker_hosts_common
                         | combine(mylar3_docker_hosts_default)
                         | combine(mylar3_docker_hosts_custom) }}"

# Labels
mylar3_docker_labels_default: {}
mylar3_docker_labels_custom: {}
mylar3_docker_labels: "{{ docker_labels_common
                          | combine(mylar3_docker_labels_default)
                          | combine(mylar3_docker_labels_custom) }}"

# Hostname
mylar3_docker_hostname: "{{ mylar3_name }}"

# Networks
mylar3_docker_networks_alias: "{{ mylar3_name }}"
mylar3_docker_networks_default: []
mylar3_docker_networks_custom: []
mylar3_docker_networks: "{{ docker_networks_common
                            + mylar3_docker_networks_default
                            + mylar3_docker_networks_custom }}"

# Capabilities
mylar3_docker_capabilities_default: []
mylar3_docker_capabilities_custom: []
mylar3_docker_capabilities: "{{ mylar3_docker_capabilities_default
                                + mylar3_docker_capabilities_custom }}"

# Security Opts
mylar3_docker_security_opts_default: []
mylar3_docker_security_opts_custom: []
mylar3_docker_security_opts: "{{ mylar3_docker_security_opts_default
                                 + mylar3_docker_security_opts_custom }}"

# Restart Policy
mylar3_docker_restart_policy: unless-stopped

# State
mylar3_docker_state: started
