##########################################################################
# Title:         Sandbox: ResilioSync | Default Variables                #
# Author(s):     JohnClementine                                          #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

resiliosync_name: resiliosync
resiliosync_data_port: "55555"

################################
# Paths
################################

resiliosync_paths_folder: "{{ resiliosync_name }}"
resiliosync_paths_location: "{{ server_appdata_path }}/{{ resiliosync_paths_folder }}"
resiliosync_paths_folders_list:
  - "{{ resiliosync_paths_location }}"

################################
# Web
################################

resiliosync_web_subdomain: "{{ resiliosync_name }}"
resiliosync_web_domain: "{{ user.domain }}"
resiliosync_web_port: "8888"
resiliosync_web_url: "{{ 'https://' + (resiliosync_web_subdomain + '.' + resiliosync_web_domain
                      if (resiliosync_web_subdomain | length > 0)
                      else resiliosync_web_domain) }}"

################################
# DNS
################################

resiliosync_dns_record: "{{ resiliosync_web_subdomain }}"
resiliosync_dns_zone: "{{ resiliosync_web_domain }}"
resiliosync_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

resiliosync_traefik_sso_middleware: ""
resiliosync_traefik_middleware_default: "{{ traefik_default_middleware }}"
resiliosync_traefik_middleware_custom: ""
resiliosync_traefik_certresolver: "{{ traefik_default_certresolver }}"
resiliosync_traefik_enabled: true
resiliosync_traefik_api_enabled: false
resiliosync_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
resiliosync_docker_container: "{{ resiliosync_name }}"

# Image
resiliosync_docker_image_pull: true
resiliosync_docker_image_tag: "latest"
resiliosync_docker_image: "resilio/sync:{{ resiliosync_docker_image_tag }}"

# Ports
resiliosync_docker_ports_defaults:
  - "{{ resiliosync_data_port }}:{{ resiliosync_data_port }}"
resiliosync_docker_ports_custom: []
resiliosync_docker_ports: "{{ resiliosync_docker_ports_defaults
                              + resiliosync_docker_ports_custom }}"

# Envs
resiliosync_docker_envs_default: {}
resiliosync_docker_envs_custom: {}
resiliosync_docker_envs: "{{ resiliosync_docker_envs_default
                             | combine(resiliosync_docker_envs_custom) }}"
# Commands
resiliosync_docker_commands_default: []
resiliosync_docker_commands_custom: []
resiliosync_docker_commands: "{{ resiliosync_docker_commands_default
                                 + resiliosync_docker_commands_custom }}"

# Volumes
resiliosync_docker_volumes_global: false
resiliosync_docker_volumes_default:
  - "{{ resiliosync_paths_location }}:/mnt/sync"
  - "/mnt:/mnt/mounted_folders/mnt"
  - "/home:/mnt/mounted_folders/home"
resiliosync_docker_volumes_custom: []
resiliosync_docker_volumes: "{{ resiliosync_docker_volumes_default
                                + resiliosync_docker_volumes_custom }}"

# Devices
resiliosync_docker_devices_default: []
resiliosync_docker_devices_custom: []
resiliosync_docker_devices: "{{ resiliosync_docker_devices_default
                                + resiliosync_docker_devices_custom }}"

# Hosts
resiliosync_docker_hosts_default: {}
resiliosync_docker_hosts_custom: {}
resiliosync_docker_hosts: "{{ docker_hosts_common
                              | combine(resiliosync_docker_hosts_default)
                              | combine(resiliosync_docker_hosts_custom) }}"

# Labels
resiliosync_docker_labels_default: {}
resiliosync_docker_labels_custom: {}
resiliosync_docker_labels: "{{ docker_labels_common
                               | combine(resiliosync_docker_labels_default)
                               | combine(resiliosync_docker_labels_custom) }}"

# Hostname
resiliosync_docker_hostname: "{{ resiliosync_name }}"

# Networks
resiliosync_docker_networks_alias: "{{ resiliosync_name }}"
resiliosync_docker_networks_default: []
resiliosync_docker_networks_custom: []
resiliosync_docker_networks: "{{ docker_networks_common
                                 + resiliosync_docker_networks_default
                                 + resiliosync_docker_networks_custom }}"

# Capabilities
resiliosync_docker_capabilities_default: []
resiliosync_docker_capabilities_custom: []
resiliosync_docker_capabilities: "{{ resiliosync_docker_capabilities_default
                                     + resiliosync_docker_capabilities_custom }}"

# Security Opts
resiliosync_docker_security_opts_default: []
resiliosync_docker_security_opts_custom: []
resiliosync_docker_security_opts: "{{ resiliosync_docker_security_opts_default
                                      + resiliosync_docker_security_opts_custom }}"

# Restart Policy
resiliosync_docker_restart_policy: unless-stopped

# State
resiliosync_docker_state: started

# User
resiliosync_docker_user: "{{ uid }}:{{ gid }}"
