##########################################################################
# Title:            Sandbox: Membarr | Default Variables                 #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

membarr_name: membarr

################################
# Settings
################################

membarr_role_discord_token: "your_discord_bot_token"

################################
# Paths
################################

membarr_role_paths_folder: "{{ membarr_name }}"
membarr_role_paths_location: "{{ server_appdata_path }}/{{ membarr_role_paths_folder }}"
membarr_role_paths_recursive: true
membarr_role_paths_config_location: "{{ membarr_role_paths_location }}/config.ini"
membarr_role_paths_folders_list:
  - "{{ membarr_role_paths_location }}"

################################
# Docker
################################

# Container
membarr_role_docker_container: "{{ membarr_name }}"

# Image
membarr_role_docker_image_pull: true
membarr_role_docker_image_tag: "latest"
membarr_role_docker_image_repo: "yoruio/membarr"
membarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='membarr') }}:{{ lookup('role_var', '_docker_image_tag', role='membarr') }}"

# Envs
membarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  token: "{{ lookup('role_var', '_discord_token', role='membarr') }}"
membarr_role_docker_envs_custom: {}
membarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='membarr')
                              | combine(lookup('role_var', '_docker_envs_custom', role='membarr')) }}"

# Volumes
membarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='membarr') }}:/app/app/config"
membarr_role_docker_volumes_custom: []
membarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='membarr')
                                 + lookup('role_var', '_docker_volumes_custom', role='membarr') }}"

# Hostname
membarr_role_docker_hostname: "{{ membarr_name }}"

# Networks
membarr_role_docker_networks_alias: "{{ membarr_name }}"
membarr_role_docker_networks_default: []
membarr_role_docker_networks_custom: []
membarr_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='membarr')
                                  + lookup('role_var', '_docker_networks_custom', role='membarr') }}"

# Restart Policy
membarr_role_docker_restart_policy: unless-stopped

# State
membarr_role_docker_state: started

# User
membarr_role_docker_user: "{{ uid }}:{{ gid }}"
