##########################################################################
# Title:            Sandbox: Mealie                                      #
# Author(s):        Thundernerd, Grostim, kowalski                       #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

mealie_name: mealie

################################
# Paths
################################

mealie_role_paths_folder: "{{ mealie_name }}"
mealie_role_paths_location: "{{ server_appdata_path }}/{{ mealie_role_paths_folder }}"
mealie_role_paths_folders_list:
  - "{{ mealie_role_paths_location }}"

################################
# Web
################################

mealie_role_web_subdomain: "{{ mealie_name }}"
mealie_role_web_domain: "{{ user.domain }}"
mealie_role_web_port: "9000"
mealie_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='mealie') + '.' + lookup('role_var', '_web_domain', role='mealie')
                      if (lookup('role_var', '_web_subdomain', role='mealie') | length > 0)
                      else lookup('role_var', '_web_domain', role='mealie')) }}"

################################
# DNS
################################

mealie_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='mealie') }}"
mealie_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='mealie') }}"
mealie_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

mealie_role_traefik_sso_middleware: ""
mealie_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
mealie_role_traefik_middleware_custom: ""
mealie_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
mealie_role_traefik_enabled: true
mealie_role_traefik_api_enabled: false
mealie_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
mealie_role_docker_container: "{{ mealie_name }}"

# Image
mealie_role_docker_image_pull: true
mealie_role_docker_image_tag: "latest"
mealie_role_docker_image_repo: "ghcr.io/mealie-recipes/mealie"
mealie_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='mealie') }}:{{ lookup('role_var', '_docker_image_tag', role='mealie') }}"

# Envs
mealie_role_docker_envs_default:
  ALLOW_SIGNUP: "false"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  BASE_URL: "{{ lookup('role_var', '_web_url', role='mealie') }}"
mealie_role_docker_envs_custom: {}
mealie_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='mealie')
                             | combine(lookup('role_var', '_docker_envs_custom', role='mealie')) }}"

# Volumes
mealie_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='mealie') }}:/app/data"
mealie_role_docker_volumes_custom: []
mealie_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='mealie')
                                + lookup('role_var', '_docker_volumes_custom', role='mealie') }}"

# Hostname
mealie_role_docker_hostname: "{{ mealie_name }}"

# Networks
mealie_role_docker_networks_alias: "{{ mealie_name }}"
mealie_role_docker_networks_default: []
mealie_role_docker_networks_custom: []
mealie_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='mealie')
                                 + lookup('role_var', '_docker_networks_custom', role='mealie') }}"

# Restart Policy
mealie_role_docker_restart_policy: unless-stopped

# State
mealie_role_docker_state: started
