##########################################################################
# Title:         Saltbox: IT-Tools | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

it_tools_name: it-tools

################################
# Web
################################

it_tools_role_web_subdomain: "{{ it_tools_name }}"
it_tools_role_web_domain: "{{ user.domain }}"
it_tools_role_web_port: "80"
it_tools_role_web_url: "{{ 'https://' + (it_tools_role_web_subdomain + '.' + it_tools_role_web_domain
                   if (it_tools_role_web_subdomain | length > 0)
                   else it_tools_role_web_domain) }}"

################################
# DNS
################################

it_tools_role_dns_record: "{{ it_tools_role_web_subdomain }}"
it_tools_role_dns_zone: "{{ it_tools_role_web_domain }}"
it_tools_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

it_tools_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
it_tools_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
it_tools_role_traefik_middleware_custom: ""
it_tools_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
it_tools_role_traefik_enabled: true
it_tools_role_traefik_api_enabled: false
it_tools_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
it_tools_role_docker_container: "{{ it_tools_name }}"

# Image
it_tools_role_docker_image_pull: true
it_tools_role_docker_image_tag: "latest"
it_tools_role_docker_image: "corentinth/it-tools:{{ it_tools_role_docker_image_tag }}"

# Volumes
it_tools_role_docker_volumes_global: false

# Hostname
it_tools_role_docker_hostname: "{{ it_tools_name }}"

# Networks
it_tools_role_docker_networks_alias: "{{ it_tools_name }}"
it_tools_role_docker_networks_default: []
it_tools_role_docker_networks_custom: []
it_tools_role_docker_networks: "{{ docker_networks_common
                              + it_tools_role_docker_networks_default
                              + it_tools_role_docker_networks_custom }}"

# Restart Policy
it_tools_role_docker_restart_policy: unless-stopped

# State
it_tools_role_docker_state: started
