##########################################################################
# Title:            Sandbox: homarr | Default Variables                  #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Docker Socket Proxy
################################

homarr_role_docker_socket_proxy_envs:
  CONTAINERS: "1"
  POST: "0"

################################
# Basics
################################

homarr_name: homarr

################################
# Paths
################################

homarr_role_paths_folder: "{{ homarr_name }}"
homarr_role_paths_location: "{{ server_appdata_path }}/{{ homarr_role_paths_folder }}"
homarr_role_paths_folders_list:
  - "{{ homarr_role_paths_location }}"
  - "{{ homarr_role_paths_location }}/icons"

################################
# Web
################################

homarr_role_web_subdomain: "{{ homarr_name }}"
homarr_role_web_domain: "{{ user.domain }}"
homarr_role_web_port: "7575"
homarr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='homarr') + '.' + lookup('role_var', '_web_domain', role='homarr')
                      if (lookup('role_var', '_web_subdomain', role='homarr') | length > 0)
                      else lookup('role_var', '_web_domain', role='homarr')) }}"

################################
# DNS
################################

homarr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='homarr') }}"
homarr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='homarr') }}"
homarr_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

homarr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
homarr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
homarr_role_traefik_middleware_custom: ""
homarr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
homarr_role_traefik_enabled: true
homarr_role_traefik_api_enabled: false
homarr_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
homarr_role_docker_container: "{{ homarr_name }}"

# Image
homarr_role_docker_image_pull: true
homarr_role_docker_image_repo: "ghcr.io/ajnart/homarr"
homarr_role_docker_image_tag: "latest"
homarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='homarr') }}:{{ lookup('role_var', '_docker_image_tag', role='homarr') }}"

# Envs
homarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  BASE_URL: "{{ lookup('role_var', '_web_subdomain', role='homarr') + '.' + lookup('role_var', '_web_domain', role='homarr') }}"
  PASSWORD: "{{ user.pass }}"
  DOCKER_HOST: "tcp://{{ homarr_name }}-docker-socket-proxy:2375"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
homarr_role_docker_envs_custom: {}
homarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='homarr')
                             | combine(lookup('role_var', '_docker_envs_custom', role='homarr')) }}"

# Volumes
homarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='homarr') }}:/app/data/configs"
  - "{{ lookup('role_var', '_paths_location', role='homarr') }}/icons:/app/public/icons"
homarr_role_docker_volumes_custom: []
homarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='homarr')
                                + lookup('role_var', '_docker_volumes_custom', role='homarr') }}"

# Hostname
homarr_role_docker_hostname: "{{ homarr_name }}"

# Networks
homarr_role_docker_networks_alias: "{{ homarr_name }}"
homarr_role_docker_networks_default: []
homarr_role_docker_networks_custom: []
homarr_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='homarr')
                                 + lookup('role_var', '_docker_networks_custom', role='homarr') }}"

# Restart Policy
homarr_role_docker_restart_policy: unless-stopped

# State
homarr_role_docker_state: started

# Dependencies
homarr_depends_on: "{{ homarr_name }}-docker-socket-proxy"
homarr_depends_on_delay: "0"
homarr_depends_on_healthchecks: "false"
