##########################################################################
# Title:            Sandbox: Codex | Default Variables                   #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

codex_name: codex

################################
# Paths
################################

codex_role_paths_folder: "{{ codex_name }}"
codex_role_paths_location: "{{ server_appdata_path }}/{{ codex_role_paths_folder }}"
codex_role_paths_folders_list:
  - "{{ codex_role_paths_location }}"
  - "{{ codex_role_paths_location }}/config"

################################
# Web
################################

codex_role_web_subdomain: "{{ codex_name }}"
codex_role_web_domain: "{{ user.domain }}"
codex_role_web_port: "9810"
codex_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='codex') + '.' + lookup('role_var', '_web_domain', role='codex')
                     if (lookup('role_var', '_web_subdomain', role='codex') | length > 0)
                     else lookup('role_var', '_web_domain', role='codex')) }}"

################################
# DNS
################################

codex_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='codex') }}"
codex_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='codex') }}"
codex_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

codex_role_traefik_sso_middleware: ""
codex_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
codex_role_traefik_middleware_custom: ""
codex_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
codex_role_traefik_enabled: true
codex_role_traefik_api_enabled: false
codex_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
codex_role_docker_container: "{{ codex_name }}"

# Image
codex_role_docker_image_pull: true
codex_role_docker_image_repo: "docker.io/ajslater/codex"
codex_role_docker_image_tag: "latest"
codex_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='codex') }}:{{ lookup('role_var', '_docker_image_tag', role='codex') }}"

# Envs
codex_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
codex_role_docker_envs_custom: {}
codex_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='codex')
                            | combine(lookup('role_var', '_docker_envs_custom', role='codex')) }}"

# Volumes
codex_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='codex') }}:/config"
codex_role_docker_volumes_custom: []
codex_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='codex')
                               + lookup('role_var', '_docker_volumes_custom', role='codex') }}"

# Hostname
codex_role_docker_hostname: "{{ codex_name }}"

# Networks
codex_role_docker_networks_alias: "{{ codex_name }}"
codex_role_docker_networks_default: []
codex_role_docker_networks_custom: []
codex_role_docker_networks: "{{ docker_networks_common
                                + lookup('role_var', '_docker_networks_default', role='codex')
                                + lookup('role_var', '_docker_networks_custom', role='codex') }}"

# Restart Policy
codex_role_docker_restart_policy: unless-stopped

# State
codex_role_docker_state: started
