##########################################################################
# Title:         Sandbox: Syncthing   | Default Variables                #
# Author(s):     Turbo                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

syncthing_name: syncthing

################################
# Paths
################################

syncthing_role_paths_folder: "{{ syncthing_name }}"
syncthing_role_paths_location: "{{ server_appdata_path }}/{{ syncthing_role_paths_folder }}"
syncthing_role_paths_folders_list:
  - "{{ syncthing_role_paths_location }}"

################################
# Web
################################

syncthing_role_web_subdomain: "{{ syncthing_name }}"
syncthing_role_web_domain: "{{ user.domain }}"
syncthing_role_web_port: "8384"
syncthing_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='syncthing') + '.' + lookup('role_var', '_web_domain', role='syncthing')
                         if (lookup('role_var', '_web_subdomain', role='syncthing') | length > 0)
                         else lookup('role_var', '_web_domain', role='syncthing')) }}"

################################
# DNS
################################

syncthing_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='syncthing') }}"
syncthing_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='syncthing') }}"
syncthing_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

syncthing_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
syncthing_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
syncthing_role_traefik_middleware_custom: ""
syncthing_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
syncthing_role_traefik_enabled: true
syncthing_role_traefik_api_enabled: false
syncthing_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
syncthing_role_docker_container: "{{ syncthing_name }}"

# Image
syncthing_role_docker_image_pull: true
syncthing_role_docker_image_repo: "lscr.io/linuxserver/syncthing"
syncthing_role_docker_image_tag: "latest"
syncthing_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='syncthing') }}:{{ lookup('role_var', '_docker_image_tag', role='syncthing') }}"

# Ports
syncthing_role_docker_ports_default:
  - "22000:22000/tcp"
  - "22000:22000/udp"
  - "21027:21027/udp"
syncthing_role_docker_ports_custom: []
syncthing_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='syncthing')
                                 + lookup('role_var', '_docker_ports_custom', role='syncthing') }}"

# Envs
syncthing_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
syncthing_role_docker_envs_custom: {}
syncthing_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='syncthing')
                                | combine(lookup('role_var', '_docker_envs_custom', role='syncthing')) }}"

# Volumes
syncthing_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='syncthing') }}:/config"
syncthing_role_docker_volumes_custom: []
syncthing_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='syncthing')
                                   + lookup('role_var', '_docker_volumes_custom', role='syncthing') }}"

# Hostname
syncthing_role_docker_hostname: "{{ syncthing_name }}"

# Networks
syncthing_role_docker_networks_alias: "{{ syncthing_name }}"
syncthing_role_docker_networks_default: []
syncthing_role_docker_networks_custom: []
syncthing_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='syncthing')
                                    + lookup('role_var', '_docker_networks_custom', role='syncthing') }}"

# Restart Policy
syncthing_role_docker_restart_policy: unless-stopped

# State
syncthing_role_docker_state: started
