#########################################################################
# Title:            Sandbox: Paperless Ngx                              #
# Author(s):        JigSawFr                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
# Versions: https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml
---
- name: Redis Role
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_instances: ["{{ paperless_ngx_name }}_redis"]
    redis_docker_image_tag: "7-alpine"
    redis_paths_folder: "{{ paperless_ngx_name }}"
    redis_paths_location: "{{ server_appdata_path }}/{{ redis_paths_folder }}/redis"

- name: PostgreSQL Role
  ansible.builtin.include_role:
    name: postgres
  vars:
    postgres_instances: ["{{ paperless_ngx_name }}_postgres"]
    postgres_docker_env_db: "{{ paperless_ngx_name }}"
    postgres_docker_image_tag: "14-alpine"
    postgres_paths_folder: "{{ paperless_ngx_name }}"
    postgres_paths_location: "{{ server_appdata_path }}/{{ postgres_paths_folder }}/postgres"

- name: Gotenberg Role
  ansible.builtin.include_role:
    name: gotenberg
  vars:
    gotenberg_name: "{{ paperless_ngx_name }}_gotenberg"
    gotenberg_docker_image_tag: "7-cloudrun"
    gotenberg_docker_commands_default:
      - "gotenberg"
      - "--chromium-disable-routes=true"
      - "--api-timeout=300s"
      - "--uno-listener-restart-threshold=0"
      - "--uno-listener-restart-threshold=300"
      - "--uno-listener-start-timeout=300s"
    gotenberg_paths_folder: "{{ paperless_ngx_name }}"
    gotenberg_paths_location: "{{ server_appdata_path }}/{{ gotenberg_paths_folder }}/gotenberg"

- name: Tika Role
  ansible.builtin.include_role:
    name: tika
  vars:
    tika_name: "{{ paperless_ngx_name }}_tika"
    tika_docker_image_tag: "latest"
    tika_paths_folder: "{{ paperless_ngx_name }}"
    tika_paths_location: "{{ server_appdata_path }}/{{ tika_paths_folder }}/tika"

- name: "Generate Secret Key for sessions"
  ansible.builtin.shell: "openssl rand -base64 45"
  register: paperless_ngx_secret_key

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: "Get number of physical processors"
  ansible.builtin.shell: "grep -c ^processor /proc/cpuinfo"
  register: paperless_ngx_proc

- name: Print Tweaking Info
  ansible.builtin.debug:
    msg: "Your server has {{ paperless_ngx_proc.stdout }} CPU cores, tweak your config using: https://paperless-ngx.readthedocs.io/en/latest/configuration.html#software-tweaks"
