##########################################################################
# Title:            Sandbox: ZNC | Default Variables                     #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

znc_name: znc

################################
# Paths
################################

znc_paths_folder: "{{ znc_name }}"
znc_paths_location: "{{ server_appdata_path }}/{{ znc_paths_folder }}"
znc_paths_folders_list:
  - "{{ znc_paths_location }}"

################################
# Web
################################

znc_web_subdomain: "{{ znc_name }}"
znc_web_domain: "{{ user.domain }}"
znc_web_port: "6501"
znc_web_url: "{{ 'https://' + (znc_web_subdomain + '.' + znc_web_domain
              if (znc_web_subdomain | length > 0)
              else znc_web_domain) }}"

################################
# DNS
################################

znc_dns_record: "{{ znc_web_subdomain }}"
znc_dns_zone: "{{ znc_web_domain }}"
znc_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

znc_traefik_sso_middleware: ""
znc_traefik_middleware_default: "{{ traefik_default_middleware }}"
znc_traefik_middleware_custom: ""
znc_traefik_certresolver: "{{ traefik_default_certresolver }}"
znc_traefik_enabled: true
znc_traefik_api_enabled: false
znc_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
znc_docker_container: "{{ znc_name }}"

# Image
znc_docker_image_pull: true
znc_docker_image_tag: "latest"
znc_docker_image: "lscr.io/linuxserver/znc:{{ znc_docker_image_tag }}"

# Ports
znc_docker_ports_defaults:
  - "{{ znc_web_port }}:{{ znc_web_port }}"
  - "6502:6502"
znc_docker_ports_custom: []
znc_docker_ports: "{{ znc_docker_ports_defaults
                      + znc_docker_ports_custom }}"

# Envs
znc_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
znc_docker_envs_custom: {}
znc_docker_envs: "{{ znc_docker_envs_default
                     | combine(znc_docker_envs_custom) }}"

# Commands
znc_docker_commands_default: []
znc_docker_commands_custom: []
znc_docker_commands: "{{ znc_docker_commands_default
                         + znc_docker_commands_custom }}"

# Volumes
znc_docker_volumes_default:
  - "{{ znc_paths_location }}:/config"
znc_docker_volumes_custom: []
znc_docker_volumes: "{{ znc_docker_volumes_default
                        + znc_docker_volumes_custom }}"

# Devices
znc_docker_devices_default: []
znc_docker_devices_custom: []
znc_docker_devices: "{{ znc_docker_devices_default
                        + znc_docker_devices_custom }}"

# Hosts
znc_docker_hosts_default: {}
znc_docker_hosts_custom: {}
znc_docker_hosts: "{{ docker_hosts_common
                      | combine(znc_docker_hosts_default)
                      | combine(znc_docker_hosts_custom) }}"

# Labels
znc_docker_labels_default: {}
znc_docker_labels_custom: {}
znc_docker_labels: "{{ docker_labels_common
                       | combine(znc_docker_labels_default)
                       | combine(znc_docker_labels_custom) }}"

# Hostname
znc_docker_hostname: "{{ znc_name }}"

# Networks
znc_docker_networks_alias: "{{ znc_name }}"
znc_docker_networks_default: []
znc_docker_networks_custom: []
znc_docker_networks: "{{ docker_networks_common
                         + znc_docker_networks_default
                         + znc_docker_networks_custom }}"

# Capabilities
znc_docker_capabilities_default: []
znc_docker_capabilities_custom: []
znc_docker_capabilities: "{{ znc_docker_capabilities_default
                             + znc_docker_capabilities_custom }}"

# Security Opts
znc_docker_security_opts_default: []
znc_docker_security_opts_custom: []
znc_docker_security_opts: "{{ znc_docker_security_opts_default
                              + znc_docker_security_opts_custom }}"

# Restart Policy
znc_docker_restart_policy: unless-stopped

# State
znc_docker_state: started
