##########################################################################
# Title:            Sandbox: ZNC | Default Variables                     #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

znc_name: znc

################################
# Paths
################################

znc_role_paths_folder: "{{ znc_name }}"
znc_role_paths_location: "{{ server_appdata_path }}/{{ znc_role_paths_folder }}"
znc_role_paths_folders_list:
  - "{{ znc_role_paths_location }}"

################################
# Web
################################

znc_role_web_subdomain: "{{ znc_name }}"
znc_role_web_domain: "{{ user.domain }}"
znc_role_web_port: "6501"
znc_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='znc') + '.' + lookup('role_var', '_web_domain', role='znc')
                   if (lookup('role_var', '_web_subdomain', role='znc') | length > 0)
                   else lookup('role_var', '_web_domain', role='znc')) }}"

################################
# DNS
################################

znc_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='znc') }}"
znc_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='znc') }}"
znc_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

znc_role_traefik_sso_middleware: ""
znc_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
znc_role_traefik_middleware_custom: ""
znc_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
znc_role_traefik_enabled: true
znc_role_traefik_api_enabled: false
znc_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
znc_role_docker_container: "{{ znc_name }}"

# Image
znc_role_docker_image_pull: true
znc_role_docker_image_repo: "lscr.io/linuxserver/znc"
znc_role_docker_image_tag: "latest"
znc_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='znc') }}:{{ lookup('role_var', '_docker_image_tag', role='znc') }}"

# Ports
znc_role_docker_ports_default:
  - "{{ lookup('role_var', '_web_port', role='znc') }}:{{ lookup('role_var', '_web_port', role='znc') }}"
  - "6502:6502"
znc_role_docker_ports_custom: []
znc_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='znc')
                           + lookup('role_var', '_docker_ports_custom', role='znc') }}"

# Envs
znc_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
znc_role_docker_envs_custom: {}
znc_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='znc')
                          | combine(lookup('role_var', '_docker_envs_custom', role='znc')) }}"

# Volumes
znc_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='znc') }}:/config"
znc_role_docker_volumes_custom: []
znc_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='znc')
                             + lookup('role_var', '_docker_volumes_custom', role='znc') }}"

# Hostname
znc_role_docker_hostname: "{{ znc_name }}"

# Networks
znc_role_docker_networks_alias: "{{ znc_name }}"
znc_role_docker_networks_default: []
znc_role_docker_networks_custom: []
znc_role_docker_networks: "{{ docker_networks_common
                              + lookup('role_var', '_docker_networks_default', role='znc')
                              + lookup('role_var', '_docker_networks_custom', role='znc') }}"

# Restart Policy
znc_role_docker_restart_policy: unless-stopped

# State
znc_role_docker_state: started
