#########################################################################
# Title:            Sandbox: Zigbee2mqtt                                #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Check if `{{ zigbee2mqtt_mqtt_config_location }}` exists
  ansible.builtin.stat:
    path: "{{ zigbee2mqtt_mqtt_config_location }}"
  register: mqtt_config

- name: "Fail when 'mosquitto.conf' is not present"
  ansible.builtin.fail:
    msg: "You need to install MQTT. https://docs.saltbox.dev/sandbox/apps/mqtt/. Zigbee2mqtt requires MQTT to function."
  when: (not mqtt_config.stat.exists) and (not continuous_integration)

- name: Check if `{{ zigbee2mqtt_config_location | basename }}` exists
  ansible.builtin.stat:
    path: "{{ zigbee2mqtt_config_location }}"
  register: zigbee2mqtt_config

- name: Import 'configuration.yaml'
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ zigbee2mqtt_config_location }}"
    mode: "664"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    force: true
  when: not zigbee2mqtt_config.stat.exists

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
