#########################################################################
# Title:            Sandbox: deemix                                     #
# Author(s):        chazlarson, kowalski                                #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

deemix_name: deemix

################################
# Paths
################################

deemix_paths_folder: "{{ deemix_name }}"
deemix_paths_location: "{{ server_appdata_path }}/{{ deemix_paths_folder }}"
deemix_paths_folders_list:
  - "{{ deemix_paths_location }}"

################################
# Web
################################

deemix_web_subdomain: "{{ deemix_name }}"
deemix_web_domain: "{{ user.domain }}"
deemix_web_port: "6595"
deemix_web_url: "{{ 'https://' + deemix_web_subdomain + '.' + deemix_web_domain
                 if (reverse_proxy_is_enabled)
                 else 'http://localhost:' + deemix_web_port }}"

################################
# DNS
################################

deemix_dns_record: "{{ deemix_web_subdomain }}"
deemix_dns_zone: "{{ deemix_web_domain }}"
deemix_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

deemix_traefik_middleware: "{{ traefik_default_middleware }}"
deemix_traefik_certresolver: "{{ traefik_default_certresolver }}"
deemix_traefik_enabled: true

################################
# Docker
################################

# Container
deemix_docker_container: "{{ deemix_name }}"

# Image
deemix_docker_image_pull: true
deemix_docker_image_tag: "latest"
deemix_docker_image: "registry.gitlab.com/bockiii/deemix-docker:{{ deemix_docker_image_tag }}"

# Ports
deemix_docker_ports_defaults:
  - "{{ deemix_web_port }}"
deemix_docker_ports_custom: []
deemix_docker_ports: "{{ deemix_docker_ports_defaults
                         + deemix_docker_ports_custom
                      if (not reverse_proxy_is_enabled)
                      else [] + deemix_docker_ports_custom }}"

# Envs
deemix_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  UMASK_SET: "022"
  REVERSEPROXY: "true"
deemix_docker_envs_custom: {}
deemix_docker_envs: "{{ deemix_docker_envs_default
                        | combine(deemix_docker_envs_custom) }}"

# Commands
deemix_docker_commands_default: []
deemix_docker_commands_custom: []
deemix_docker_commands: "{{ deemix_docker_commands_default
                            + deemix_docker_commands_custom }}"

# Volumes
deemix_docker_volumes_default:
  - "{{ deemix_paths_location }}:/config"
  - "/mnt:/mnt"
deemix_docker_volumes_custom: []
deemix_docker_volumes: "{{ deemix_docker_volumes_default
                           + deemix_docker_volumes_custom
                           + docker_volumes_downloads_common }}"

# Devices
deemix_docker_devices_default: []
deemix_docker_devices_custom: []
deemix_docker_devices: "{{ deemix_docker_devices_default
                           + deemix_docker_devices_custom }}"

# Hosts
deemix_docker_hosts_default: []
deemix_docker_hosts_custom: []
deemix_docker_hosts: "{{ docker_hosts_common
                         | combine(deemix_docker_hosts_default)
                         | combine(deemix_docker_hosts_custom) }}"

# Labels
deemix_docker_labels_default: {}
deemix_docker_labels_custom: {}
deemix_docker_labels: "{{ docker_labels_common
                          | combine(deemix_docker_labels_default)
                          | combine(deemix_docker_labels_custom) }}"

# Hostname
deemix_docker_hostname: "{{ deemix_name }}"

# Networks
deemix_docker_networks_alias: "{{ deemix_name }}"
deemix_docker_networks_default: []
deemix_docker_networks_custom: []
deemix_docker_networks: "{{ docker_networks_common
                            + deemix_docker_networks_default
                            + deemix_docker_networks_custom }}"

# Capabilities
deemix_docker_capabilities_default: []
deemix_docker_capabilities_custom: []
deemix_docker_capabilities: "{{ deemix_docker_capabilities_default
                                + deemix_docker_capabilities_custom }}"

# Security Opts
deemix_docker_security_opts_default: []
deemix_docker_security_opts_custom: []
deemix_docker_security_opts: "{{ deemix_docker_security_opts_default
                                 + deemix_docker_security_opts_custom }}"

# Restart Policy
deemix_docker_restart_policy: unless-stopped

# State
deemix_docker_state: started
