##########################################################################
# Title:            Sandbox: Heimdall | Default Variables                #
# Author(s):        TheBradz, desimaniac, kowalski, JigSawFr             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

heimdall_name: heimdall

################################
# Paths
################################

heimdall_role_paths_folder: "{{ heimdall_name }}"
heimdall_role_paths_location: "{{ server_appdata_path }}/{{ heimdall_role_paths_folder }}"
heimdall_role_paths_folders_list:
  - "{{ heimdall_role_paths_location }}"

################################
# Web
################################

heimdall_role_web_subdomain: "{{ heimdall_name }}"
heimdall_role_web_domain: "{{ user.domain }}"
heimdall_role_web_port: "80"
heimdall_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='heimdall') + '.' + lookup('role_var', '_web_domain', role='heimdall')
                        if (lookup('role_var', '_web_subdomain', role='heimdall') | length > 0)
                        else lookup('role_var', '_web_domain', role='heimdall')) }}"

################################
# DNS
################################

heimdall_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='heimdall') }}"
heimdall_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='heimdall') }}"
heimdall_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

heimdall_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
heimdall_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
heimdall_role_traefik_middleware_custom: ""
heimdall_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
heimdall_role_traefik_enabled: true
heimdall_role_traefik_api_enabled: false
heimdall_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
heimdall_role_docker_container: "{{ heimdall_name }}"

# Image
heimdall_role_docker_image_pull: true
heimdall_role_docker_image_repo: "lscr.io/linuxserver/heimdall"
heimdall_role_docker_image_tag: "latest"
heimdall_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='heimdall') }}:{{ lookup('role_var', '_docker_image_tag', role='heimdall') }}"

# Envs
heimdall_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
heimdall_role_docker_envs_custom: {}
heimdall_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='heimdall')
                               | combine(lookup('role_var', '_docker_envs_custom', role='heimdall')) }}"

# Volumes
heimdall_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='heimdall') }}:/config"
heimdall_role_docker_volumes_custom: []
heimdall_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='heimdall')
                                  + lookup('role_var', '_docker_volumes_custom', role='heimdall') }}"

# Hostname
heimdall_role_docker_hostname: "{{ heimdall_name }}"

# Networks
heimdall_role_docker_networks_alias: "{{ heimdall_name }}"
heimdall_role_docker_networks_default: []
heimdall_role_docker_networks_custom: []
heimdall_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default', role='heimdall')
                                   + lookup('role_var', '_docker_networks_custom', role='heimdall') }}"

# Restart Policy
heimdall_role_docker_restart_policy: unless-stopped

# State
heimdall_role_docker_state: started
