##########################################################################
# Title:            Sandbox: Chrome  | Default Variables                 #
# Author(s):        Zuke97                                               #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

chrome_name: chrome

################################
# Paths
################################

chrome_paths_folder: "{{ chrome_name }}"
chrome_paths_location: "{{ server_appdata_path }}/{{ chrome_paths_folder }}"
chrome_paths_folders_list:
  - "{{ chrome_paths_location }}"

################################
# Docker
################################

# Container
chrome_docker_container: "{{ chrome_name }}"

# Image
chrome_docker_image_pull: true
chrome_docker_image: "gcr.io/zenika-hub/alpine-chrome"
chrome_docker_image_tag: "123"

# Ports
chrome_docker_ports_defaults:
  - "9222:9222"
chrome_docker_ports_custom: []
chrome_docker_ports: "{{ chrome_docker_ports_defaults
                          + chrome_docker_ports_custom }}"

# Envs
chrome_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
chrome_docker_envs_custom: {}
chrome_docker_envs: "{{ chrome_docker_envs_default
                         | combine(chrome_docker_envs_custom) }}"

# Commands
chrome_docker_commands_default:
  - --no-sandbox
  - --disable-gpu
  - --disable-dev-shm-usage
  - --remote-debugging-address=0.0.0.0
  - --remote-debugging-port=9222
  - --hide-scrollbars
chrome_docker_commands_custom: []
chrome_docker_commands: "{{ chrome_docker_commands_default
                             + chrome_docker_commands_custom }}"

# Volumes
chrome_docker_volumes_default: []
chrome_docker_volumes_custom: []
chrome_docker_volumes: "{{ chrome_docker_volumes_default
                            + chrome_docker_volumes_custom }}"

# Devices
chrome_docker_devices_default: []
chrome_docker_devices_custom: []
chrome_docker_devices: "{{ chrome_docker_devices_default
                            + chrome_docker_devices_custom }}"

# Hosts
chrome_docker_hosts_default: {}
chrome_docker_hosts_custom: {}
chrome_docker_hosts: "{{ docker_hosts_common
                          | combine(chrome_docker_hosts_default)
                          | combine(chrome_docker_hosts_custom) }}"

# Labels
chrome_docker_labels_default: {}
chrome_docker_labels_custom: {}
chrome_docker_labels: "{{ docker_labels_common
                           | combine(chrome_docker_labels_default)
                           | combine(chrome_docker_labels_custom) }}"

# Hostname
chrome_docker_hostname: "{{ chrome_name }}"

# Networks
chrome_docker_networks_alias: "{{ chrome_name }}"
chrome_docker_networks_default: []
chrome_docker_networks_custom: []
chrome_docker_networks: "{{ docker_networks_common
                             + chrome_docker_networks_default
                             + chrome_docker_networks_custom }}"

# Capabilities
chrome_docker_capabilities_default: []
chrome_docker_capabilities_custom: []
chrome_docker_capabilities: "{{ chrome_docker_capabilities_default
                                 + chrome_docker_capabilities_custom }}"

# Security Opts
chrome_docker_security_opts_default: []
chrome_docker_security_opts_custom: []
chrome_docker_security_opts: "{{ chrome_docker_security_opts_default
                                  + chrome_docker_security_opts_custom }}"

# Restart Policy
chrome_docker_restart_policy: unless-stopped

# State
chrome_docker_state: started
