#########################################################################
# Title:            Sandbox: Vaultwarden                                #
# Author(s):        Kalroth, RXWatcher, TABLE                           #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: "Check if '{{ vaultwarden_paths_config_location | basename }}' exists"
  stat:
    path: "{{ vaultwarden_paths_config_location }}"
  register: vaultwarden_env

- name: Settings | New `{{ vaultwarden_paths_config_location | basename }}` tasks
  block:

    - name: "Generate Admin token"
      shell: /usr/bin/openssl rand -base64 48
      register: admin_token

    - name: "Import '{{ vaultwarden_paths_config_location | basename }}' if it doesnt exist"
      template:
        src: vaultwarden_env.j2
        dest: "{{ vaultwarden_paths_config_location }}"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0775

  when: not vaultwarden_env.stat.exists

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
