##########################################################################
# Title:         Sandbox: Wizarr | Default Variables                     #
# Author(s):     markschrik                                              #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

wizarr_instances: ["wizarr"]

################################
# Paths
################################

wizarr_role_paths_folder: "{{ wizarr_name }}"
wizarr_role_paths_location: "{{ server_appdata_path }}/{{ wizarr_role_paths_folder }}"
wizarr_role_paths_folders_list:
  - "{{ wizarr_role_paths_location }}"

################################
# Web
################################

wizarr_role_web_subdomain: "{{ wizarr_name }}"
wizarr_role_web_domain: "{{ user.domain }}"
wizarr_role_web_port: "5690"
wizarr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='wizarr') + '.' + lookup('role_var', '_web_domain', role='wizarr')
                      if (lookup('role_var', '_web_subdomain', role='wizarr') | length > 0)
                      else lookup('role_var', '_web_domain', role='wizarr')) }}"

################################
# DNS
################################

wizarr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='wizarr') }}"
wizarr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='wizarr') }}"
wizarr_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

wizarr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
wizarr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
wizarr_role_traefik_middleware_custom: ""
wizarr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
wizarr_role_traefik_enabled: true
wizarr_role_traefik_api_enabled: true
wizarr_role_traefik_api_endpoint: "PathPrefix(`/join`) || PathPrefix(`/j`) || PathPrefix(`/static`) || PathPrefix(`/setup`) || PathPrefix(`/wizard`) || PathPrefix(`/image-proxy`) || PathPrefix(`/cinema-posters`) || PathPrefix(`/invitation`)"

################################
# Docker
################################

# Container
wizarr_role_docker_container: "{{ wizarr_name }}"

# Image
wizarr_role_docker_image_pull: true
wizarr_role_docker_image_repo: "ghcr.io/wizarrrr/wizarr"
wizarr_role_docker_image_tag: "latest"
wizarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='wizarr') }}:{{ lookup('role_var', '_docker_image_tag', role='wizarr') }}"

# Envs
wizarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  DISABLE_BUILTIN_AUTH: "{{ 'true' if (lookup('role_var', '_traefik_sso_middleware', role='wizarr') | length > 0) else 'false' }}"
wizarr_role_docker_envs_custom: {}
wizarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='wizarr')
                             | combine(lookup('role_var', '_docker_envs_custom', role='wizarr')) }}"

# Volumes
wizarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='wizarr') }}:/data"
wizarr_role_docker_volumes_custom: []
wizarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='wizarr')
                                + lookup('role_var', '_docker_volumes_custom', role='wizarr') }}"

# Hostname
wizarr_role_docker_hostname: "{{ wizarr_name }}"

# Networks
wizarr_role_docker_networks_alias: "{{ wizarr_name }}"
wizarr_role_docker_networks_default: []
wizarr_role_docker_networks_custom: []
wizarr_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='wizarr')
                                 + lookup('role_var', '_docker_networks_custom', role='wizarr') }}"

# Restart Policy
wizarr_role_docker_restart_policy: unless-stopped

# State
wizarr_role_docker_state: started
