#########################################################################
# Title:            Sandbox: docspell                                   #
# Author(s):        JigSawFr                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# URL:              https://github.com/eikek/docspell                   #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check if db folder exists
  ansible.builtin.stat:
    path: "{{ server_appdata_path }}/{{ docspell_paths_folder }}/mariadb"
  register: stat_docspell_db_folder

- name: Remove legacy MariaDB Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ docspell_name }}_mariadb"

- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb
  vars:
    mariadb_instances: ["{{ docspell_name }}-mariadb"]
    mariadb_paths_folder: "{{ docspell_name }}"
    mariadb_paths_location: "{{ server_appdata_path }}/{{ docspell_paths_folder }}/mariadb"

- name: Create docspell database
  community.mysql.mysql_db:
    name: "{{ docspell_name }}"
    login_host: "{{ docspell_name }}-mariadb"
    login_user: "root"
    login_password: "{{ mariadb_docker_env_password }}"
    state: present

- name: Remove legacy Solr Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ docspell_name }}_solr"

- name: Solr Role
  ansible.builtin.include_role:
    name: solr
  vars:
    solr_name: "{{ docspell_name }}-solr"
    solr_docker_env_core_name: "{{ docspell_name }}"
    solr_paths_folder: "{{ docspell_name }}"
    solr_paths_location: "{{ server_appdata_path }}/{{ solr_paths_folder }}/solr"

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: "Generate Secret Key for registration"
  ansible.builtin.shell: "openssl rand -hex 20"
  register: docspell_register_key

- name: "Generate Secret Key for integration endpoint"
  ansible.builtin.shell: "openssl rand -hex 30"
  register: docspell_integration_key

- name: "Generate Secret Key for admin endpoint"
  ansible.builtin.shell: "openssl rand -hex 30"
  register: docspell_admin_key

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container (docspell-server)
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Remove legacy docspell-worker Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ docspell_name }}_joex"

- name: Create Docker container (docspell-worker)
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
  vars:
    docspell_docker_container: "{{ docspell_name }}-joex"
    docspell_docker_image: "docspell/joex:latest"
    docspell_web_port: "7878"
    docspell_docker_envs:
      TZ: "{{ tz }}"
      DOCSPELL_JOEX_APP__ID: "joex"
      DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME: "joex"
      DOCSPELL_JOEX_SCHEDULER_NAME: "joex"
      DOCSPELL_JOEX_BASE__URL: "http://{{ docspell_docker_container }}:{{ docspell_web_port }}"
      DOCSPELL_JOEX_BIND_ADDRESS: "0.0.0.0"
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL: "http://{{ docspell_name }}-solr:{{ solr_docker_env_port }}/solr/{{ docspell_name }}"
      DOCSPELL_JOEX_JDBC_PASSWORD: "{{ mariadb_docker_env_password }}"
      DOCSPELL_JOEX_JDBC_URL: "jdbc:mariadb://{{ docspell_name }}-mariadb:3306/{{ docspell_name }}"
      DOCSPELL_JOEX_JDBC_USER: "root"
      DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER: "docker,trivial"
      DOCSPELL_JOEX_CONVERT_HTML__CONVERTER: "weasyprint"
    docspell_docker_labels: "{{ omit }}"
    docspell_docker_volumes:
      - /tmp:/tmp
