##########################################################################
# Title:            Sandbox: plexshare | Default Variables               #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

plexshare_name: plexshare

################################
# Paths
################################

plexshare_role_paths_folder: "{{ plexshare_name }}"
plexshare_role_paths_location: "{{ server_appdata_path }}/{{ plexshare_role_paths_folder }}"
plexshare_role_paths_folders_list:
  - "{{ plexshare_role_paths_location }}"

################################
# Web
################################

plexshare_role_web_subdomain: "{{ plexshare_name }}"
plexshare_role_web_domain: "{{ user.domain }}"
plexshare_role_web_port: "80"
plexshare_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='plexshare') + '.' + lookup('role_var', '_web_domain', role='plexshare')
                         if (lookup('role_var', '_web_subdomain', role='plexshare') | length > 0)
                         else lookup('role_var', '_web_domain', role='plexshare')) }}"

################################
# DNS
################################

plexshare_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='plexshare') }}"
plexshare_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='plexshare') }}"
plexshare_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

plexshare_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
plexshare_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
plexshare_role_traefik_middleware_custom: ""
plexshare_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
plexshare_role_traefik_enabled: true
plexshare_role_traefik_api_enabled: false
plexshare_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
plexshare_role_docker_container: "{{ plexshare_name }}"

# Image
plexshare_role_docker_image_pull: true
plexshare_role_docker_image_tag: "latest"
plexshare_role_docker_image_repo: "chewbaka/plexshare"
plexshare_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='plexshare') }}:{{ lookup('role_var', '_docker_image_tag', role='plexshare') }}"

# Envs
plexshare_role_docker_envs_default:
  TZ: "{{ tz }}"
  WEB_DOCUMENT_ROOT: "/app/public"
  WEB_DOCUMENT_INDEX: "index.php"
  LOG_STDOUT: "./var/log/plexshare.stdout.log"
  LOG_STDERR: "./var/log/plexshare.stderr.log"
  PHP_POST_MAX_SIZE: "20M"
  PHP_MEMORY_LIMIT: "521M"
  PHP_MAX_EXECUTION_TIME: "300"
  PHP_DATE_TIMEZONE: "{{ tz }}"
  COMPOSER_VERSION: "1"
  BASE_URL: "{{ lookup('role_var', '_web_url', role='plexshare') }}/"
plexshare_role_docker_envs_custom: {}
plexshare_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='plexshare')
                                | combine(lookup('role_var', '_docker_envs_custom', role='plexshare')) }}"

# Hostname
plexshare_role_docker_hostname: "{{ plexshare_name }}"

# Networks
plexshare_role_docker_networks_alias: "{{ plexshare_name }}"
plexshare_role_docker_networks_default: []
plexshare_role_docker_networks_custom: []
plexshare_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='plexshare')
                                    + lookup('role_var', '_docker_networks_custom', role='plexshare') }}"

# Restart Policy
plexshare_role_docker_restart_policy: unless-stopped

# State
plexshare_role_docker_state: started

# Dependencies
plexshare_role_depends_on: "{{ plexshare_name }}-mariadb"
plexshare_role_depends_on_delay: "0"
plexshare_role_depends_on_healthchecks: "false"
