#########################################################################
# Title:            Sandbox: Zigbee2mqtt                                #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

zigbee2mqtt_name: zigbee2mqtt

################################
# Paths
################################

zigbee2mqtt_role_paths_folder: "{{ zigbee2mqtt_role_name }}"
zigbee2mqtt_role_paths_location: "{{ server_appdata_path }}/{{ zigbee2mqtt_role_paths_folder }}"
zigbee2mqtt_role_config_location: "{{ zigbee2mqtt_role_paths_location }}/configuration.yaml"
zigbee2mqtt_role_mqtt_config_location: "{{ server_appdata_path }}/mqtt/config/mosquitto.conf"
zigbee2mqtt_role_paths_folders_list:
  - "{{ zigbee2mqtt_role_paths_location }}"

################################
# Web
################################

zigbee2mqtt_role_web_subdomain: "{{ zigbee2mqtt_role_name }}"
zigbee2mqtt_role_web_domain: "{{ user.domain }}"
zigbee2mqtt_role_web_port: "8080"
zigbee2mqtt_role_web_url: "{{ 'https://' + (zigbee2mqtt_role_web_subdomain + '.' + zigbee2mqtt_role_web_domain
                      if (zigbee2mqtt_role_web_subdomain | length > 0)
                      else zigbee2mqtt_role_web_domain) }}"

################################
# DNS
################################

zigbee2mqtt_role_dns_record: "{{ zigbee2mqtt_role_web_subdomain }}"
zigbee2mqtt_role_dns_zone: "{{ zigbee2mqtt_role_web_domain }}"
zigbee2mqtt_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

zigbee2mqtt_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
zigbee2mqtt_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
zigbee2mqtt_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
zigbee2mqtt_role_traefik_middleware_custom: ""
zigbee2mqtt_role_traefik_enabled: true
zigbee2mqtt_role_traefik_api_enabled: false
zigbee2mqtt_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
zigbee2mqtt_role_docker_container: "{{ zigbee2mqtt_role_name }}"

# Image
zigbee2mqtt_role_docker_image_pull: true
zigbee2mqtt_role_docker_image_tag: "latest"
zigbee2mqtt_role_docker_image: "koenkk/zigbee2mqtt_role:{{ zigbee2mqtt_role_docker_image_tag }}"

# Ports
zigbee2mqtt_role_docker_ports_defaults:
  - "{{ zigbee2mqtt_role_web_port }}"
zigbee2mqtt_role_docker_ports_custom: []
zigbee2mqtt_role_docker_ports: "{{ zigbee2mqtt_role_docker_ports_defaults
                              + zigbee2mqtt_role_docker_ports_custom
                           if (not reverse_proxy_is_enabled)
                           else zigbee2mqtt_role_docker_ports_custom }}"

# Envs
zigbee2mqtt_role_docker_envs_default:
  TZ: "{{ tz }}"
zigbee2mqtt_role_docker_envs_custom: {}
zigbee2mqtt_role_docker_envs: "{{ zigbee2mqtt_role_docker_envs_default
                             | combine(zigbee2mqtt_role_docker_envs_custom) }}"

# Commands
zigbee2mqtt_role_docker_commands_default: []
zigbee2mqtt_role_docker_commands_custom: []
zigbee2mqtt_role_docker_commands: "{{ zigbee2mqtt_role_docker_commands_default
                                 + zigbee2mqtt_role_docker_commands_custom }}"

# Volumes
zigbee2mqtt_role_docker_volumes_default:
  - "{{ zigbee2mqtt_role_paths_location }}:/app/data"
  - "/run/udev:/run/udev:ro"
zigbee2mqtt_role_docker_volumes_custom: []
zigbee2mqtt_role_docker_volumes: "{{ zigbee2mqtt_role_docker_volumes_default
                                + zigbee2mqtt_role_docker_volumes_custom }}"

# Devices
zigbee2mqtt_role_docker_devices_default:
  - "/dev/ttyUSB0:/dev/ttyUSB0"
zigbee2mqtt_role_docker_devices_custom: []
zigbee2mqtt_role_docker_devices: "{{ zigbee2mqtt_role_docker_devices_default
                                + zigbee2mqtt_role_docker_devices_custom }}"

# Hosts
zigbee2mqtt_role_docker_hosts_default: []
zigbee2mqtt_role_docker_hosts_custom: []
zigbee2mqtt_role_docker_hosts: "{{ docker_hosts_common
                              | combine(zigbee2mqtt_role_docker_hosts_default)
                              | combine(zigbee2mqtt_role_docker_hosts_custom) }}"

# Labels
zigbee2mqtt_role_docker_labels_default: {}
zigbee2mqtt_role_docker_labels_custom: {}
zigbee2mqtt_role_docker_labels: "{{ docker_labels_common
                               | combine(zigbee2mqtt_role_docker_labels_default)
                               | combine(zigbee2mqtt_role_docker_labels_custom) }}"

# Hostname
zigbee2mqtt_role_docker_hostname: "{{ zigbee2mqtt_role_name }}"

# Networks
zigbee2mqtt_role_docker_networks_alias: "{{ zigbee2mqtt_role_name }}"
zigbee2mqtt_role_docker_networks_default: []
zigbee2mqtt_role_docker_networks_custom: []
zigbee2mqtt_role_docker_networks: "{{ docker_networks_common
                                 + zigbee2mqtt_role_docker_networks_default
                                 + zigbee2mqtt_role_docker_networks_custom }}"

# Capabilities
zigbee2mqtt_role_docker_capabilities_default: []
zigbee2mqtt_role_docker_capabilities_custom: []
zigbee2mqtt_role_docker_capabilities: "{{ zigbee2mqtt_role_docker_capabilities_default
                                     + zigbee2mqtt_role_docker_capabilities_custom }}"

# Security Opts
zigbee2mqtt_role_docker_security_opts_default: []
zigbee2mqtt_role_docker_security_opts_custom: []
zigbee2mqtt_role_docker_security_opts: "{{ zigbee2mqtt_role_docker_security_opts_default
                                      + zigbee2mqtt_role_docker_security_opts_custom }}"

# Restart Policy
zigbee2mqtt_role_docker_restart_policy: unless-stopped

# State
zigbee2mqtt_role_docker_state: started

# User
zigbee2mqtt_role_docker_user: "{{ uid }}:{{ gid }}"

zigbee2mqtt_role_docker_groups:
  - "dialout"
