#########################################################################
# Title:            Sandbox: Zigbee2mqtt                                #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

zigbee2mqtt_name: zigbee2mqtt

################################
# Paths
################################

zigbee2mqtt_role_paths_folder: "{{ zigbee2mqtt_name }}"
zigbee2mqtt_role_paths_location: "{{ server_appdata_path }}/{{ zigbee2mqtt_role_paths_folder }}"
zigbee2mqtt_role_config_location: "{{ zigbee2mqtt_role_paths_location }}/configuration.yaml"
zigbee2mqtt_role_mqtt_config_location: "{{ server_appdata_path }}/mqtt/config/mosquitto.conf"
zigbee2mqtt_role_paths_folders_list:
  - "{{ zigbee2mqtt_role_paths_location }}"

################################
# Web
################################

zigbee2mqtt_role_web_subdomain: "{{ zigbee2mqtt_name }}"
zigbee2mqtt_role_web_domain: "{{ user.domain }}"
zigbee2mqtt_role_web_port: "8080"
zigbee2mqtt_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='zigbee2mqtt') + '.' + lookup('role_var', '_web_domain', role='zigbee2mqtt')
                           if (lookup('role_var', '_web_subdomain', role='zigbee2mqtt') | length > 0)
                           else lookup('role_var', '_web_domain', role='zigbee2mqtt')) }}"

################################
# DNS
################################

zigbee2mqtt_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='zigbee2mqtt') }}"
zigbee2mqtt_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='zigbee2mqtt') }}"
zigbee2mqtt_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

zigbee2mqtt_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
zigbee2mqtt_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
zigbee2mqtt_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
zigbee2mqtt_role_traefik_middleware_custom: ""
zigbee2mqtt_role_traefik_enabled: true
zigbee2mqtt_role_traefik_api_enabled: false
zigbee2mqtt_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
zigbee2mqtt_role_docker_container: "{{ zigbee2mqtt_name }}"

# Image
zigbee2mqtt_role_docker_image_pull: true
zigbee2mqtt_role_docker_image_repo: "ghcr.io/koenkk/zigbee2mqtt"
zigbee2mqtt_role_docker_image_tag: "latest"
zigbee2mqtt_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='zigbee2mqtt') }}:{{ lookup('role_var', '_docker_image_tag', role='zigbee2mqtt') }}"

# Envs
zigbee2mqtt_role_docker_envs_default:
  TZ: "{{ tz }}"
zigbee2mqtt_role_docker_envs_custom: {}
zigbee2mqtt_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='zigbee2mqtt')
                                  | combine(lookup('role_var', '_docker_envs_custom', role='zigbee2mqtt')) }}"

# Volumes
zigbee2mqtt_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='zigbee2mqtt') }}:/app/data"
  - "/run/udev:/run/udev:ro"
zigbee2mqtt_role_docker_volumes_custom: []
zigbee2mqtt_role_docker_volumes: "{{ zigbee2mqtt_role_docker_volumes_default
                                     + zigbee2mqtt_role_docker_volumes_custom }}"

# Devices
zigbee2mqtt_role_docker_devices_default:
  - "/dev/ttyUSB0:/dev/ttyUSB0"
zigbee2mqtt_role_docker_devices_custom: []
zigbee2mqtt_role_docker_devices: "{{ zigbee2mqtt_role_docker_devices_default
                                     + zigbee2mqtt_role_docker_devices_custom }}"

# Hostname
zigbee2mqtt_role_docker_hostname: "{{ zigbee2mqtt_name }}"

# Networks
zigbee2mqtt_role_docker_networks_alias: "{{ zigbee2mqtt_name }}"
zigbee2mqtt_role_docker_networks_default: []
zigbee2mqtt_role_docker_networks_custom: []
zigbee2mqtt_role_docker_networks: "{{ docker_networks_common
                                      + lookup('role_var', '_docker_networks_default', role='zigbee2mqtt')
                                      + lookup('role_var', '_docker_networks_custom', role='zigbee2mqtt') }}"

# User
zigbee2mqtt_role_docker_user: "{{ uid }}:{{ gid }}"

# Groups

zigbee2mqtt_role_docker_groups:
  - "dialout"

# Restart Policy
zigbee2mqtt_role_docker_restart_policy: unless-stopped

# State
zigbee2mqtt_role_docker_state: started
