#########################################################################
# Title:            Sandbox: comixed                                    #
# Author(s):        theotocopulitos, kowalski                           #
# URL:              https://github.com/saltyorg/Sandbox                 #
# Docker Image(s):  comixed/comixed                                     #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

comixed_name: comixed

################################
# Paths
################################

comixed_paths_folder: "{{ comixed_name }}"
comixed_paths_location: "{{ server_appdata_path }}/{{ comixed_paths_folder }}"
comixed_paths_folders_list:
  - "{{ comixed_paths_location }}"
  - "/mnt/local/Media/Comics"

################################
# Web
################################

comixed_web_subdomain: "{{ comixed_name }}"
comixed_web_domain: "{{ user.domain }}"
comixed_web_port: "7171"
comixed_web_url: "{{ 'https://' + (comixed_web_subdomain + '.' + comixed_web_domain
                  if (comixed_web_subdomain | length > 0)
                  else comixed_web_domain) }}"

################################
# DNS
################################

comixed_dns_record: "{{ comixed_web_subdomain }}"
comixed_dns_zone: "{{ comixed_web_domain }}"
comixed_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

comixed_traefik_sso_middleware: ""
comixed_traefik_middleware_default: "{{ traefik_default_middleware }}"
comixed_traefik_middleware_custom: ""
comixed_traefik_certresolver: "{{ traefik_default_certresolver }}"
comixed_traefik_enabled: true

################################
# Docker
################################

# Container
comixed_docker_container: "{{ comixed_name }}"

# Image
comixed_docker_image_pull: true
comixed_docker_image_tag: "latest"
comixed_docker_image: "comixed/comixed:{{ comixed_docker_image_tag }}"

# Ports
comixed_docker_ports_defaults: []
comixed_docker_ports_custom: []
comixed_docker_ports: "{{ comixed_docker_ports_defaults
                          + comixed_docker_ports_custom }}"

# Envs
comixed_docker_envs_default: {}
comixed_docker_envs_custom: {}
comixed_docker_envs: "{{ comixed_docker_envs_default
                         | combine(comixed_docker_envs_custom) }}"

# Commands
comixed_docker_commands_default: []
comixed_docker_commands_custom: []
comixed_docker_commands: "{{ comixed_docker_commands_default
                             + comixed_docker_commands_custom }}"

# Volumes
comixed_docker_volumes_default:
  - "{{ comixed_paths_location }}:/root/.comixed"
  - "/mnt/unionfs/Media/Comics:/comic_dir"
comixed_docker_volumes_custom: []
comixed_docker_volumes: "{{ comixed_docker_volumes_default
                            + comixed_docker_volumes_custom }}"

# Devices
comixed_docker_devices_default: []
comixed_docker_devices_custom: []
comixed_docker_devices: "{{ comixed_docker_devices_default
                            + comixed_docker_devices_custom }}"

# Hosts
comixed_docker_hosts_default: {}
comixed_docker_hosts_custom: {}
comixed_docker_hosts: "{{ docker_hosts_common
                          | combine(comixed_docker_hosts_default)
                          | combine(comixed_docker_hosts_custom) }}"

# Labels
comixed_docker_labels_default: {}
comixed_docker_labels_custom: {}
comixed_docker_labels: "{{ docker_labels_common
                           | combine(comixed_docker_labels_default)
                           | combine(comixed_docker_labels_custom) }}"

# Hostname
comixed_docker_hostname: "{{ comixed_name }}"

# Networks
comixed_docker_networks_alias: "{{ comixed_name }}"
comixed_docker_networks_default: []
comixed_docker_networks_custom: []
comixed_docker_networks: "{{ docker_networks_common
                             + comixed_docker_networks_default
                             + comixed_docker_networks_custom }}"

# Capabilities
comixed_docker_capabilities_default: []
comixed_docker_capabilities_custom: []
comixed_docker_capabilities: "{{ comixed_docker_capabilities_default
                                 + comixed_docker_capabilities_custom }}"

# Security Opts
comixed_docker_security_opts_default: []
comixed_docker_security_opts_custom: []
comixed_docker_security_opts: "{{ comixed_docker_security_opts_default
                                  + comixed_docker_security_opts_custom }}"

# Restart Policy
comixed_docker_restart_policy: unless-stopped

# State
comixed_docker_state: started
