#########################################################################
# Title:            Sandbox: Coder                                      #
# Author(s):        astroMD, kowalski                                   #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

coder_name: coder

################################
# Paths
################################

coder_paths_folder: "{{ coder_name }}"
coder_paths_location: "{{ server_appdata_path }}/{{ coder_paths_folder }}"
coder_paths_folders_list:
  - "{{ coder_paths_location }}"
  - "{{ coder_paths_location }}/project"
  - "{{ coder_paths_location }}/.config"
  - "{{ coder_paths_location }}/.local"

################################
# Web
################################

coder_web_subdomain: "{{ coder_name }}"
coder_web_domain: "{{ user.domain }}"
coder_web_port: "8080"
coder_web_url: "{{ 'https://' + coder_web_subdomain + '.' + coder_web_domain }}"

################################
# DNS
################################

coder_dns_record: "{{ coder_web_subdomain }}"
coder_dns_zone: "{{ coder_web_domain }}"
coder_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

coder_traefik_middleware: "{{ traefik_default_middleware }}"
coder_traefik_certresolver: "{{ traefik_default_certresolver }}"
coder_traefik_enabled: true

################################
# Docker
################################

# Container
coder_docker_container: "{{ coder_name }}"

# Image
coder_docker_image_pull: true
coder_docker_image_tag: "latest"
coder_docker_image: "codercom/code-server:{{ coder_docker_image_tag }}"

# Ports
coder_docker_ports_defaults: []
coder_docker_ports_custom: []
coder_docker_ports: "{{ coder_docker_ports_defaults
                        + coder_docker_ports_custom }}"

# Envs
coder_docker_envs_default:
  UMASK: "002"
  TZ: "{{ tz }}"
  PASSWORD: "{{ user.pass }}"
  DOCKER_USER: "{{ user.name }}"
coder_docker_envs_custom: {}
coder_docker_envs: "{{ coder_docker_envs_default
                       | combine(coder_docker_envs_custom) }}"

# Commands
coder_docker_commands_default: []
coder_docker_commands_custom: []
coder_docker_commands: "{{ coder_docker_commands_default
                           + coder_docker_commands_custom }}"

# Volumes
coder_docker_volumes_default:
  - "{{ coder_paths_location }}/project:/home/coder/project"
  - "{{ coder_paths_location }}/.config:/home/coder/.config"
  - "{{ coder_paths_location }}/.local:/home/coder/.local"
  - "{{ server_appdata_path }}:/host_opt"
coder_docker_volumes_custom: []
coder_docker_volumes: "{{ coder_docker_volumes_default
                          + coder_docker_volumes_custom }}"

# Devices
coder_docker_devices_default: []
coder_docker_devices_custom: []
coder_docker_devices: "{{ coder_docker_devices_default
                          + coder_docker_devices_custom }}"

# Hosts
coder_docker_hosts_default: []
coder_docker_hosts_custom: []
coder_docker_hosts: "{{ docker_hosts_common
                        | combine(coder_docker_hosts_default)
                        | combine(coder_docker_hosts_custom) }}"

# Labels
coder_docker_labels_default: {}
coder_docker_labels_custom: {}
coder_docker_labels: "{{ docker_labels_common
                         | combine(coder_docker_labels_default)
                         | combine(coder_docker_labels_custom) }}"

# Hostname
coder_docker_hostname: "{{ coder_name }}"

# Networks
coder_docker_networks_alias: "{{ coder_name }}"
coder_docker_networks_default: []
coder_docker_networks_custom: []
coder_docker_networks: "{{ docker_networks_common
                           + coder_docker_networks_default
                           + coder_docker_networks_custom }}"

# Capabilities
coder_docker_capabilities_default: []
coder_docker_capabilities_custom: []
coder_docker_capabilities: "{{ coder_docker_capabilities_default
                               + coder_docker_capabilities_custom }}"

# Security Opts
coder_docker_security_opts_default: []
coder_docker_security_opts_custom: []
coder_docker_security_opts: "{{ coder_docker_security_opts_default
                                + coder_docker_security_opts_custom }}"

# Restart Policy
coder_docker_restart_policy: unless-stopped

# State
coder_docker_state: started

# User
coder_docker_user: "{{ uid }}:{{ gid }}"
