##########################################################################
# Title:            Sandbox: Navidrome                                   #
# Author(s):        finch, kowalski                                      #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

navidrome_name: navidrome

################################
# Paths
################################

navidrome_role_paths_folder: "{{ navidrome_name }}"
navidrome_role_paths_location: "{{ server_appdata_path }}/{{ navidrome_role_paths_folder }}"
navidrome_role_paths_folders_list:
  - "{{ navidrome_role_paths_location }}"

################################
# Web
################################

navidrome_role_web_subdomain: "{{ navidrome_name }}"
navidrome_role_web_domain: "{{ user.domain }}"
navidrome_role_web_port: "4533"
navidrome_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='navidrome') + '.' + lookup('role_var', '_web_domain', role='navidrome')
                         if (lookup('role_var', '_web_subdomain', role='navidrome') | length > 0)
                         else lookup('role_var', '_web_domain', role='navidrome')) }}"

################################
# DNS
################################

navidrome_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='navidrome') }}"
navidrome_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='navidrome') }}"
navidrome_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

navidrome_role_traefik_sso_middleware: ""
navidrome_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
navidrome_role_traefik_middleware_custom: ""
navidrome_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
navidrome_role_traefik_enabled: true
navidrome_role_traefik_api_enabled: false
navidrome_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
navidrome_role_docker_container: "{{ navidrome_name }}"

# Image
navidrome_role_docker_image_pull: true
navidrome_role_docker_image_tag: "latest"
navidrome_role_docker_image_repo: "deluan/navidrome"
navidrome_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='navidrome') }}:{{ lookup('role_var', '_docker_image_tag', role='navidrome') }}"

# Volumes
navidrome_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='navidrome') }}:/data"
  - "/mnt/unionfs/Media/Music:/music"
navidrome_role_docker_volumes_custom: []
navidrome_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='navidrome')
                                   + lookup('role_var', '_docker_volumes_custom', role='navidrome') }}"

# Hostname
navidrome_role_docker_hostname: "{{ navidrome_name }}"

# Networks
navidrome_role_docker_networks_alias: "{{ navidrome_name }}"
navidrome_role_docker_networks_default: []
navidrome_role_docker_networks_custom: []
navidrome_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='navidrome')
                                    + lookup('role_var', '_docker_networks_custom', role='navidrome') }}"

# Restart Policy
navidrome_role_docker_restart_policy: unless-stopped

# State
navidrome_role_docker_state: started

# User
navidrome_role_docker_user: "{{ uid }}:{{ gid }}"
