##########################################################################
# Title:            Sandbox: solr | Default Variables                    #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# URL:              https://github.com/apache/solr                       #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

solr_name: solr

################################
# Settings
################################

# solr_docker_env_password: "solr147"
solr_docker_env_port: "8983"
solr_docker_env_core_name: "{{ solr_name }}"

################################
# Paths
################################

solr_paths_folder: "{{ solr_name }}"
solr_paths_location: "{{ server_appdata_path }}/{{ solr_paths_folder }}"
solr_paths_folders_list:
  - "{{ solr_paths_location }}"

################################
# Docker
################################

# Container
solr_docker_container: "{{ solr_name }}"

# Image
solr_docker_image_pull: true
solr_docker_image_tag: "latest"
solr_docker_image: "solr:{{ solr_docker_image_tag }}"

# Ports
solr_docker_ports_defaults: []
solr_docker_ports_custom: []
solr_docker_ports: "{{ solr_docker_ports_defaults
                       + solr_docker_ports_custom }}"

# Envs
solr_docker_envs_default:
  TZ: "{{ tz }}"
  SOLR_HOST: "{{ solr_name }}"
  # SOLR_UID: "{{ uid }}"
  # SOLR_GID: "{{ gid }}"
solr_docker_envs_custom: {}
solr_docker_envs: "{{ solr_docker_envs_default
                      | combine(solr_docker_envs_custom) }}"

# Commands
solr_docker_commands_default:
  - "solr-precreate {{ solr_docker_env_core_name }}"
solr_docker_commands_custom: []
solr_docker_commands: "{{ solr_docker_commands_default
                          + solr_docker_commands_custom }}"

# Volumes
solr_docker_volumes_default: []
#  - "{{ solr_paths_location }}:/var/solr/data"
solr_docker_volumes_custom: []
solr_docker_volumes: "{{ solr_docker_volumes_default
                         + solr_docker_volumes_custom }}"

# Devices
solr_docker_devices_default: []
solr_docker_devices_custom: []
solr_docker_devices: "{{ solr_docker_devices_default
                         + solr_docker_devices_custom }}"

# Hosts
solr_docker_hosts_default: {}
solr_docker_hosts_custom: {}
solr_docker_hosts: "{{ docker_hosts_common
                       | combine(solr_docker_hosts_default)
                       | combine(solr_docker_hosts_custom) }}"

# Labels
solr_docker_labels_default: {}
solr_docker_labels_custom: {}
solr_docker_labels: "{{ docker_labels_common
                        | combine(solr_docker_labels_default)
                        | combine(solr_docker_labels_custom) }}"

# Hostname
solr_docker_hostname: "{{ solr_name }}"

# Networks
solr_docker_networks_alias: "{{ solr_name }}"
solr_docker_networks_default: []
solr_docker_networks_custom: []
solr_docker_networks: "{{ docker_networks_common
                          + solr_docker_networks_default
                          + solr_docker_networks_custom }}"

# Capabilities
solr_docker_capabilities_default: []
solr_docker_capabilities_custom: []
solr_docker_capabilities: "{{ solr_docker_capabilities_default
                              + solr_docker_capabilities_custom }}"

# Security Opts
solr_docker_security_opts_default: []
solr_docker_security_opts_custom: []
solr_docker_security_opts: "{{ solr_docker_security_opts_default
                               + solr_docker_security_opts_custom }}"

# Restart Policy
solr_docker_restart_policy: always

# State
solr_docker_state: started

# User
# solr_docker_user: "{{ uid }}:{{ gid }}"
