#########################################################################
# Title:         Saltbox: Beszel-Agent Role                             #
# Author(s):     f4bio                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# - name: Prompt for universal token
#   ansible.builtin.pause:
#     prompt: "Go to Beszel Hub at {{ beszel_hub_url }}/settings/tokens, activate and paste Universal token (e.g.: 'a68a9a0b-1337-1ee7-i33t-756df1b0e034')"
#   register: universal_token

# - name: Prompt user for agent token
#   ansible.builtin.pause:
#     prompt: "Go to your Beszel Hub ({{ beszel_hub_url }}), add new system and enter the token displayed (e.g., 'a68a9a0b-1337-1ee7-i33t-756df1b0e034')"
#   register: agent_token

# - name: Prompt user for agent key 
#   ansible.builtin.pause:
#     prompt: "...and the corresponding agent key (e.g., 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2YufokpaoKXT5mimcuu0JdfWadErOGAC6hn8+yB5D+')"
#   register: agent_key

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Reset Beszel-Agent directory
  ansible.builtin.file:
    path: "{{ beszel_agent_paths_location }}"
    state: absent
  when: ('beszel-reset' in ansible_run_tags)

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
