#########################################################################
# Title:         Saltbox: Beszel-Agent Role                             #
# Author(s):     f4bio                                                  #
# URL:           https://github.com/f4bio/Saltbox                       #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# - name: Prompt for universal token
#   ansible.builtin.pause:
#     prompt: "Go to your Beszel Hub, activate and paste \"Universal token\" (example: 'a68a9a0b-1337-1ee7-i33t-756df1b0e034')"
#   register: universal_token

- name: Prompt user for hub URL
  ansible.builtin.pause:
    prompt: "Paste Beszel Hub URL (for local connection use 'http://beszel:8090')"
  register: beszel_agent_hub_url

- name: Prompt user for listen port or socket
  ansible.builtin.pause:
    prompt: "Paste Beszel-Agent listen port or socket (for local connection use '/beszel_socket/beszel.sock')"
  register: beszel_agent_listen

- name: Prompt user for agent public key
  ansible.builtin.pause:
    prompt: "Go to your Beszel Hub, \"+Add System\" and paste the displayed \"Public Key\" (example: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2YufokpaoKXT5mimcuu0JdfWadErOGAC6hn8+yB5D+')"
  register: beszel_agent_public_key

- name: Prompt user for agent token
  ansible.builtin.pause:
    prompt: "...and the corresponding \"Token\" (example: 'a68a9a0b-1337-1ee7-i33t-756df1b0e034')"
  register: beszel_agent_token

- name: Prompt user for confirmation
  ansible.builtin.pause:
    prompt: "...and click \"Add system\". Press return to continue. Press Ctrl+C and then \"A\" to abort"

- name: "Save Beszel Agent \"Public Key\" and \"Token\" Saltbox facts"
  saltbox_facts:
    role: "beszel_agent"
    instance: "beszel_agent"
    keys:
      hub_url: "{{ beszel_agent_hub_url.user_input }}"
      listen: "{{ beszel_agent_listen.user_input }}"
      public_key: "{{ beszel_agent_public_key.user_input }}"
      token: "{{ beszel_agent_token.user_input }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  register: beszel_agent_saltbox_facts

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Reset Beszel-Agent directory
  ansible.builtin.file:
    path: "{{ beszel_agent_paths_location }}"
    state: absent
  when: ('beszel-reset' in ansible_run_tags)

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
