##########################################################################
# Title:            Sandbox: Apache TIKA | Default Variables             #
# Author(s):        JigSawFr                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tika_name: tika

################################
# Docker
################################

# Container
tika_docker_container: "{{ tika_name }}"

# Image
tika_docker_image_pull: true
tika_docker_image_tag: "latest"
tika_docker_image: "ghcr.io/paperless-ngx/tika:{{ tika_docker_image_tag }}"

# Ports
tika_docker_ports_defaults: []
tika_docker_ports_custom: []
tika_docker_ports: "{{ tika_docker_ports_defaults
                       + tika_docker_ports_custom }}"

# Envs
tika_docker_envs_default:
  TZ: "{{ tz }}"
tika_docker_envs_custom: {}
tika_docker_envs: "{{ tika_docker_envs_default
                      | combine(tika_docker_envs_custom) }}"

# Commands
tika_docker_commands_default: []
tika_docker_commands_custom: []
tika_docker_commands: "{{ tika_docker_commands_default
                          + tika_docker_commands_custom }}"

# Volumes
tika_docker_volumes_default: []
tika_docker_volumes_custom: []
tika_docker_volumes: "{{ tika_docker_volumes_default
                         + tika_docker_volumes_custom }}"

# Devices
tika_docker_devices_default: []
tika_docker_devices_custom: []
tika_docker_devices: "{{ tika_docker_devices_default
                         + tika_docker_devices_custom }}"

# Hosts
tika_docker_hosts_default: {}
tika_docker_hosts_custom: {}
tika_docker_hosts: "{{ docker_hosts_common
                       | combine(tika_docker_hosts_default)
                       | combine(tika_docker_hosts_custom) }}"

# Labels
tika_docker_labels_default: {}
tika_docker_labels_custom: {}
tika_docker_labels: "{{ docker_labels_common
                        | combine(tika_docker_labels_default)
                        | combine(tika_docker_labels_custom) }}"

# Hostname
tika_docker_hostname: "{{ tika_name }}"

# Networks
tika_docker_networks_alias: "{{ tika_name }}"
tika_docker_networks_default: []
tika_docker_networks_custom: []
tika_docker_networks: "{{ docker_networks_common
                          + tika_docker_networks_default
                          + tika_docker_networks_custom }}"

# Capabilities
tika_docker_capabilities_default: []
tika_docker_capabilities_custom: []
tika_docker_capabilities: "{{ tika_docker_capabilities_default
                              + tika_docker_capabilities_custom }}"

# Security Opts
tika_docker_security_opts_default: []
tika_docker_security_opts_custom: []
tika_docker_security_opts: "{{ tika_docker_security_opts_default
                               + tika_docker_security_opts_custom }}"

# Restart Policy
tika_docker_restart_policy: always

# State
tika_docker_state: started
