#########################################################################
# Title:            Sandbox: minecraft-bedrock                          #
# Author(s):        nickstarkloff                                       #
# URL:              https://github.com/saltyorg/Sandbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Add SRV record
  community.general.cloudflare_dns:
    zone: "{{ _dns_tasker_zone }}"
    record: "{{ lookup('vars', role_name + '_dns_record') }}"
    type: SRV
    proto: udp
    service: minecraft
    value: "{{ lookup('vars', role_name + '_dns_record') }}.{{ lookup('vars', role_name + '_dns_zone') }}"
    port: 19132
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
  when: cloudflare_is_enabled

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
