##########################################################################
# Title:         Sandbox: freshrss                                       #
# Author(s):     kxzaon, salty                                           #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

freshrss_name: freshrss

################################
# Paths
################################

freshrss_paths_folder: "{{ freshrss_name }}"
freshrss_paths_location: "{{ server_appdata_path }}/{{ freshrss_paths_folder }}"
freshrss_paths_folders_list:
  - "{{ freshrss_paths_location }}"

################################
# Web
################################

freshrss_web_subdomain: "{{ freshrss_name }}"
freshrss_web_domain: "{{ user.domain }}"
freshrss_web_port: "80"
freshrss_web_url: "{{ 'https://' + (freshrss_web_subdomain + '.' + freshrss_web_domain
                   if (freshrss_web_subdomain | length > 0)
                   else freshrss_web_domain) }}"

################################
# DNS
################################

freshrss_dns_record: "{{ freshrss_web_subdomain }}"
freshrss_dns_zone: "{{ freshrss_web_domain }}"
freshrss_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

freshrss_traefik_sso_middleware: ""
freshrss_traefik_middleware_default: "{{ traefik_default_middleware }}"
freshrss_traefik_middleware_custom: ""
freshrss_traefik_certresolver: "{{ traefik_default_certresolver }}"
freshrss_traefik_enabled: true
freshrss_traefik_api_enabled: false
freshrss_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
freshrss_docker_container: "{{ freshrss_name }}"

# Image
freshrss_docker_image_pull: true
freshrss_docker_image_tag: "amd64-latest"
freshrss_docker_image: "lscr.io/linuxserver/freshrss:{{ freshrss_docker_image_tag }}"

# Ports
freshrss_docker_ports_defaults: []
freshrss_docker_ports_custom: []
freshrss_docker_ports: "{{ freshrss_docker_ports_defaults
                           + freshrss_docker_ports_custom }}"

# Envs
freshrss_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
freshrss_docker_envs_custom: {}
freshrss_docker_envs: "{{ freshrss_docker_envs_default
                          | combine(freshrss_docker_envs_custom) }}"

# Commands
freshrss_docker_commands_default: []
freshrss_docker_commands_custom: []
freshrss_docker_commands: "{{ freshrss_docker_commands_default
                              + freshrss_docker_commands_custom }}"

# Volumes
freshrss_docker_volumes_default:
  - "{{ freshrss_paths_location }}:/config"
freshrss_docker_volumes_custom: []
freshrss_docker_volumes: "{{ freshrss_docker_volumes_default
                             + freshrss_docker_volumes_custom }}"

# Devices
freshrss_docker_devices_default: []
freshrss_docker_devices_custom: []
freshrss_docker_devices: "{{ freshrss_docker_devices_default
                             + freshrss_docker_devices_custom }}"

# Hosts
freshrss_docker_hosts_default: {}
freshrss_docker_hosts_custom: {}
freshrss_docker_hosts: "{{ docker_hosts_common
                           | combine(freshrss_docker_hosts_default)
                           | combine(freshrss_docker_hosts_custom) }}"

# Labels
freshrss_docker_labels_default: {}
freshrss_docker_labels_custom: {}
freshrss_docker_labels: "{{ docker_labels_common
                            | combine(freshrss_docker_labels_default)
                            | combine(freshrss_docker_labels_custom) }}"

# Hostname
freshrss_docker_hostname: "{{ freshrss_name }}"

# Networks
freshrss_docker_networks_alias: "{{ freshrss_name }}"
freshrss_docker_networks_default: []
freshrss_docker_networks_custom: []
freshrss_docker_networks: "{{ docker_networks_common
                              + freshrss_docker_networks_default
                              + freshrss_docker_networks_custom }}"

# Capabilities
freshrss_docker_capabilities_default: []
freshrss_docker_capabilities_custom: []
freshrss_docker_capabilities: "{{ freshrss_docker_capabilities_default
                                  + freshrss_docker_capabilities_custom }}"

# Security Opts
freshrss_docker_security_opts_default: []
freshrss_docker_security_opts_custom: []
freshrss_docker_security_opts: "{{ freshrss_docker_security_opts_default
                                   + freshrss_docker_security_opts_custom }}"

# Restart Policy
freshrss_docker_restart_policy: unless-stopped

# State
freshrss_docker_state: started
