#########################################################################
# Title:         Sandbox: SabThrottle  | Default Variables              #
# Author(s):     8a8al00ey                                              #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

sabthrottle_name: sabthrottle

################################
# Paths
################################

sabthrottle_paths_folder: "{{ sabthrottle_name }}"
sabthrottle_paths_location: "{{ server_appdata_path }}/{{ sabthrottle_paths_folder }}"
sabthrottle_paths_folders_list:
  - "{{ sabthrottle_paths_location }}"
sabthrottle_paths_config_location: "{{ sabthrottle_paths_location }}/config.json"

################################
# Docker
################################

# Container
sabthrottle_docker_container: "{{ sabthrottle_name }}"

# Image
sabthrottle_docker_image_pull: true
sabthrottle_docker_image_tag: "latest"
sabthrottle_docker_image: "8a8al00ey/sabthrottle:{{ sabthrottle_docker_image_tag }}"

# Ports
sabthrottle_docker_ports_defaults: []
sabthrottle_docker_ports_custom: []
sabthrottle_docker_ports: "{{ sabthrottle_docker_ports_defaults
                              + sabthrottle_docker_ports_custom }}"

# Envs
sabthrottle_docker_envs_default:
  TZ: "{{ tz }}"
sabthrottle_docker_envs_custom: {}
sabthrottle_docker_envs: "{{ sabthrottle_docker_envs_default
                             | combine(sabthrottle_docker_envs_custom) }}"

# Commands
sabthrottle_docker_commands_default: []
sabthrottle_docker_commands_custom: []
sabthrottle_docker_commands: "{{ sabthrottle_docker_commands_default
                                 + sabthrottle_docker_commands_custom }}"

# Volumes
sabthrottle_docker_volumes_default:
  - "{{ sabthrottle_paths_config_location }}:/sabthrottle/config.json:ro"
sabthrottle_docker_volumes_custom: []
sabthrottle_docker_volumes: "{{ sabthrottle_docker_volumes_default
                                + sabthrottle_docker_volumes_custom }}"

# Devices
sabthrottle_docker_devices_default: []
sabthrottle_docker_devices_custom: []
sabthrottle_docker_devices: "{{ sabthrottle_docker_devices_default
                                + sabthrottle_docker_devices_custom }}"

# Hosts
sabthrottle_docker_hosts_default: {}
sabthrottle_docker_hosts_custom: {}
sabthrottle_docker_hosts: "{{ docker_hosts_common
                              | combine(sabthrottle_docker_hosts_default)
                              | combine(sabthrottle_docker_hosts_custom) }}"

# Labels
sabthrottle_docker_labels_default: {}
sabthrottle_docker_labels_custom: {}
sabthrottle_docker_labels: "{{ docker_labels_common
                               | combine(sabthrottle_docker_labels_default)
                               | combine(sabthrottle_docker_labels_custom) }}"

# Hostname
sabthrottle_docker_hostname: "{{ sabthrottle_name }}"

# Networks
sabthrottle_docker_networks_alias: "{{ sabthrottle_name }}"
sabthrottle_docker_networks_default: []
sabthrottle_docker_networks_custom: []
sabthrottle_docker_networks: "{{ docker_networks_common
                                 + sabthrottle_docker_networks_default
                                 + sabthrottle_docker_networks_custom }}"

# Capabilities
sabthrottle_docker_capabilities_default: []
sabthrottle_docker_capabilities_custom: []
sabthrottle_docker_capabilities: "{{ sabthrottle_docker_capabilities_default
                                     + sabthrottle_docker_capabilities_custom }}"

# Security Opts
sabthrottle_docker_security_opts_default: []
sabthrottle_docker_security_opts_custom: []
sabthrottle_docker_security_opts: "{{ sabthrottle_docker_security_opts_default
                                      + sabthrottle_docker_security_opts_custom }}"

# Restart Policy
sabthrottle_docker_restart_policy: unless-stopped

# State
sabthrottle_docker_state: started
