#########################################################################
# Title:            Sandbox: Glances                                    #
# Author(s):        Satz, kowalski                                      #
# URL:              https://github.com/saltyorg/Sandbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Docker Socket Proxy
################################

glances_docker_socket_proxy_envs:
  CONTAINERS: "1"
  IMAGES: "1"

################################
# Basics
################################

glances_web_name: glances

################################
# Paths
################################

glances_web_paths_folder: "{{ glances_web_name }}"
glances_web_paths_location: "{{ server_appdata_path }}/{{ glances_web_paths_folder }}"
glances_web_paths_folders_list:
  - "{{ glances_web_paths_location }}"
  - "{{ glances_web_paths_location }}/config"
glances_web_paths_config_location: "{{ glances_web_paths_location }}/config/glances.conf"

################################
# Web
################################

glances_web_web_subdomain: "{{ glances_web_name }}"
glances_web_web_domain: "{{ user.domain }}"
glances_web_web_port: "61208"
glances_web_web_url: "{{ 'https://' + (glances_web_web_subdomain + '.' + glances_web_web_domain
                      if (glances_web_web_subdomain | length > 0)
                      else glances_web_web_domain) }}"

################################
# DNS
################################

glances_web_dns_record: "{{ glances_web_web_subdomain }}"
glances_web_dns_zone: "{{ glances_web_web_domain }}"
glances_web_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

glances_web_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
glances_web_traefik_middleware_default: "{{ traefik_default_middleware }}"
glances_web_traefik_middleware_custom: ""
glances_web_traefik_certresolver: "{{ traefik_default_certresolver }}"
glances_web_traefik_enabled: true
glances_web_traefik_api_enabled: false
glances_web_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
glances_web_docker_container: "{{ glances_web_name }}"

# Image
glances_web_docker_image_pull: true
glances_web_docker_image_tag: "latest-full"
glances_web_docker_image: "nicolargo/glances:{{ glances_web_docker_image_tag }}"

# Ports
glances_web_docker_ports_defaults: []
glances_web_docker_ports_custom: []
glances_web_docker_ports: "{{ glances_web_docker_ports_defaults
                              + glances_web_docker_ports_custom }}"

# Envs
glances_web_docker_envs_default:
  UID: "{{ uid }}"
  GID: "{{ gid }}"
  TZ: "{{ tz }}"
  GLANCES_OPT: "-w --bind 172.19.0.1"
  DOCKER_HOST: "tcp://{{ glances_web_name }}-docker-socket-proxy:2375"
glances_web_docker_envs_custom: {}
glances_web_docker_envs: "{{ glances_web_docker_envs_default
                             | combine(glances_web_docker_envs_custom) }}"

# Commands
glances_web_docker_commands_default: []
glances_web_docker_commands_custom: []
glances_web_docker_commands: "{{ glances_web_docker_commands_default
                                 + glances_web_docker_commands_custom }}"

# Volumes
glances_web_docker_volumes_default:
  - "{{ glances_web_paths_config_location }}:/glances/conf/glances.conf:rw"
glances_web_docker_volumes_custom: []
glances_web_docker_volumes: "{{ glances_web_docker_volumes_default
                                + glances_web_docker_volumes_custom }}"

# Devices
glances_web_docker_devices_default: []
glances_web_docker_devices_custom: []
glances_web_docker_devices: "{{ glances_web_docker_devices_default
                                + glances_web_docker_devices_custom }}"

# Hosts
glances_web_docker_hosts_default: {}
glances_web_docker_hosts_custom: {}
glances_web_docker_hosts: "{{ docker_hosts_common
                              | combine(glances_web_docker_hosts_default)
                              | combine(glances_web_docker_hosts_custom) }}"

# Labels
glances_web_docker_labels_default: {}
glances_web_docker_labels_custom: {}
glances_web_docker_labels: "{{ docker_labels_common
                               | combine(glances_web_docker_labels_default)
                               | combine(glances_web_docker_labels_custom) }}"

# Hostname
glances_web_docker_hostname: "{{ glances_web_name }}"

# Networks
glances_web_docker_network_mode: "host"

# Capabilities
glances_web_docker_capabilities_default: []
glances_web_docker_capabilities_custom: []
glances_web_docker_capabilities: "{{ glances_web_docker_capabilities_default
                                     + glances_web_docker_capabilities_custom }}"

# Security Opts
glances_web_docker_security_opts_default: []
glances_web_docker_security_opts_custom: []
glances_web_docker_security_opts: "{{ glances_web_docker_security_opts_default
                                      + glances_web_docker_security_opts_custom }}"

# Restart Policy
glances_web_docker_restart_policy: unless-stopped

# State
glances_web_docker_state: started

# Force Kill
glances_web_docker_force_kill: yes

# PID Mode
glances_web_docker_pid_mode: host

# Dependencies
glances_web_depends_on: "{{ glances_web_name }}-docker-socket-proxy"
glances_web_depends_on_delay: "0"
glances_web_depends_on_healthchecks: "false"
