##########################################################################
# Title:            Sandbox: InfluxDB2                                   #
# Author(s):        desimaniac, kowalski, owine                          #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

influxdb2_instances: ["influxdb2"]

################################
# Paths
################################

influxdb2_role_paths_folder: "{{ influxdb2_name }}"
influxdb2_role_paths_location: "{{ server_appdata_path }}/{{ influxdb2_role_paths_folder }}"
influxdb2_role_paths_folders_list:
  - "{{ influxdb2_role_paths_location }}"
  - "{{ influxdb2_role_paths_location }}/config"
  - "{{ influxdb2_role_paths_location }}/data"

################################
# Web
################################

influxdb2_role_web_subdomain: "{{ influxdb2_name }}"
influxdb2_role_web_domain: "{{ user.domain }}"
influxdb2_role_web_port: "8086"
influxdb2_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='influxdb2') + '.' + lookup('role_var', '_web_domain', role='influxdb2')
                         if (lookup('role_var', '_web_subdomain', role='influxdb2') | length > 0)
                         else lookup('role_var', '_web_domain', role='influxdb2')) }}"

################################
# DNS
################################

influxdb2_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='influxdb2') }}"
influxdb2_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='influxdb2') }}"
influxdb2_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

influxdb2_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
influxdb2_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
influxdb2_role_traefik_middleware_custom: ""
influxdb2_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
influxdb2_role_traefik_enabled: true
influxdb2_role_traefik_api_enabled: false
influxdb2_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
influxdb2_role_docker_container: "{{ influxdb2_name }}"

# Image
influxdb2_role_docker_image_pull: true
influxdb2_role_docker_image_tag: "2-alpine"
influxdb2_role_docker_image_repo: "influxdb"
influxdb2_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='influxdb2') }}:{{ lookup('role_var', '_docker_image_tag', role='influxdb2') }}"

# Volumes
influxdb2_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='influxdb2') }}/data:/var/lib/influxdb2"
  - "{{ lookup('role_var', '_paths_location', role='influxdb2') }}/config:/etc/influxdb2"
influxdb2_role_docker_volumes_custom: []
influxdb2_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='influxdb2')
                                   + lookup('role_var', '_docker_volumes_custom', role='influxdb2') }}"

# Hostname
influxdb2_role_docker_hostname: "{{ influxdb2_name }}"

# Networks
influxdb2_role_docker_networks_alias: "{{ influxdb2_name }}"
influxdb2_role_docker_networks_default: []
influxdb2_role_docker_networks_custom: []
influxdb2_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='influxdb2')
                                    + lookup('role_var', '_docker_networks_custom', role='influxdb2') }}"

# Restart Policy
influxdb2_role_docker_restart_policy: unless-stopped

# State
influxdb2_role_docker_state: started
