##########################################################################
# Title:         Sandbox: PufferPanel | Default Variables                #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

pufferpanel_name: pufferpanel

################################
# Paths
################################

pufferpanel_role_paths_folder: "{{ pufferpanel_name }}"
pufferpanel_role_paths_location: "{{ server_appdata_path }}/{{ pufferpanel_role_paths_folder }}"
pufferpanel_role_paths_folders_list:
  - "{{ pufferpanel_role_paths_location }}/config"
  - "{{ pufferpanel_role_paths_location }}/data"
  - "{{ pufferpanel_role_paths_location }}/logs"

################################
# Web
################################

pufferpanel_role_web_subdomain: "{{ pufferpanel_name }}"
pufferpanel_role_web_domain: "{{ user.domain }}"
pufferpanel_role_web_port: "8080"
pufferpanel_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='pufferpanel') + '.' + lookup('role_var', '_web_domain', role='pufferpanel')
                           if (lookup('role_var', '_web_subdomain', role='pufferpanel') | length > 0)
                           else lookup('role_var', '_web_domain', role='pufferpanel')) }}"

################################
# DNS
################################

pufferpanel_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='pufferpanel') }}"
pufferpanel_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='pufferpanel') }}"
pufferpanel_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

pufferpanel_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
pufferpanel_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
pufferpanel_role_traefik_middleware_custom: ""
pufferpanel_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
pufferpanel_role_traefik_enabled: true

################################
# Docker
################################

# Container
pufferpanel_role_docker_container: "{{ pufferpanel_name }}"

# Image
pufferpanel_role_docker_image_pull: true
pufferpanel_role_docker_image_repo: "pufferpanel/pufferpanel"
pufferpanel_role_docker_image_tag: "latest"
pufferpanel_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='pufferpanel') }}:{{ lookup('role_var', '_docker_image_tag', role='pufferpanel') }}"

# Ports
pufferpanel_role_docker_ports_default:
  - "5657:5657"
pufferpanel_role_docker_ports_custom: []
pufferpanel_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='pufferpanel')
                                   + lookup('role_var', '_docker_ports_custom', role='pufferpanel') }}"

# Envs
pufferpanel_role_docker_envs_default:
  TZ: "{{ tz }}"
  GIN_MODE: "release"
pufferpanel_role_docker_envs_custom: {}
pufferpanel_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='pufferpanel')
                                  | combine(lookup('role_var', '_docker_envs_custom', role='pufferpanel')) }}"

# Volumes
pufferpanel_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='pufferpanel') }}/config:/etc/pufferpanel"
  - "{{ lookup('role_var', '_paths_location', role='pufferpanel') }}/data:/var/lib/pufferpanel"
  - "{{ lookup('role_var', '_paths_location', role='pufferpanel') }}/logs:/var/log/pufferpanel"
  - "/var/run/docker.sock:/var/run/docker.sock"
pufferpanel_role_docker_volumes_custom: []
pufferpanel_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='pufferpanel')
                                     + lookup('role_var', '_docker_volumes_custom', role='pufferpanel') }}"

# Hostname
pufferpanel_role_docker_hostname: "{{ pufferpanel_name }}"

# Networks
pufferpanel_role_docker_networks_alias: "{{ pufferpanel_name }}"
pufferpanel_role_docker_networks_default: []
pufferpanel_role_docker_networks_custom: []
pufferpanel_role_docker_networks: "{{ docker_networks_common
                                      + lookup('role_var', '_docker_networks_default', role='pufferpanel')
                                      + lookup('role_var', '_docker_networks_custom', role='pufferpanel') }}"

# Restart Policy
pufferpanel_role_docker_restart_policy: unless-stopped

# State
pufferpanel_role_docker_state: started
