##########################################################################
# Title:         Sandbox: Jellystat | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

jellystat_name: jellystat

################################
# Settings
################################

jellystat_role_postgres_name: "{{ jellystat_name }}-postgres"
jellystat_role_postgres_docker_env_db: "jfstat"
jellystat_role_postgres_docker_image_tag: "15.2-alpine"
jellystat_role_postgres_docker_image_repo: "postgres"

################################
# Paths
################################

jellystat_role_paths_folder: "{{ jellystat_name }}"
jellystat_role_paths_location: "{{ server_appdata_path }}/{{ jellystat_role_paths_folder }}"
jellystat_role_paths_jwt_secret_file: "{{ jellystat_role_paths_location }}/jwt_secret.txt"
jellystat_role_paths_folders_list:
  - "{{ jellystat_role_paths_location }}"

################################
# Web
################################

jellystat_role_web_subdomain: "{{ jellystat_name }}"
jellystat_role_web_domain: "{{ user.domain }}"
jellystat_role_web_port: "3000"
jellystat_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='jellystat') + '.' + lookup('role_var', '_web_domain', role='jellystat')
                         if (lookup('role_var', '_web_subdomain', role='jellystat') | length > 0)
                         else lookup('role_var', '_web_domain', role='jellystat')) }}"

################################
# DNS
################################

jellystat_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='jellystat') }}"
jellystat_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='jellystat') }}"
jellystat_role_dns_proxy: "{{ dns.proxied }}"

################################
# Settings
################################

jellystat_log_level: "INFO"
jellystat_emby: false

################################
# Traefik
################################

jellystat_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
jellystat_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
jellystat_role_traefik_middleware_custom: ""
jellystat_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
jellystat_role_traefik_enabled: true
jellystat_role_traefik_api_enabled: false
jellystat_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
jellystat_role_docker_container: "{{ jellystat_name }}"

# Image
jellystat_role_docker_image_pull: true
jellystat_role_docker_image_repo: "cyfershepard/jellystat"
jellystat_role_docker_image_tag: "latest"
jellystat_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='jellystat') }}:{{ lookup('role_var', '_docker_image_tag', role='jellystat') }}"

# Envs
jellystat_role_docker_envs_default:
  POSTGRES_USER: "{{ lookup('role_var', '_docker_env_user ', role='postgres') }}"
  POSTGRES_PASSWORD: "{{ lookup('role_var', '_docker_env_password ', role='postgres') }}"
  POSTGRES_IP: "{{ lookup('role_var', '_postgres_name', role='jellystat') }}"
  POSTGRES_PORT: "5432"
  JWT_SECRET: "{{ jwt_token.stdout }}"
jellystat_role_docker_envs_custom: {}
jellystat_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='jellystat')
                                | combine(lookup('role_var', '_docker_envs_custom', role='jellystat')) }}"

# Volumes
jellystat_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='jellystat') }}:/app/backend/backup-data"
jellystat_role_docker_volumes_custom: []
jellystat_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='jellystat')
                                   + lookup('role_var', '_docker_volumes_custom', role='jellystat') }}"

# Hostname
jellystat_role_docker_hostname: "{{ jellystat_name }}"

# Networks
jellystat_role_docker_networks_alias: "{{ jellystat_name }}"
jellystat_role_docker_networks_default: []
jellystat_role_docker_networks_custom: []
jellystat_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='jellystat')
                                    + lookup('role_var', '_docker_networks_custom', role='jellystat') }}"

# Restart Policy
jellystat_role_docker_restart_policy: unless-stopped

# State
jellystat_role_docker_state: started

# Dependencies
jellystat_depends_on: "{{ lookup('role_var', '_postgres_name', role='jellystat') }}"
jellystat_depends_on_delay: "0"
jellystat_depends_on_healthchecks: "false"
