#########################################################################
# Title:            Sandbox: Hoarder                                    #
# Author(s):        Zuke97                                              #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
# Repository: https://github.com/hoarder-app/hoarder
---
- name: "Fail with deprecation warning"
  ansible.builtin.fail:
    msg: "The 'hoarder' role is deprecated in favour of the 'karakeep' role. The karakeep role will migrate your hoarder appdata to karakeep."
  when: not continuous_integration
