##########################################################################
# Title:         Sandbox: esphome                                        #
# Author(s):     Zuke97                                                  #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

esphome_name: esphome

################################
# Paths
################################

esphome_role_paths_folder: "{{ esphome_name }}"
esphome_role_paths_location: "{{ server_appdata_path }}/{{ esphome_role_paths_folder }}"
esphome_role_paths_conf: "{{ esphome_role_paths_location }}/configuration.yaml"
esphome_role_paths_folders_list:
  - "{{ esphome_role_paths_location }}"

################################
# Web
################################

esphome_role_web_subdomain: "{{ esphome_name }}"
esphome_role_web_domain: "{{ user.domain }}"
esphome_role_web_port: "6052"
esphome_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='esphome') + '.' + lookup('role_var', '_web_domain', role='esphome')
                       if (lookup('role_var', '_web_subdomain', role='esphome') | length > 0)
                       else lookup('role_var', '_web_domain', role='esphome')) }}"

################################
# DNS
################################

esphome_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='esphome') }}"
esphome_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='esphome') }}"
esphome_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

esphome_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
esphome_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
esphome_role_traefik_middleware_custom: ""
esphome_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
esphome_role_traefik_enabled: true
esphome_role_traefik_api_enabled: false
esphome_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
esphome_role_docker_container: "{{ esphome_name }}"

# Image
esphome_role_docker_image_pull: true
esphome_role_docker_image_repo: "ghcr.io/imagegenius/esphome"
esphome_role_docker_image_tag: "latest"
esphome_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='esphome') }}:{{ lookup('role_var', '_docker_image_tag', role='esphome') }}"

# Envs
esphome_role_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
esphome_role_docker_envs_custom: {}
esphome_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='esphome')
                              | combine(lookup('role_var', '_docker_envs_custom', role='esphome')) }}"

# Volumes
esphome_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='esphome') }}:/config"
  - /etc/localtime:/etc/localtime:ro
esphome_role_docker_volumes_custom: []
esphome_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='esphome')
                                 + lookup('role_var', '_docker_volumes_custom', role='esphome') }}"

# Hostname
esphome_role_docker_hostname: "{{ esphome_name }}"

# Networks
esphome_role_docker_networks_alias: "{{ esphome_name }}"
esphome_role_docker_networks_default: []
esphome_role_docker_networks_custom: []
esphome_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='esphome')
                                  + lookup('role_var', '_docker_networks_custom', role='esphome') }}"

# Network Mode
esphome_role_docker_network_mode: "host"

# Restart Policy
esphome_role_docker_restart_policy: unless-stopped

# State
esphome_role_docker_state: started

# Privileged
esphome_role_docker_privileged: true
