##########################################################################
# Title:         Sandbox: Qui | Default Variables                        #
# Author(s):     owine                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

qui_instances: ["qui"]

################################
# Paths
################################

qui_paths_folder: "{{ qui_name }}"
qui_paths_location: "{{ server_appdata_path }}/{{ qui_paths_folder }}"
qui_paths_folders_list:
  - "{{ qui_paths_location }}"

################################
# Web
################################

qui_web_subdomain: "{{ qui_name }}"
qui_web_domain: "{{ user.domain }}"
qui_web_port: "7476"
qui_web_url: "{{ 'https://' + (lookup('vars', qui_name + '_web_subdomain', default=qui_web_subdomain) + '.' + lookup('vars', qui_name + '_web_domain', default=qui_web_domain)
              if (lookup('vars', qui_name + '_web_subdomain', default=qui_web_subdomain) | length > 0)
              else lookup('vars', qui_name + '_web_domain', default=qui_web_domain)) }}"

################################
# DNS
################################

qui_dns_record: "{{ lookup('vars', qui_name + '_web_subdomain', default=qui_web_subdomain) }}"
qui_dns_zone: "{{ lookup('vars', qui_name + '_web_domain', default=qui_web_domain) }}"
qui_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

qui_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
qui_traefik_middleware_default: "{{ traefik_default_middleware }}"
qui_traefik_middleware_custom: ""
qui_traefik_certresolver: "{{ traefik_default_certresolver }}"
qui_traefik_enabled: true
qui_traefik_api_enabled: true
qui_traefik_api_endpoint: "PathPrefix(`/proxy`)"

################################
# Docker
################################

# Container
qui_docker_container: "{{ qui_name }}"

# Image
qui_docker_image_pull: true
qui_docker_image_repo: "ghcr.io/autobrr/qui"
qui_docker_image_tag: "latest"
qui_docker_image: "{{ lookup('vars', qui_name + '_docker_image_repo', default=qui_docker_image_repo) }}:{{ lookup('vars', qui_name + '_docker_image_tag', default=qui_docker_image_tag) }}"

# Ports
qui_docker_ports_defaults: []
qui_docker_ports_custom: []
qui_docker_ports: "{{ lookup('vars', qui_name + '_docker_ports_defaults', default=qui_docker_ports_defaults)
                      + lookup('vars', qui_name + '_docker_ports_custom', default=qui_docker_ports_custom) }}"

# Envs
qui_docker_envs_default:
  TZ: "{{ tz }}"
qui_docker_envs_custom: {}
qui_docker_envs: "{{ lookup('vars', qui_name + '_docker_envs_default', default=qui_docker_envs_default)
                     | combine(lookup('vars', qui_name + '_docker_envs_custom', default=qui_docker_envs_custom)) }}"

# Commands
qui_docker_commands_default: []
qui_docker_commands_custom: []
qui_docker_commands: "{{ lookup('vars', qui_name + '_docker_commands_default', default=qui_docker_commands_default)
                         + lookup('vars', qui_name + '_docker_commands_custom', default=qui_docker_commands_custom) }}"

# Volumes
qui_docker_volumes_default:
  - "{{ qui_paths_location }}:/config"
qui_docker_volumes_custom: []
qui_docker_volumes: "{{ lookup('vars', qui_name + '_docker_volumes_default', default=qui_docker_volumes_default)
                        + lookup('vars', qui_name + '_docker_volumes_custom', default=qui_docker_volumes_custom) }}"

# Devices
qui_docker_devices_default: []
qui_docker_devices_custom: []
qui_docker_devices: "{{ lookup('vars', qui_name + '_docker_devices_default', default=qui_docker_devices_default)
                        + lookup('vars', qui_name + '_docker_devices_custom', default=qui_docker_devices_custom) }}"

# Hosts
qui_docker_hosts_default: {}
qui_docker_hosts_custom: {}
qui_docker_hosts: "{{ docker_hosts_common
                      | combine(lookup('vars', qui_name + '_docker_hosts_default', default=qui_docker_hosts_default))
                      | combine(lookup('vars', qui_name + '_docker_hosts_custom', default=qui_docker_hosts_custom)) }}"

# Labels
qui_docker_labels_default: {}
qui_docker_labels_custom: {}
qui_docker_labels: "{{ docker_labels_common
                       | combine(lookup('vars', qui_name + '_docker_labels_default', default=qui_docker_labels_default))
                       | combine(lookup('vars', qui_name + '_docker_labels_custom', default=qui_docker_labels_custom)) }}"

# Hostname
qui_docker_hostname: "{{ qui_name }}"

# Networks
qui_docker_networks_alias: "{{ qui_name }}"
qui_docker_networks_default: []
qui_docker_networks_custom: []
qui_docker_networks: "{{ docker_networks_common
                         + lookup('vars', qui_name + '_docker_networks_default', default=qui_docker_networks_default)
                         + lookup('vars', qui_name + '_docker_networks_custom', default=qui_docker_networks_custom) }}"

# Capabilities
qui_docker_capabilities_default: []
qui_docker_capabilities_custom: []
qui_docker_capabilities: "{{ lookup('vars', qui_name + '_docker_capabilities_default', default=qui_docker_capabilities_default)
                             + lookup('vars', qui_name + '_docker_capabilities_custom', default=qui_docker_capabilities_custom) }}"

# Security Opts
qui_docker_security_opts_default: []
qui_docker_security_opts_custom: []
qui_docker_security_opts: "{{ lookup('vars', qui_name + '_docker_security_opts_default', default=qui_docker_security_opts_default)
                              + lookup('vars', qui_name + '_docker_security_opts_custom', default=qui_docker_security_opts_custom) }}"

# Restart Policy
qui_docker_restart_policy: unless-stopped

# State
qui_docker_state: started

# User
qui_docker_user: "{{ uid }}:{{ gid }}"
