##########################################################################
# Title:            Sandbox: PlexTraktSync Role                          #
# Author(s):        keldian                                              #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Post-Install | Check if `.pytrakt.json` exists
  ansible.builtin.stat:
    path: "{{ plextraktsync_paths_location }}/.pytrakt.json"
  register: plextraktsync_pytrakt

- name: Post-Install | Check if a Trakt.tv username is supplied
  ansible.builtin.lineinfile:
    path: "{{ plextraktsync_paths_config_location }}"
    regexp: '^TRAKT_USERNAME=(?!\s*$).+'
    state: absent
  check_mode: true
  changed_when: false
  register: plextraktsync_env_trakt_username

- name: Post-Install | Check if a Plex.tv username is supplied
  ansible.builtin.lineinfile:
    path: "{{ plextraktsync_paths_config_location }}"
    regexp: '^PLEX_USERNAME=(?!\s*$).+'
    state: absent
  check_mode: true
  changed_when: false
  register: plextraktsync_env_plex_username

- name: Post-Install | Warn if no Plex.tv username is supplied
  ansible.builtin.debug:
    msg:
      Username not found for Plex. If a user is not specified, watch activity from ALL
      users of the target Plex server will be scrobbled to the target Trakt.tv account.
  when: not plextraktsync_env_plex_username.found

- name: Post-Install | Guide if Trakt.tv login data is missing
  ansible.builtin.pause:
    seconds: 1
    prompt: |

      ╔════ Clean install detected ════════════════════════════════════╗
      ║                                                                ║
      ║                        TO FINISH SETUP                         ║
      ║                                                                ║
      ║  1. Set your preferences in {{ plextraktsync_paths_location + '/config.yml      ║' }}
      ║                                                                ║
      ║  2. Run the below command and follow the interactive script    ║
      ║                                                                ║
      ║  docker exec -it {{ plextraktsync_name + ' python3 -m plextraktsync login  ║' }}
      ║                                                                ║
      ╚════════════════════════════════════════════════════════════════╝

  when: not plextraktsync_env_trakt_username.found or
        not plextraktsync_pytrakt.stat.exists
