##########################################################################
# Title:         Sandbox: Booksonic | Default Variables                  #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

booksonic_name: booksonic

################################
# Paths
################################

booksonic_role_paths_folder: "{{ booksonic_name }}"
booksonic_role_paths_location: "{{ server_appdata_path }}/{{ booksonic_role_paths_folder }}"
booksonic_role_paths_folders_list:
  - "{{ booksonic_role_paths_location }}"

################################
# Web
################################

booksonic_role_web_subdomain: "{{ booksonic_name }}"
booksonic_role_web_domain: "{{ user.domain }}"
booksonic_role_web_port: "4040"
booksonic_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='booksonic') + '.' + lookup('role_var', '_web_domain', role='booksonic')
                         if (lookup('role_var', '_web_subdomain', role='booksonic') | length > 0)
                         else lookup('role_var', '_web_domain', role='booksonic')) }}"

################################
# DNS
################################

booksonic_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='booksonic') }}"
booksonic_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='booksonic') }}"
booksonic_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

booksonic_role_traefik_sso_middleware: ""
booksonic_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
booksonic_role_traefik_middleware_custom: ""
booksonic_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
booksonic_role_traefik_enabled: true

################################
# Docker
################################

# Container
booksonic_role_docker_container: "{{ booksonic_name }}"

# Image
booksonic_role_docker_image_pull: true
booksonic_role_docker_image_repo: "lscr.io/linuxserver/booksonic-air"
booksonic_role_docker_image_tag: "2201.1.0"
booksonic_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='booksonic') }}:{{ lookup('role_var', '_docker_image_tag', role='booksonic') }}"

# Ports
booksonic_role_docker_ports_default: []
booksonic_role_docker_ports_custom: []
booksonic_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='booksonic')
                                 + lookup('role_var', '_docker_ports_custom', role='booksonic') }}"

# Envs
booksonic_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  JAVA_OPTS: "-Dserver.use-forward-headers=true"
booksonic_role_docker_envs_custom: {}
booksonic_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='booksonic')
                                | combine(lookup('role_var', '_docker_envs_custom', role='booksonic')) }}"

# Volumes
booksonic_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='booksonic') }}:/config"
  - "/mnt/unionfs/Media/Audiobooks:/audiobooks"
  - "/mnt/unionfs/Media/Podcasts:/podcasts"
  - "/mnt/unionfs/Media:/othermedia"
booksonic_role_docker_volumes_custom: []
booksonic_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='booksonic')
                                   + lookup('role_var', '_docker_volumes_custom', role='booksonic') }}"

# Hostname
booksonic_role_docker_hostname: "{{ booksonic_name }}"

# Networks
booksonic_role_docker_networks_alias: "{{ booksonic_name }}"
booksonic_role_docker_networks_default: []
booksonic_role_docker_networks_custom: []
booksonic_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='booksonic')
                                    + lookup('role_var', '_docker_networks_custom', role='booksonic') }}"

# Restart Policy
booksonic_role_docker_restart_policy: unless-stopped

# State
booksonic_role_docker_state: started
