##########################################################################
# Title:            Sandbox: Recyclarr   | Default Variables             #
# Author(s):        BeansIsFat                                           #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

recyclarr_name: recyclarr

################################
# Settings
################################

recyclarr_role_cron_schedule: "@daily"

################################
# Paths
################################

recyclarr_role_paths_folder: "{{ recyclarr_name }}"
recyclarr_role_paths_location: "{{ server_appdata_path }}/{{ recyclarr_role_paths_folder }}"
recyclarr_role_paths_folders_list:
  - "{{ recyclarr_role_paths_location }}"

################################
# Docker
################################

# Container
recyclarr_role_docker_container: "{{ recyclarr_name }}"

# Image
recyclarr_role_docker_image_pull: true
recyclarr_role_docker_image_repo: "ghcr.io/recyclarr/recyclarr"
recyclarr_role_docker_image_tag: "latest"
recyclarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='recyclarr') }}:{{ lookup('role_var', '_docker_image_tag', role='recyclarr') }}"

# Envs
recyclarr_role_docker_envs_default:
  TZ: "{{ tz }}"
  CRON_SCHEDULE: "{{ lookup('role_var', '_cron_schedule', role='recyclarr') }}"
  RECYCLARR_CREATE_CONFIG: "true"
recyclarr_role_docker_envs_custom: {}
recyclarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='recyclarr')
                                | combine(lookup('role_var', '_docker_envs_custom', role='recyclarr')) }}"

# Volumes
recyclarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='recyclarr') }}:/config"
recyclarr_role_docker_volumes_custom: []
recyclarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='recyclarr')
                                   + lookup('role_var', '_docker_volumes_custom', role='recyclarr') }}"

# Hostname
recyclarr_role_docker_hostname: "{{ recyclarr_name }}"

# Networks
recyclarr_role_docker_networks_alias: "{{ recyclarr_name }}"
recyclarr_role_docker_networks_default: []
recyclarr_role_docker_networks_custom: []
recyclarr_role_docker_networks: "{{ docker_networks_common
                                    + lookup('role_var', '_docker_networks_default', role='recyclarr')
                                    + lookup('role_var', '_docker_networks_custom', role='recyclarr') }}"

# Restart Policy
recyclarr_role_docker_restart_policy: unless-stopped

# State
recyclarr_role_docker_state: started

# User
recyclarr_role_docker_user: "{{ uid }}:{{ gid }}"
