##########################################################################
# Title:            Community: InfluxDB                                  #
# Author(s):        desimaniac, kowalski                                 #
# URL:              https://github.com/saltyorg/Community                #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

influxdb_name: influxdb

################################
# Paths
################################

influxdb_paths_folder: "{{ influxdb_name }}"
influxdb_paths_location: "{{ server_appdata_path }}/{{ influxdb_paths_folder }}"
influxdb_paths_folders_list:
  - "{{ influxdb_paths_location }}"

################################
# Docker
################################

# Container
influxdb_docker_container: "{{ influxdb_name }}"

# Image
influxdb_docker_image_pull: true
influxdb_docker_image_tag: "1.8.4"
influxdb_docker_image: "influxdb:{{ influxdb_docker_image_tag }}"

# Ports
influxdb_docker_ports_defaults: []
influxdb_docker_ports_custom: []
influxdb_docker_ports: "{{ influxdb_docker_ports_defaults
                           + influxdb_docker_ports_custom
                        if (not reverse_proxy_is_enabled)
                        else [] + influxdb_docker_ports_custom }}"

# Envs
influxdb_docker_envs_default: {}
influxdb_docker_envs_custom: {}
influxdb_docker_envs: "{{ influxdb_docker_envs_default
                          | combine(influxdb_docker_envs_custom) }}"

# Commands
influxdb_docker_commands_default: []
influxdb_docker_commands_custom: []
influxdb_docker_commands: "{{ influxdb_docker_commands_default
                              + influxdb_docker_commands_custom }}"

# Volumes
influxdb_docker_volumes_default:
  - "{{ influxdb_paths_location }}:/var/lib/influxdb"
influxdb_docker_volumes_custom: []
influxdb_docker_volumes: "{{ influxdb_docker_volumes_default
                             + influxdb_docker_volumes_custom
                             + docker_volumes_downloads_common }}"

# Devices
influxdb_docker_devices_default: []
influxdb_docker_devices_custom: []
influxdb_docker_devices: "{{ influxdb_docker_devices_default
                             + influxdb_docker_devices_custom }}"

# Hosts
influxdb_docker_hosts_default: []
influxdb_docker_hosts_custom: []
influxdb_docker_hosts: "{{ docker_hosts_common
                           | combine(influxdb_docker_hosts_default)
                           | combine(influxdb_docker_hosts_custom) }}"

# Labels
influxdb_docker_labels_default: {}
influxdb_docker_labels_custom: {}
influxdb_docker_labels: "{{ docker_labels_common
                            | combine(influxdb_docker_labels_default)
                            | combine(influxdb_docker_labels_custom) }}"

# Hostname
influxdb_docker_hostname: "{{ influxdb_name }}"

# Networks
influxdb_docker_networks_alias: "{{ influxdb_name }}"
influxdb_docker_networks_default: []
influxdb_docker_networks_custom: []
influxdb_docker_networks: "{{ docker_networks_common
                              + influxdb_docker_networks_default
                              + influxdb_docker_networks_custom }}"

# Capabilities
influxdb_docker_capabilities_default: []
influxdb_docker_capabilities_custom: []
influxdb_docker_capabilities: "{{ influxdb_docker_capabilities_default
                                  + influxdb_docker_capabilities_custom }}"

# Security Opts
influxdb_docker_security_opts_default: []
influxdb_docker_security_opts_custom: []
influxdb_docker_security_opts: "{{ influxdb_docker_security_opts_default
                                   + influxdb_docker_security_opts_custom }}"

# Restart Policy
influxdb_docker_restart_policy: unless-stopped

# State
influxdb_docker_state: started
