#########################################################################
# Title:         Sandbox: AdGuard Home | Default Variables              #
# Author(s):     sevos                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

adguardhome_name: adguardhome

################################
# Paths
################################

adguardhome_role_paths_folder: "{{ adguardhome_name }}"
adguardhome_role_paths_location: "{{ server_appdata_path }}/{{ adguardhome_role_paths_folder }}"
adguardhome_role_paths_config_path: "{{ adguardhome_role_paths_location }}/conf/AdGuardHome.yaml"
adguardhome_role_paths_folders_list:
  - "{{ adguardhome_role_paths_location }}"
  - "{{ adguardhome_role_paths_location }}/conf"
  - "{{ adguardhome_role_paths_location }}/work"
  - "{{ adguardhome_role_paths_location }}/work/data"
  - "{{ adguardhome_role_paths_location }}/work/data/filters"

################################
# Web
################################

adguardhome_role_web_subdomain: "{{ adguardhome_name }}"
adguardhome_role_web_domain: "{{ user.domain }}"
adguardhome_role_web_port: "3000"
adguardhome_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='adguardhome') + '.' + lookup('role_var', '_web_domain', role='adguardhome')
                           if (lookup('role_var', '_web_subdomain', role='adguardhome') | length > 0)
                           else lookup('role_var', '_web_domain', role='adguardhome')) }}"

################################
# DNS
################################

adguardhome_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='adguardhome') }}"
adguardhome_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='adguardhome') }}"
adguardhome_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

adguardhome_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
adguardhome_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
adguardhome_role_traefik_middleware_custom: ""
adguardhome_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
adguardhome_role_traefik_enabled: true
adguardhome_role_traefik_api_enabled: true
adguardhome_role_traefik_api_endpoint: "PathPrefix(`/dns-query`)"

################################
# Docker
################################

# Container
adguardhome_role_docker_container: "{{ adguardhome_name }}"

# Image
adguardhome_role_docker_image_pull: true
adguardhome_role_docker_image_repo: "adguard/adguardhome"
adguardhome_role_docker_image_tag: "latest"
adguardhome_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='adguardhome') }}:{{ lookup('role_var', '_docker_image_tag', role='adguardhome') }}"

# Envs
adguardhome_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
adguardhome_role_docker_envs_custom: {}
adguardhome_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='adguardhome')
                                  | combine(lookup('role_var', '_docker_envs_custom', role='adguardhome')) }}"

# Volumes
adguardhome_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='adguardhome') }}/work:/opt/adguardhome/work"
  - "{{ lookup('role_var', '_paths_location', role='adguardhome') }}/conf:/opt/adguardhome/conf"
adguardhome_role_docker_volumes_custom: []
adguardhome_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='adguardhome')
                                     + lookup('role_var', '_docker_volumes_custom', role='adguardhome') }}"

# Hostname
adguardhome_role_docker_hostname: "{{ adguardhome_name }}"

# Networks
adguardhome_role_docker_networks_alias: "{{ adguardhome_name }}"
adguardhome_role_docker_networks_default: []
adguardhome_role_docker_networks_custom: []
adguardhome_role_docker_networks: "{{ docker_networks_common
                                      + lookup('role_var', '_docker_networks_default', role='adguardhome')
                                      + lookup('role_var', '_docker_networks_custom', role='adguardhome') }}"

# Restart Policy
adguardhome_role_docker_restart_policy: unless-stopped

# State
adguardhome_role_docker_state: started
