#########################################################################
# Title:         Sandbox: AdGuard Home | Default Variables              #
# Author(s):     sevos                                                  #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

adguardhome_name: adguardhome

################################
# Paths
################################

adguardhome_paths_folder: "{{ adguardhome_name }}"
adguardhome_paths_location: "{{ server_appdata_path }}/{{ adguardhome_paths_folder }}"
adguardhome_config_path: "{{ adguardhome_paths_location }}/conf/AdGuardHome.yaml"
adguardhome_paths_folders_list:
  - "{{ adguardhome_paths_location }}"
  - "{{ adguardhome_paths_location }}/conf"
  - "{{ adguardhome_paths_location }}/work"
  - "{{ adguardhome_paths_location }}/work/data"
  - "{{ adguardhome_paths_location }}/work/data/filters"

################################
# Web
################################

adguardhome_web_subdomain: "{{ adguardhome_name }}"
adguardhome_web_domain: "{{ user.domain }}"
adguardhome_web_port: "3000"
adguardhome_web_url: "{{ 'https://' + (adguardhome_web_subdomain + '.' + adguardhome_web_domain
                      if (adguardhome_web_subdomain | length > 0)
                      else adguardhome_web_domain) }}"

################################
# DNS
################################

adguardhome_dns_record: "{{ adguardhome_web_subdomain }}"
adguardhome_dns_zone: "{{ adguardhome_web_domain }}"
adguardhome_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

adguardhome_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
adguardhome_traefik_middleware_default: "{{ traefik_default_middleware }}"
adguardhome_traefik_middleware_custom: ""
adguardhome_traefik_certresolver: "{{ traefik_default_certresolver }}"
adguardhome_traefik_enabled: true
adguardhome_traefik_api_enabled: true
adguardhome_traefik_api_endpoint: "PathPrefix(`/dns-query`)"

################################
# Docker
################################

# Container
adguardhome_docker_container: "{{ adguardhome_name }}"

# Image
adguardhome_docker_image_pull: true
adguardhome_docker_image_tag: "latest"
adguardhome_docker_image: "adguard/adguardhome:{{ adguardhome_docker_image_tag }}"

# Ports
adguardhome_docker_ports_defaults: []
adguardhome_docker_ports_custom: []
adguardhome_docker_ports: "{{ adguardhome_docker_ports_defaults
                              + adguardhome_docker_ports_custom }}"

# Envs
adguardhome_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
adguardhome_docker_envs_custom: {}
adguardhome_docker_envs: "{{ adguardhome_docker_envs_default
                             | combine(adguardhome_docker_envs_custom) }}"

# Commands
adguardhome_docker_commands_default: []
adguardhome_docker_commands_custom: []
adguardhome_docker_commands: "{{ adguardhome_docker_commands_default
                                 + adguardhome_docker_commands_custom }}"

# Volumes
adguardhome_docker_volumes_default:
  - "{{ adguardhome_paths_location }}/work:/opt/adguardhome/work"
  - "{{ adguardhome_paths_location }}/conf:/opt/adguardhome/conf"
adguardhome_docker_volumes_custom: []
adguardhome_docker_volumes: "{{ adguardhome_docker_volumes_default }}"

# Devices
adguardhome_docker_devices_default: []
adguardhome_docker_devices_custom: []
adguardhome_docker_devices: "{{ adguardhome_docker_devices_default
                                + adguardhome_docker_devices_custom }}"

# Hosts
adguardhome_docker_hosts_default: {}
adguardhome_docker_hosts_custom: {}
adguardhome_docker_hosts: "{{ docker_hosts_common
                              | combine(adguardhome_docker_hosts_default)
                              | combine(adguardhome_docker_hosts_custom) }}"

# Labels
adguardhome_docker_labels_default: {}
adguardhome_docker_labels_custom: {}
adguardhome_docker_labels: "{{ docker_labels_common
                               | combine(adguardhome_docker_labels_default)
                               | combine(adguardhome_docker_labels_custom) }}"

# Hostname
adguardhome_docker_hostname: "{{ adguardhome_name }}"

# Networks
adguardhome_docker_networks_alias: "{{ adguardhome_name }}"
adguardhome_docker_networks_default: []
adguardhome_docker_networks_custom: []
adguardhome_docker_networks: "{{ docker_networks_common
                                 + adguardhome_docker_networks_default
                                 + adguardhome_docker_networks_custom }}"

# Capabilities
adguardhome_docker_capabilities_default: []
adguardhome_docker_capabilities_custom: []
adguardhome_docker_capabilities: "{{ adguardhome_docker_capabilities_default
                                     + adguardhome_docker_capabilities_custom }}"

# Security Opts
adguardhome_docker_security_opts_default: []
adguardhome_docker_security_opts_custom: []
adguardhome_docker_security_opts: "{{ adguardhome_docker_security_opts_default
                                      + adguardhome_docker_security_opts_custom }}"

# Restart Policy
adguardhome_docker_restart_policy: unless-stopped

# State
adguardhome_docker_state: started
