#########################################################################
# Title:            Sandbox: Apprise                                    #
# Author(s):        owine, kowalski                                     #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

apprise_name: apprise

################################
# Paths
################################

apprise_paths_folder: "{{ apprise_name }}"
apprise_paths_location: "{{ server_appdata_path }}/{{ apprise_paths_folder }}"
apprise_paths_folders_list:
  - "{{ apprise_paths_location }}"

################################
# Web
################################

apprise_web_subdomain: "{{ apprise_name }}"
apprise_web_domain: "{{ user.domain }}"
apprise_web_port: "8000"
apprise_web_url: "{{ 'https://' + (apprise_web_subdomain + '.' + apprise_web_domain
                  if (apprise_web_subdomain | length > 0)
                  else apprise_web_domain) }}"

################################
# DNS
################################

apprise_dns_record: "{{ apprise_web_subdomain }}"
apprise_dns_zone: "{{ apprise_web_domain }}"
apprise_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

apprise_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
apprise_traefik_middleware_default: "{{ traefik_default_middleware }}"
apprise_traefik_middleware_custom: ""
apprise_traefik_certresolver: "{{ traefik_default_certresolver }}"
apprise_traefik_enabled: true

################################
# Docker
################################

# Container
apprise_docker_container: "{{ apprise_name }}"

# Image
apprise_docker_image_pull: true
apprise_docker_image_tag: "latest"
apprise_docker_image: "lscr.io/linuxserver/apprise-api:{{ apprise_docker_image_tag }}"

# Ports
apprise_docker_ports_defaults: []
apprise_docker_ports_custom: []
apprise_docker_ports: "{{ apprise_docker_ports_defaults
                          + apprise_docker_ports_custom }}"

# Envs
apprise_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
apprise_docker_envs_custom: {}
apprise_docker_envs: "{{ apprise_docker_envs_default
                         | combine(apprise_docker_envs_custom) }}"

# Commands
apprise_docker_commands_default: []
apprise_docker_commands_custom: []
apprise_docker_commands: "{{ apprise_docker_commands_default
                             + apprise_docker_commands_custom }}"

# Volumes
apprise_docker_volumes_default:
  - "{{ apprise_paths_location }}:/config"
apprise_docker_volumes_custom: []
apprise_docker_volumes: "{{ apprise_docker_volumes_default
                            + apprise_docker_volumes_custom }}"

# Devices
apprise_docker_devices_default: []
apprise_docker_devices_custom: []
apprise_docker_devices: "{{ apprise_docker_devices_default
                            + apprise_docker_devices_custom }}"

# Hosts
apprise_docker_hosts_default: {}
apprise_docker_hosts_custom: {}
apprise_docker_hosts: "{{ docker_hosts_common
                          | combine(apprise_docker_hosts_default)
                          | combine(apprise_docker_hosts_custom) }}"

# Labels
apprise_docker_labels_default: {}
apprise_docker_labels_custom: {}
apprise_docker_labels: "{{ docker_labels_common
                           | combine(apprise_docker_labels_default)
                           | combine(apprise_docker_labels_custom) }}"

# Hostname
apprise_docker_hostname: "{{ apprise_name }}"

# Networks
apprise_docker_networks_alias: "{{ apprise_name }}"
apprise_docker_networks_default: []
apprise_docker_networks_custom: []
apprise_docker_networks: "{{ docker_networks_common
                             + apprise_docker_networks_default
                             + apprise_docker_networks_custom }}"

# Capabilities
apprise_docker_capabilities_default: []
apprise_docker_capabilities_custom: []
apprise_docker_capabilities: "{{ apprise_docker_capabilities_default
                                 + apprise_docker_capabilities_custom }}"

# Security Opts
apprise_docker_security_opts_default: []
apprise_docker_security_opts_custom: []
apprise_docker_security_opts: "{{ apprise_docker_security_opts_default
                                  + apprise_docker_security_opts_custom }}"

# Restart Policy
apprise_docker_restart_policy: unless-stopped

# State
apprise_docker_state: started
