#########################################################################
# Title:            Sandbox: Apprise                                    #
# Author(s):        owine, kowalski                                     #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

apprise_name: apprise

################################
# Paths
################################

apprise_role_paths_folder: "{{ apprise_name }}"
apprise_role_paths_location: "{{ server_appdata_path }}/{{ apprise_role_paths_folder }}"
apprise_role_paths_folders_list:
  - "{{ apprise_role_paths_location }}"

################################
# Web
################################

apprise_role_web_subdomain: "{{ apprise_name }}"
apprise_role_web_domain: "{{ user.domain }}"
apprise_role_web_port: "8000"
apprise_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='apprise') + '.' + lookup('role_var', '_web_domain', role='apprise')
                       if (lookup('role_var', '_web_subdomain', role='apprise') | length > 0)
                       else lookup('role_var', '_web_domain', role='apprise')) }}"

################################
# DNS
################################

apprise_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='apprise') }}"
apprise_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='apprise') }}"
apprise_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

apprise_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
apprise_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
apprise_role_traefik_middleware_custom: ""
apprise_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
apprise_role_traefik_enabled: true

################################
# Docker
################################

# Container
apprise_role_docker_container: "{{ apprise_name }}"

# Image
apprise_role_docker_image_pull: true
apprise_role_docker_image_repo: "lscr.io/linuxserver/apprise-api"
apprise_role_docker_image_tag: "latest"
apprise_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='apprise') }}:{{ lookup('role_var', '_docker_image_tag', role='apprise') }}"

# Envs
apprise_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
apprise_role_docker_envs_custom: {}
apprise_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='apprise')
                              | combine(lookup('role_var', '_docker_envs_custom', role='apprise')) }}"

# Volumes
apprise_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='apprise') }}:/config"
apprise_role_docker_volumes_custom: []
apprise_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='apprise')
                                 + lookup('role_var', '_docker_volumes_custom', role='apprise') }}"

# Hostname
apprise_role_docker_hostname: "{{ apprise_name }}"

# Networks
apprise_role_docker_networks_alias: "{{ apprise_name }}"
apprise_role_docker_networks_default: []
apprise_role_docker_networks_custom: []
apprise_role_docker_networks: "{{ docker_networks_common
                                  + lookup('role_var', '_docker_networks_default', role='apprise')
                                  + lookup('role_var', '_docker_networks_custom', role='apprise') }}"

# Restart Policy
apprise_role_docker_restart_policy: unless-stopped

# State
apprise_role_docker_state: started
