#########################################################################
# Title:         Sandbox: Settings | Ansible Config                     #
# Author(s):     l3uddz, desimaniac, Migz93, salty                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if '{{ item }}' exists."
  stat:
    path: "{{ playbook_dir }}/{{ item }}"
  register: file

- name: "Copy '{{ item }}.default' to '{{ item }}'."
  copy:
    src: "{{ playbook_dir }}/defaults/{{ item }}.default"
    dest: "{{ playbook_dir }}/{{ item }}"
    owner: "{{ sandbox_yml.stat.uid }}"
    group: "{{ sandbox_yml.stat.gid }}"
    mode: 0664
    force: true
  when: not file.stat.exists

- name: Add default entries to '{{ item }}'
  ini_file:
    path: "{{ playbook_dir }}/{{ item }}"
    section: "{{ inner_item.section }}"
    option: "{{ inner_item.option }}"
    value: "{{ inner_item.value | default(omit) }}"
    state: "{{ inner_item.state | default('present') }}"
    no_extra_spaces: false
    owner: "{{ community_yml.stat.uid }}"
    group: "{{ community_yml.stat.gid }}"
    mode: 0664
  register: ansible_cfg_update_status
  loop:
    - { section: 'defaults', option: 'inventory', value: '/srv/git/saltbox/inventories/local' }
    - { section: 'defaults', option: 'roles_path', value: 'roles:/srv/git/saltbox/roles:/srv/git/saltbox/resources/roles' }
    - { section: 'defaults', option: 'fact_path', value: '/srv/git/saltbox/ansible_facts.d' }
    - { section: 'defaults', option: 'filter_plugins', value: '/srv/git/saltbox/filter_plugins' }
    - { section: 'defaults', option: 'interpreter_python', value: '/usr/bin/python3' }
    - { section: 'defaults', option: 'log_path', value: './sandbox.log' }
    - { section: 'defaults', option: 'callbacks_enabled', value: 'profile_tasks' }
    - { section: 'defaults', option: 'callback_whitelist', state: 'absent' }
    - { section: 'defaults', option: 'command_warnings', state: 'absent' }
  loop_control:
    loop_var: "inner_item"
  when: file.stat.exists

- name: "Exit if '{{ item }}' changes."
  include_tasks: "ansible_config_2.yml"
  when:
    - file.stat.exists
    - inner_item.changed
  loop: "{{ ansible_cfg_update_status.results }}"
  loop_control:
    loop_var: "inner_item"
