#########################################################################
# Title:            Sandbox: tqm | Default Variables                    #
# Author(s):        CHAIR/Raneydazed                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

tqm_name: tqm

################################
# Settings
################################

tqm_role_download_client: "qbt"

################################
# Paths
################################

tqm_role_paths_folder: "{{ tqm_name }}"
tqm_role_paths_location: "{{ server_appdata_path }}/{{ tqm_role_paths_folder }}"
tqm_role_paths_config_location: "{{ tqm_role_paths_location }}/config.yaml"
tqm_role_paths_service_location: "/etc/systemd/system/tqm.service"
tqm_role_paths_timer_location: "/etc/systemd/system/tqm.timer"
tqm_role_paths_folders_list:
  - "{{ tqm_role_paths_location }}"
