#########################################################################
# Title:            Sandbox: Suwayomi                                   #
# Author(s):        JohnClementine                                      #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

suwayomi_name: suwayomi

################################
# Paths
################################

suwayomi_role_paths_folder: "{{ suwayomi_name }}"
suwayomi_role_paths_location: "{{ server_appdata_path }}/{{ suwayomi_role_paths_folder }}"
suwayomi_role_paths_config_location: "{{ suwayomi_role_paths_location }}/server.conf"
suwayomi_role_paths_folders_list:
  - "{{ suwayomi_role_paths_location }}"
  - "{{ server_local_folder_path }}/Media/Comics"

################################
# Web
################################

suwayomi_role_web_subdomain: "{{ suwayomi_name }}"
suwayomi_role_web_domain: "{{ user.domain }}"
suwayomi_role_web_port: "4567"
suwayomi_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain') + '.' + lookup('role_var', '_web_domain')
                        if (lookup('role_var', '_web_subdomain') | length > 0)
                        else lookup('role_var', '_web_domain')) }}"

################################
# DNS
################################

suwayomi_role_dns_record: "{{ lookup('role_var', '_web_subdomain') }}"
suwayomi_role_dns_zone: "{{ lookup('role_var', '_web_domain') }}"
suwayomi_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

suwayomi_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
suwayomi_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
suwayomi_role_traefik_middleware_custom: ""
suwayomi_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
suwayomi_role_traefik_enabled: true
suwayomi_role_traefik_api_enabled: false
suwayomi_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
suwayomi_role_docker_container: "{{ suwayomi_name }}"

# Image
suwayomi_role_docker_image_pull: true
suwayomi_role_docker_image_repo: "ghcr.io/suwayomi/suwayomi-server"
suwayomi_role_docker_image_tag: "latest"
suwayomi_role_docker_image: "{{ lookup('role_var', '_docker_image_repo') }}:{{ lookup('role_var', '_docker_image_tag') }}"

# Envs
suwayomi_role_docker_envs_default:
  TZ: "{{ tz }}"
suwayomi_role_docker_envs_custom: {}
suwayomi_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default')
                               | combine(lookup('role_var', '_docker_envs_custom')) }}"

# Volumes
suwayomi_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location') }}:/home/suwayomi/.local/share/Tachidesk"
  - "/mnt/unionfs/Media/Comics:/comics"
suwayomi_role_docker_volumes_custom: []
suwayomi_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default')
                                  + lookup('role_var', '_docker_volumes_custom') }}"

# Hostname
suwayomi_role_docker_hostname: "{{ suwayomi_name }}"

# Networks
suwayomi_role_docker_networks_alias: "{{ suwayomi_name }}"
suwayomi_role_docker_networks_default: []
suwayomi_role_docker_networks_custom: []
suwayomi_role_docker_networks: "{{ docker_networks_common
                                   + lookup('role_var', '_docker_networks_default')
                                   + lookup('role_var', '_docker_networks_custom') }}"

# Restart Policy
suwayomi_role_docker_restart_policy: unless-stopped

# State
suwayomi_role_docker_state: started

# User
suwayomi_role_docker_user: "{{ uid }}:{{ gid }}"
