##########################################################################
# Title:         Sandbox: Suwayomi | Default Variables                   #
# Author(s):     JohnClementine                                          #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

suwayomi_name: suwayomi

################################
# Paths
################################

suwayomi_paths_folder: "{{ suwayomi_name }}"
suwayomi_paths_location: "{{ server_appdata_path }}/{{ suwayomi_paths_folder }}"
suwayomi_paths_config_location: "{{ suwayomi_paths_location }}/server.conf"
suwayomi_paths_folders_list:
  - "{{ suwayomi_paths_location }}"
  - "/mnt/local/Media/Comics"

################################
# Web
################################

suwayomi_web_subdomain: "{{ suwayomi_name }}"
suwayomi_web_domain: "{{ user.domain }}"
suwayomi_web_port: "4567"
suwayomi_web_url: "{{ 'https://' + (suwayomi_web_subdomain + '.' + suwayomi_web_domain
                   if (suwayomi_web_subdomain | length > 0)
                   else suwayomi_web_domain) }}"

################################
# DNS
################################

suwayomi_dns_record: "{{ suwayomi_web_subdomain }}"
suwayomi_dns_zone: "{{ suwayomi_web_domain }}"
suwayomi_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

suwayomi_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
suwayomi_traefik_middleware_default: "{{ traefik_default_middleware }}"
suwayomi_traefik_middleware_custom: ""
suwayomi_traefik_certresolver: "{{ traefik_default_certresolver }}"
suwayomi_traefik_enabled: true
suwayomi_traefik_api_enabled: false
suwayomi_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
suwayomi_docker_container: "{{ suwayomi_name }}"

# Image
suwayomi_docker_image_pull: true
suwayomi_docker_image_repo: "ghcr.io/suwayomi/suwayomi-server"
suwayomi_docker_image_tag: "latest"
suwayomi_docker_image: "{{ suwayomi_docker_image_repo
                           + ':' + suwayomi_docker_image_tag }}"

# Ports
suwayomi_docker_ports_defaults: []
suwayomi_docker_ports_custom: []
suwayomi_docker_ports: "{{ suwayomi_docker_ports_defaults
                          + suwayomi_docker_ports_custom }}"

# Envs
suwayomi_docker_envs_default:
  TZ: "{{ tz }}"
suwayomi_docker_envs_custom: {}
suwayomi_docker_envs: "{{ suwayomi_docker_envs_default
                         | combine(suwayomi_docker_envs_custom) }}"

# Commands
suwayomi_docker_commands_default: []
suwayomi_docker_commands_custom: []
suwayomi_docker_commands: "{{ suwayomi_docker_commands_default
                             + suwayomi_docker_commands_custom }}"

# Volumes
suwayomi_docker_volumes_default:
  - "{{ suwayomi_paths_location }}:/home/suwayomi/.local/share/Tachidesk"
  - "/mnt/unionfs/Media/Comics:/comics"
suwayomi_docker_volumes_custom: []
suwayomi_docker_volumes: "{{ suwayomi_docker_volumes_default
                            + suwayomi_docker_volumes_custom }}"

# Devices
suwayomi_docker_devices_default: []
suwayomi_docker_devices_custom: []
suwayomi_docker_devices: "{{ suwayomi_docker_devices_default
                            + suwayomi_docker_devices_custom }}"

# Hosts
suwayomi_docker_hosts_default: {}
suwayomi_docker_hosts_custom: {}
suwayomi_docker_hosts: "{{ docker_hosts_common
                          | combine(suwayomi_docker_hosts_default)
                          | combine(suwayomi_docker_hosts_custom) }}"

# Labels
suwayomi_docker_labels_default: {}
suwayomi_docker_labels_custom: {}
suwayomi_docker_labels: "{{ docker_labels_common
                           | combine(suwayomi_docker_labels_default)
                           | combine(suwayomi_docker_labels_custom) }}"

# Hostname
suwayomi_docker_hostname: "{{ suwayomi_name }}"

# Network Mode
suwayomi_docker_network_mode_default: "{{ docker_networks_name_common }}"
suwayomi_docker_network_mode: "{{ suwayomi_docker_network_mode_default }}"

# Networks
suwayomi_docker_networks_alias: "{{ suwayomi_name }}"
suwayomi_docker_networks_default: []
suwayomi_docker_networks_custom: []
suwayomi_docker_networks: "{{ docker_networks_common
                             + suwayomi_docker_networks_default
                             + suwayomi_docker_networks_custom }}"

# Capabilities
suwayomi_docker_capabilities_default: []
suwayomi_docker_capabilities_custom: []
suwayomi_docker_capabilities: "{{ suwayomi_docker_capabilities_default
                                 + suwayomi_docker_capabilities_custom }}"

# Security Opts
suwayomi_docker_security_opts_default: []
suwayomi_docker_security_opts_custom: []
suwayomi_docker_security_opts: "{{ suwayomi_docker_security_opts_default
                                  + suwayomi_docker_security_opts_custom }}"

# Restart Policy
suwayomi_docker_restart_policy: unless-stopped

# State
suwayomi_docker_state: started

# User
suwayomi_docker_user: "{{ uid }}:{{ gid }}"
