#########################################################################
# Title:            Sandbox: Logarr                                     #
# Author(s):        Superduper09, Kalroth, RXWatcher, kowalski          #
# URL:              https://github.com/saltyorg/Sandbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

logarr_name: logarr

################################
# Paths
################################

logarr_paths_folder: "{{ logarr_name }}"
logarr_paths_location: "{{ server_appdata_path }}/{{ logarr_paths_folder }}"
logarr_paths_folders_list:
  - "{{ logarr_paths_location }}"
  - "{{ logarr_paths_location }}/config"
  - "{{ logarr_paths_location }}/userdata"
logarr_paths_config_location: "{{ logarr_paths_location }}/userdata/config.json"

################################
# Web
################################

logarr_web_subdomain: "{{ logarr_name }}"
logarr_web_domain: "{{ user.domain }}"
logarr_web_port: "80"
logarr_web_url: "{{ 'https://' + (logarr_web_subdomain + '.' + logarr_web_domain
                 if (logarr_web_subdomain | length > 0)
                 else logarr_web_domain) }}"

################################
# DNS
################################

logarr_dns_record: "{{ logarr_web_subdomain }}"
logarr_dns_zone: "{{ logarr_web_domain }}"
logarr_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

logarr_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
logarr_traefik_middleware_default: "{{ traefik_default_middleware }}"
logarr_traefik_middleware_custom: ""
logarr_traefik_certresolver: "{{ traefik_default_certresolver }}"
logarr_traefik_enabled: true
logarr_traefik_api_enabled: false
logarr_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
logarr_docker_container: "{{ logarr_name }}"

# Image
logarr_docker_image_pull: true
logarr_docker_image_tag: "latest"
logarr_docker_image: "monitorr/logarr-alpha:{{ logarr_docker_image_tag }}"

# Ports
logarr_docker_ports_defaults: []
logarr_docker_ports_custom: []
logarr_docker_ports: "{{ logarr_docker_ports_defaults
                         + logarr_docker_ports_custom }}"

# Envs
logarr_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
logarr_docker_envs_custom: {}
logarr_docker_envs: "{{ logarr_docker_envs_default
                        | combine(logarr_docker_envs_custom) }}"

# Commands
logarr_docker_commands_default: []
logarr_docker_commands_custom: []
logarr_docker_commands: "{{ logarr_docker_commands_default
                            + logarr_docker_commands_custom }}"

# Volumes
logarr_docker_volumes_default:
  - "{{ logarr_paths_location }}:/app"
  - "{{ logarr_paths_location }}/config:/config"
  - "{{ server_appdata_path }}:/opt"
logarr_docker_volumes_custom: []
logarr_docker_volumes: "{{ logarr_docker_volumes_default
                           + logarr_docker_volumes_custom }}"

# Devices
logarr_docker_devices_default: []
logarr_docker_devices_custom: []
logarr_docker_devices: "{{ logarr_docker_devices_default
                           + logarr_docker_devices_custom }}"

# Hosts
logarr_docker_hosts_default: {}
logarr_docker_hosts_custom: {}
logarr_docker_hosts: "{{ docker_hosts_common
                         | combine(logarr_docker_hosts_default)
                         | combine(logarr_docker_hosts_custom) }}"

# Labels
logarr_docker_labels_default: {}
logarr_docker_labels_custom: {}
logarr_docker_labels: "{{ docker_labels_common
                          | combine(logarr_docker_labels_default)
                          | combine(logarr_docker_labels_custom) }}"

# Hostname
logarr_docker_hostname: "{{ logarr_name }}"

# Networks
logarr_docker_networks_alias: "{{ logarr_name }}"
logarr_docker_networks_default: []
logarr_docker_networks_custom: []
logarr_docker_networks: "{{ docker_networks_common
                            + logarr_docker_networks_default
                            + logarr_docker_networks_custom }}"

# Capabilities
logarr_docker_capabilities_default: []
logarr_docker_capabilities_custom: []
logarr_docker_capabilities: "{{ logarr_docker_capabilities_default
                                + logarr_docker_capabilities_custom }}"

# Security Opts
logarr_docker_security_opts_default: []
logarr_docker_security_opts_custom: []
logarr_docker_security_opts: "{{ logarr_docker_security_opts_default
                                 + logarr_docker_security_opts_custom }}"

# Restart Policy
logarr_docker_restart_policy: unless-stopped

# State
logarr_docker_state: started
