##########################################################################
# Title:         Sandbox: Transmission VPN | Default Variables           #
# Author(s):     Tarek, ayykamp                                          #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

transmissionvpn_name: transmissionvpn

################################
# Settings
################################

transmissionvpn_create_tun_device: "false"
transmissionvpn_transmission_home: "/opt/transmissionvpn"
transmissionvpn_umask_set: "022"

################################
# Paths
################################

transmissionvpn_paths_folder: "{{ transmissionvpn_name }}"
transmissionvpn_paths_location: "{{ server_appdata_path }}/{{ transmissionvpn_paths_folder }}"
transmissionvpn_paths_downloads_location: "{{ downloads_torrents_path }}/{{ transmissionvpn_paths_folder }}"

transmissionvpn_paths_folders_list:
  - "{{ transmissionvpn_paths_location }}"
  - "{{ transmissionvpn_paths_downloads_location }}"
  - "{{ transmissionvpn_paths_downloads_location }}/completed"
  - "{{ transmissionvpn_paths_downloads_location }}/incoming"
  - "{{ transmissionvpn_paths_downloads_location }}/watched"
  - "{{ transmissionvpn_paths_downloads_location }}/torrents"

################################
# Web
################################

transmissionvpn_web_subdomain: "{{ transmissionvpn_name }}"
transmissionvpn_web_domain: "{{ user.domain }}"
transmissionvpn_web_port: "9091"
transmissionvpn_web_url: "{{ 'https://' + (transmissionvpn_web_subdomain + '.' + transmissionvpn_web_domain
                          if (transmissionvpn_web_subdomain | length > 0)
                          else transmissionvpn_web_domain) }}"

################################
# DNS
################################

transmissionvpn_dns_record: "{{ transmissionvpn_web_subdomain }}"
transmissionvpn_dns_zone: "{{ transmissionvpn_web_domain }}"
transmissionvpn_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

transmissionvpn_traefik_sso_middleware: ""
transmissionvpn_traefik_middleware_default: "{{ traefik_default_middleware }}"
transmissionvpn_traefik_middleware_custom: ""
transmissionvpn_traefik_certresolver: "{{ traefik_default_certresolver }}"
transmissionvpn_traefik_enabled: true
transmissionvpn_traefik_api_enabled: false
transmissionvpn_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
transmissionvpn_docker_container: "{{ transmissionvpn_name }}"

# Image
transmissionvpn_docker_image_pull: true
transmissionvpn_docker_image_tag: "latest"
transmissionvpn_docker_image: "haugene/transmission-openvpn:{{ transmissionvpn_docker_image_tag }}"

# Ports
transmissionvpn_docker_ports_defaults: []
transmissionvpn_docker_ports_custom: []
transmissionvpn_docker_ports: "{{ transmissionvpn_docker_ports_defaults
                                  + transmissionvpn_docker_ports_custom }}"

# Envs
transmissionvpn_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  OPENVPN_PROVIDER: "{{ transmissionvpn.vpn_prov | default('pia', true) }}"
  OPENVPN_USERNAME: "{{ transmissionvpn.vpn_user | default('username', true) }}"
  OPENVPN_PASSWORD: "{{ transmissionvpn.vpn_pass | default('password', true) }}"
  UMASK_SET: "{{ transmissionvpn_umask_set }}"
  CREATE_TUN_DEVICE: "{{ transmissionvpn_create_tun_device }}"
  TRANSMISSION_HOME: "{{ transmissionvpn_transmission_home }}"

transmissionvpn_docker_envs_custom: {}
transmissionvpn_docker_envs: "{{ transmissionvpn_docker_envs_default
                                 | combine(transmissionvpn_docker_envs_custom) }}"

# Commands
transmissionvpn_docker_commands_default: []
transmissionvpn_docker_commands_custom: []
transmissionvpn_docker_commands: "{{ transmissionvpn_docker_commands_default
                                     + transmissionvpn_docker_commands_custom }}"

# Volumes
transmissionvpn_docker_volumes_default:
  - "{{ transmissionvpn_paths_location }}:/config"
  - "{{ transmissionvpn_paths_location }}/data:/opt/transmissionvpn"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "{{ transmissionvpn_paths_location }}/vpn:/etc/openvpn/custom"
  - "{{ transmissionvpn_paths_downloads_location }}:/data"
transmissionvpn_docker_volumes_custom: []
transmissionvpn_docker_volumes: "{{ transmissionvpn_docker_volumes_default
                                    + transmissionvpn_docker_volumes_custom }}"

# Devices
transmissionvpn_docker_devices_default: []
transmissionvpn_docker_devices_custom: []
transmissionvpn_docker_devices: "{{ transmissionvpn_docker_devices_default
                                    + transmissionvpn_docker_devices_custom }}"

# Hosts
transmissionvpn_docker_hosts_default: {}
transmissionvpn_docker_hosts_custom: {}
transmissionvpn_docker_hosts: "{{ docker_hosts_common
                                  | combine(transmissionvpn_docker_hosts_default)
                                  | combine(transmissionvpn_docker_hosts_custom) }}"

# Labels
transmissionvpn_docker_labels_default: {}
transmissionvpn_docker_labels_custom: {}
transmissionvpn_docker_labels: "{{ docker_labels_common
                                   | combine(transmissionvpn_docker_labels_default)
                                   | combine(transmissionvpn_docker_labels_custom) }}"

# Hostname
transmissionvpn_docker_hostname: "{{ transmissionvpn_name }}"

# Networks
transmissionvpn_docker_networks_alias: "{{ transmissionvpn_name }}"
transmissionvpn_docker_networks_default: []
transmissionvpn_docker_networks_custom: []
transmissionvpn_docker_networks: "{{ docker_networks_common
                                     + transmissionvpn_docker_networks_default
                                     + transmissionvpn_docker_networks_custom }}"

# Capabilities
transmissionvpn_docker_capabilities_default:
  - NET_ADMIN
transmissionvpn_docker_capabilities_custom: []
transmissionvpn_docker_capabilities: "{{ transmissionvpn_docker_capabilities_default
                                         + transmissionvpn_docker_capabilities_custom }}"

# Security Opts
transmissionvpn_docker_security_opts_default: []
transmissionvpn_docker_security_opts_custom: []
transmissionvpn_docker_security_opts: "{{ transmissionvpn_docker_security_opts_default
                                          + transmissionvpn_docker_security_opts_custom }}"

# Restart Policy
transmissionvpn_docker_restart_policy: unless-stopped

# State
transmissionvpn_docker_state: started

# Sysctls
transmissionvpn_docker_sysctls:
  net.ipv4.conf.all.src_valid_mark: "1"

# Privileged
transmissionvpn_docker_privileged: "yes"
