##########################################################################
# Title:         Sandbox: Transmission VPN | Default Variables           #
# Author(s):     Tarek, ayykamp                                          #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

transmissionvpn_name: transmissionvpn

################################
# Settings
################################

transmissionvpn_create_tun_device: "false"
transmissionvpn_transmission_home: "/opt/transmissionvpn"
transmissionvpn_umask_set: "022"
transmissionvpn_role_vpn_user: ""
transmissionvpn_role_vpn_pass: ""
transmissionvpn_role_vpn_prov: ""

################################
# Paths
################################

transmissionvpn_role_paths_folder: "{{ transmissionvpn_name }}"
transmissionvpn_role_paths_location: "{{ server_appdata_path }}/{{ transmissionvpn_role_paths_folder }}"
transmissionvpn_role_paths_downloads_location: "{{ downloads_torrents_path }}/{{ transmissionvpn_role_paths_folder }}"
transmissionvpn_role_paths_folders_list:
  - "{{ transmissionvpn_role_paths_location }}"
  - "{{ transmissionvpn_role_paths_downloads_location }}"
  - "{{ transmissionvpn_role_paths_downloads_location }}/completed"
  - "{{ transmissionvpn_role_paths_downloads_location }}/incoming"
  - "{{ transmissionvpn_role_paths_downloads_location }}/watched"
  - "{{ transmissionvpn_role_paths_downloads_location }}/torrents"

################################
# Web
################################

transmissionvpn_role_web_subdomain: "{{ transmissionvpn_name }}"
transmissionvpn_role_web_domain: "{{ user.domain }}"
transmissionvpn_role_web_port: "9091"
transmissionvpn_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='transmissionvpn') + '.' + lookup('role_var', '_web_domain', role='transmissionvpn')
                               if (lookup('role_var', '_web_subdomain', role='transmissionvpn') | length > 0)
                               else lookup('role_var', '_web_domain', role='transmissionvpn')) }}"

################################
# DNS
################################

transmissionvpn_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='transmissionvpn') }}"
transmissionvpn_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='transmissionvpn') }}"
transmissionvpn_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

transmissionvpn_role_traefik_sso_middleware: ""
transmissionvpn_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
transmissionvpn_role_traefik_middleware_custom: ""
transmissionvpn_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
transmissionvpn_role_traefik_enabled: true
transmissionvpn_role_traefik_api_enabled: false
transmissionvpn_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
transmissionvpn_role_docker_container: "{{ transmissionvpn_name }}"

# Image
transmissionvpn_role_docker_image_pull: true
transmissionvpn_role_docker_image_repo: "haugene/transmission-openvpn"
transmissionvpn_role_docker_image_tag: "latest"
transmissionvpn_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='transmissionvpn') }}:{{ lookup('role_var', '_docker_image_tag', role='transmissionvpn') }}"

# Envs
transmissionvpn_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  OPENVPN_PROVIDER: "{{ lookup('role_var', '_vpn_prov', role='transmissionvpn') }}"
  OPENVPN_USERNAME: "{{ lookup('role_var', '_vpn_user', role='transmissionvpn') }}"
  OPENVPN_PASSWORD: "{{ lookup('role_var', '_vpn_pass', role='transmissionvpn') }}"
  UMASK_SET: "{{ transmissionvpn_umask_set }}"
  CREATE_TUN_DEVICE: "{{ transmissionvpn_create_tun_device }}"
  TRANSMISSION_HOME: "{{ transmissionvpn_transmission_home }}"
transmissionvpn_role_docker_envs_custom: {}
transmissionvpn_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='transmissionvpn')
                                      | combine(lookup('role_var', '_docker_envs_custom', role='transmissionvpn')) }}"

# Volumes
transmissionvpn_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='transmissionvpn') }}:/config"
  - "{{ lookup('role_var', '_paths_location', role='transmissionvpn') }}/data:/opt/transmissionvpn"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "{{ lookup('role_var', '_paths_location', role='transmissionvpn') }}/vpn:/etc/openvpn/custom"
  - "{{ lookup('role_var', '_paths_downloads_location', role='transmissionvpn') }}:/data"
transmissionvpn_role_docker_volumes_custom: []
transmissionvpn_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='transmissionvpn')
                                         + lookup('role_var', '_docker_volumes_custom', role='transmissionvpn') }}"

# Hostname
transmissionvpn_role_docker_hostname: "{{ transmissionvpn_name }}"

# Networks
transmissionvpn_role_docker_networks_alias: "{{ transmissionvpn_name }}"
transmissionvpn_role_docker_networks_default: []
transmissionvpn_role_docker_networks_custom: []
transmissionvpn_role_docker_networks: "{{ docker_networks_common
                                          + lookup('role_var', '_docker_networks_default', role='transmissionvpn')
                                          + lookup('role_var', '_docker_networks_custom', role='transmissionvpn') }}"

# Capabilities
transmissionvpn_role_docker_capabilities_default:
  - NET_ADMIN
transmissionvpn_role_docker_capabilities_custom: []
transmissionvpn_role_docker_capabilities: "{{ transmissionvpn_role_docker_capabilities_default
                                              + transmissionvpn_role_docker_capabilities_custom }}"

# Restart Policy
transmissionvpn_role_docker_restart_policy: unless-stopped

# State
transmissionvpn_role_docker_state: started

# Sysctls
transmissionvpn_role_docker_sysctls:
  net.ipv4.conf.all.src_valid_mark: "1"

# Privileged
transmissionvpn_role_docker_privileged: true
