##########################################################################
# Title:         Sandbox: Crafty Controller | Default Variables          #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

crafty_name: crafty

################################
# Paths
################################

crafty_role_paths_folder: "{{ crafty_name }}"
crafty_role_paths_group: "root"
crafty_role_paths_location: "{{ server_appdata_path }}/{{ crafty_role_paths_folder }}"
crafty_role_paths_folders_list:
  - "{{ crafty_role_paths_location }}"
  - "{{ crafty_role_paths_location }}/backups"
  - "{{ crafty_role_paths_location }}/logs"
  - "{{ crafty_role_paths_location }}/servers"
  - "{{ crafty_role_paths_location }}/config"
  - "{{ crafty_role_paths_location }}/import"
crafty_role_paths_recurse: true

################################
# Web
################################

crafty_role_web_subdomain: "{{ crafty_name }}"
crafty_role_web_domain: "{{ user.domain }}"
crafty_role_web_port: "8443"
crafty_role_web_scheme: "https"
crafty_role_web_serverstransport: "skipverify@file"
crafty_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='crafty') + '.' + lookup('role_var', '_web_domain', role='crafty')
                      if (lookup('role_var', '_web_subdomain', role='crafty') | length > 0)
                      else lookup('role_var', '_web_domain', role='crafty')) }}"

crafty_role_dynmap_web_subdomain: "{{ crafty_name }}-map"
crafty_role_dynmap_web_domain: "{{ user.domain }}"
crafty_role_dynmap_web_port: "8123"
crafty_role_dynmap_host: "{{ lookup('role_var', '_dynmap_web_subdomain', role='crafty')
                             + '.' + lookup('role_var', '_dynmap_web_domain', role='crafty') }}"

################################
# DNS
################################

crafty_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='crafty') }}"
crafty_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='crafty') }}"
crafty_role_dns_proxy: "{{ dns.proxied }}"
crafty_dynmap_role_dns_record: "{{ lookup('role_var', '_dynmap_web_subdomain', role='crafty') }}"
crafty_dynmap_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='crafty') }}"
crafty_dynmap_role_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

crafty_role_traefik_sso_middleware: ""
crafty_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
crafty_role_traefik_middleware_custom: ""
crafty_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
crafty_role_traefik_enabled: true

################################
# Docker
################################

# Container
crafty_role_docker_container: "{{ crafty_name }}"

# Image
crafty_role_docker_image_pull: true
crafty_role_docker_image_repo: "arcadiatechnology/crafty-4"
crafty_role_docker_image_tag: "latest"
crafty_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='crafty') }}:{{ lookup('role_var', '_docker_image_tag', role='crafty') }}"

# Ports
crafty_role_docker_ports_defaults:
  - "19132:19132/udp"
  - "25500-25600:25500-25600"
crafty_role_docker_ports_custom: []
crafty_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults', role='crafty')
                              + lookup('role_var', '_docker_ports_custom', role='crafty') }}"

# Envs
crafty_role_docker_envs_default:
  TZ: "{{ tz }}"
crafty_role_docker_envs_custom: {}
crafty_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='crafty')
                             | combine(lookup('role_var', '_docker_envs_custom', role='crafty')) }}"

# Volumes
crafty_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='crafty') }}/backups:/crafty/backups"
  - "{{ lookup('role_var', '_paths_location', role='crafty') }}/logs:/crafty/logs"
  - "{{ lookup('role_var', '_paths_location', role='crafty') }}/servers:/crafty/servers"
  - "{{ lookup('role_var', '_paths_location', role='crafty') }}/config:/crafty/app/config"
  - "{{ lookup('role_var', '_paths_location', role='crafty') }}/import:/crafty/import"
crafty_role_docker_volumes_custom: []
crafty_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='crafty')
                                + lookup('role_var', '_docker_volumes_custom', role='crafty') }}"

# Labels
crafty_role_docker_labels_default:
  - '{ "traefik.http.routers.{{ crafty_name }}-map-http.entrypoints": "web" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map-http.service": "{{ crafty_name }}-map" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map-http.rule": "Host(`{{ lookup("role_var", "_dynmap_host", role="crafty") }}`)" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map-http.middlewares": "{{ traefik_default_middleware_http }}" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map-http.priority": "20" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.entrypoints": "websecure" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.service": "{{ crafty_name }}-map" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.rule": "Host(`{{ lookup("role_var", "_dynmap_host", role="crafty") }}`)" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.tls.options": "securetls@file" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.tls.certresolver": "{{ lookup("role_var", "_traefik_certresolver", role="crafty") }}" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.middlewares": "{{ traefik_default_middleware }}" }'
  - '{ "traefik.http.routers.{{ crafty_name }}-map.priority": "20" }'
  - '{ "traefik.http.services.{{ crafty_name }}-map.loadbalancer.server.port": "{{ lookup("role_var", "_dynmap_web_port", role="crafty") }}" }'
crafty_role_docker_labels_custom: {}
crafty_role_docker_labels: "{{ lookup('role_var', '_docker_labels_default', role='crafty')
                               | combine(lookup('role_var', '_docker_labels_custom', role='crafty')) }}"

# Hostname
crafty_role_docker_hostname: "{{ crafty_name }}"

# Networks
crafty_role_docker_networks_alias: "{{ crafty_name }}"
crafty_role_docker_networks_default: []
crafty_role_docker_networks_custom: []
crafty_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='crafty')
                                 + lookup('role_var', '_docker_networks_custom', role='crafty') }}"

# Restart Policy
crafty_role_docker_restart_policy: unless-stopped

# State
crafty_role_docker_state: started

# Stop Timeout
crafty_role_docker_stop_timeout: 900
