#########################################################################
# Title:            Sandbox: tubearchivist                              #
# Author(s):        JigSawFr                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# URL:              https://github.com/tubearchivist/tubearchivist      #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Redis Role
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_name: "{{ tubearchivist_name }}_redis"
    redis_docker_image_tag: "latest"
    redis_docker_image: "redislabs/rejson"
    redis_paths_folder: "{{ tubearchivist_name }}"
    redis_paths_location: "{{ server_appdata_path }}/{{ redis_paths_folder }}/redis"

- name: Elasticsearch Role
  ansible.builtin.include_role:
    name: elasticsearch
  vars:
    elasticsearch_name: "{{ tubearchivist_name }}_elasticsearch"
    elasticsearch_docker_image_tag: "8.5.0"
    elasticsearch_paths_folder: "{{ tubearchivist_name }}"
    elasticsearch_paths_location: "{{ server_appdata_path }}/{{ elasticsearch_paths_folder }}/elastiscsearch"

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
