##########################################################################
# Title:            Sandbox: Tdarr   | Default Variables                 #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

tdarr_name: tdarr

################################
# Settings
################################

tdarr_role_server_port: "8266"
tdarr_role_server_external: false

################################
# Paths
################################

tdarr_role_paths_folder: "{{ tdarr_name }}"
tdarr_role_paths_location: "{{ server_appdata_path }}/{{ tdarr_role_paths_folder }}"
tdarr_role_paths_server_location: "{{ tdarr_role_paths_location }}/server"
tdarr_role_paths_configs_location: "{{ tdarr_role_paths_location }}/configs"
tdarr_role_paths_logs_location: "{{ tdarr_role_paths_location }}/logs"
tdarr_role_paths_transcodes_location: "{{ transcodes_path }}/{{ tdarr_role_paths_folder }}"
tdarr_role_paths_folders_list:
  - "{{ tdarr_role_paths_location }}"
  - "{{ tdarr_role_paths_server_location }}"
  - "{{ tdarr_role_paths_configs_location }}"
  - "{{ tdarr_role_paths_logs_location }}"
  - "{{ tdarr_role_paths_transcodes_location }}"

################################
# Web
################################

tdarr_role_web_subdomain: "{{ tdarr_name }}"
tdarr_role_web_domain: "{{ user.domain }}"
tdarr_role_web_port: "8265"
tdarr_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='tdarr') + '.' + lookup('role_var', '_web_domain', role='tdarr')
                     if (lookup('role_var', '_web_subdomain', role='tdarr') | length > 0)
                     else lookup('role_var', '_web_domain', role='tdarr')) }}"

################################
# DNS
################################

tdarr_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='tdarr') }}"
tdarr_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='tdarr') }}"
tdarr_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

tdarr_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
tdarr_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
tdarr_role_traefik_middleware_custom: ""
tdarr_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
tdarr_role_traefik_enabled: true
tdarr_role_traefik_api_enabled: false
tdarr_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
tdarr_role_docker_container: "{{ tdarr_name }}"

# Image
tdarr_role_docker_image_pull: true
tdarr_role_docker_image_repo: "haveagitgat/tdarr"
tdarr_role_docker_image_tag: "latest"
tdarr_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='tdarr') }}:{{ lookup('role_var', '_docker_image_tag', role='tdarr') }}"

# Ports
tdarr_role_docker_ports_default:
  - "{{ lookup('role_var', '_server_port', role='tdarr') }}:{{ lookup('role_var', '_server_port', role='tdarr') }}"
tdarr_role_docker_ports_custom: []
tdarr_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='tdarr') if (lookup('role_var', '_server_external', role='tdarr')) else []
                             + lookup('role_var', '_docker_ports_custom', role='tdarr') }}"

# Envs
tdarr_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  serverIP: "0.0.0.0"
  webUIPort: "8265"
  serverPort: "{{ lookup('role_var', '_server_port', role='tdarr') }}"
  internalNode: "true"
  inContainer: "true"
tdarr_role_docker_envs_custom: {}
tdarr_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='tdarr')
                            | combine(lookup('role_var', '_docker_envs_custom', role='tdarr')) }}"

# Volumes
tdarr_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_configs_location', role='tdarr') }}:/app/configs"
  - "{{ lookup('role_var', '_paths_server_location', role='tdarr') }}:/app/server"
  - "{{ lookup('role_var', '_paths_logs_location', role='tdarr') }}:/app/logs"
  - "{{ lookup('role_var', '_paths_transcodes_location', role='tdarr') }}:/temp"
  - "/mnt/unionfs/Media:/media"
  - "/mnt/unionfs/Media/Movies:/movies"
  - "/mnt/unionfs/Media/TV:/tv"
  - "/dev/shm:/dev/shm"
tdarr_role_docker_volumes_custom: []
tdarr_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='tdarr')
                               + lookup('role_var', '_docker_volumes_custom', role='tdarr') }}"

# Hostname
tdarr_role_docker_hostname: "{{ tdarr_name }}"

# Networks
tdarr_role_docker_networks_alias: "{{ tdarr_name }}"
tdarr_role_docker_networks_default: []
tdarr_role_docker_networks_custom: []
tdarr_role_docker_networks: "{{ docker_networks_common
                                + lookup('role_var', '_docker_networks_default', role='tdarr')
                                + lookup('role_var', '_docker_networks_custom', role='tdarr') }}"

# Restart Policy
tdarr_role_docker_restart_policy: unless-stopped

# State
tdarr_role_docker_state: started
