##########################################################################
# Title:         Sandbox: Joplin | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

joplin_name: joplin

################################
# Paths
################################

joplin_paths_folder: "{{ joplin_name }}"
joplin_paths_location: "{{ server_appdata_path }}/{{ joplin_paths_folder }}"
joplin_paths_folders_list:
  - "{{ joplin_paths_location }}"

################################
# Web
################################

joplin_web_subdomain: "{{ joplin_name }}"
joplin_web_domain: "{{ user.domain }}"
joplin_web_port: "22300"
joplin_web_url: "{{ 'https://' + joplin_web_subdomain + '.' + joplin_web_domain }}"

################################
# DNS
################################

joplin_dns_record: "{{ joplin_web_subdomain }}"
joplin_dns_zone: "{{ joplin_web_domain }}"
joplin_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

joplin_traefik_sso_middleware: ""
joplin_traefik_middleware: "{{ traefik_default_middleware + ',' + joplin_traefik_sso_middleware
                            if (joplin_traefik_sso_middleware | length > 0)
                            else traefik_default_middleware }}"
joplin_traefik_certresolver: "{{ traefik_default_certresolver }}"
joplin_traefik_enabled: true

################################
# Docker
################################

# Container
joplin_docker_container: "{{ joplin_name }}"

# Image
joplin_docker_image_pull: true
joplin_docker_image_tag: "latest"
joplin_docker_image: "joplin/server:{{ joplin_docker_image_tag }}"

# Ports
joplin_docker_ports_defaults: []
joplin_docker_ports_custom: []
joplin_docker_ports: "{{ joplin_docker_ports_defaults
                         + joplin_docker_ports_custom }}"

# Envs
joplin_docker_envs_default:
  TZ: "{{ tz }}"
  APP_BASE_URL: "{{ joplin_web_url }}"
  APP_PORT: "22300"
  POSTGRES_PASSWORD: "joplin"
  POSTGRES_DATABASE: "joplin"
  POSTGRES_USER: "joplin"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "{{ joplin_name }}_postgres"
  DB_CLIENT: "pg"
joplin_docker_envs_custom: {}
joplin_docker_envs: "{{ joplin_docker_envs_default
                        | combine(joplin_docker_envs_custom) }}"

# Commands
joplin_docker_commands_default: []
joplin_docker_commands_custom: []
joplin_docker_commands: "{{ joplin_docker_commands_default
                            + joplin_docker_commands_custom }}"

# Volumes
joplin_docker_volumes_default: []
joplin_docker_volumes_custom: []
joplin_docker_volumes: "{{ joplin_docker_volumes_default
                           + joplin_docker_volumes_custom }}"

# Devices
joplin_docker_devices_default: []
joplin_docker_devices_custom: []
joplin_docker_devices: "{{ joplin_docker_devices_default
                           + joplin_docker_devices_custom }}"

# Hosts
joplin_docker_hosts_default: []
joplin_docker_hosts_custom: []
joplin_docker_hosts: "{{ docker_hosts_common
                         | combine(joplin_docker_hosts_default)
                         | combine(joplin_docker_hosts_custom) }}"

# Labels
joplin_docker_labels_default: {}
joplin_docker_labels_custom: {}
joplin_docker_labels: "{{ docker_labels_common
                          | combine(joplin_docker_labels_default)
                          | combine(joplin_docker_labels_custom) }}"

# Hostname
joplin_docker_hostname: "{{ joplin_name }}"

# Networks
joplin_docker_networks_alias: "{{ joplin_name }}"
joplin_docker_networks_default: []
joplin_docker_networks_custom: []
joplin_docker_networks: "{{ docker_networks_common
                            + joplin_docker_networks_default
                            + joplin_docker_networks_custom }}"

# Capabilities
joplin_docker_capabilities_default: []
joplin_docker_capabilities_custom: []
joplin_docker_capabilities: "{{ joplin_docker_capabilities_default
                                + joplin_docker_capabilities_custom }}"

# Security Opts
joplin_docker_security_opts_default: []
joplin_docker_security_opts_custom: []
joplin_docker_security_opts: "{{ joplin_docker_security_opts_default
                                 + joplin_docker_security_opts_custom }}"

# Restart Policy
joplin_docker_restart_policy: unless-stopped

# State
joplin_docker_state: started
