##########################################################################
# Title:            Sandbox: Wireguard                                   #
# Author(s):        owine, salty                                         #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('role_var', '_dns_record') }}"
    dns_zone: "{{ lookup('role_var', '_dns_zone') }}"
    dns_proxy: "{{ lookup('role_var', '_dns_proxy') }}"

- name: Check if wg-easy database exists
  ansible.builtin.stat:
    path: "{{ wireguard_role_paths_location }}/wg-easy.db"
  register: wireguard_db

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: debug
  ansible.builtin.debug:
    var: docker_ipv6

- name: Create wg network
  community.docker.docker_network:
    name: wg
    state: present
    enable_ipv6: "{{ true
                  if docker_ipv6
                  else false }}"
    ipam_config:
      - subnet: 10.42.42.0/24
      - subnet: "{{ 'fdcc:ad94:bacf:61a3::/64'
                 if docker_ipv6
                 else omit }}"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
