##########################################################################
# Title:            Sandbox: qBit Management   | Default Variables       #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

qbit_manage_name: qbit-manage

################################
# Settings
################################

qbit_manage_role_qbt_run: "false"
qbit_manage_role_qbt_schedule: "30"
qbit_manage_role_qbt_config: "config.yml"
qbit_manage_role_qbt_logfile: "activity.log"
qbit_manage_role_qbt_cross_seed: "false"
qbit_manage_role_qbt_recheck: "false"
qbit_manage_role_qbt_cat_update: "false"
qbit_manage_role_qbt_tag_update: "false"
qbit_manage_role_qbt_rem_unregistered: "false"
qbit_manage_role_qbt_rem_orphaned: "false"
qbit_manage_role_qbt_tag_nohardlinks: "false"
qbit_manage_role_qbt_skip_recycle: "false"
qbit_manage_role_qbt_dry_run: "true"
qbit_manage_role_qbt_log_level: "INFO"
qbit_manage_role_qbt_divider: "="
qbit_manage_role_qbt_width: "100"
qbit_manage_role_qbt_debug: "false"
qbit_manage_role_qbt_trace: "false"

################################
# Paths
################################

qbit_manage_role_paths_folder: "{{ qbit_manage_name }}"
qbit_manage_role_paths_location: "{{ server_appdata_path }}/{{ qbit_manage_role_paths_folder }}"
qbit_manage_role_paths_folders_list:
  - "{{ qbit_manage_role_paths_location }}"

################################
# Web
################################

qbit_manage_role_web_subdomain: "{{ qbit_manage_name }}"
qbit_manage_role_web_domain: "{{ user.domain }}"
qbit_manage_role_web_port: "8080"
qbit_manage_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='qbit_manage') + '.' + lookup('role_var', '_web_domain', role='qbit_manage')
                           if (lookup('role_var', '_web_subdomain', role='qbit_manage') | length > 0)
                           else lookup('role_var', '_web_domain', role='qbit_manage')) }}"

################################
# DNS
################################

qbit_manage_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='qbit_manage') }}"
qbit_manage_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='qbit_manage') }}"
qbit_manage_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

qbit_manage_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
qbit_manage_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
qbit_manage_role_traefik_middleware_custom: ""
qbit_manage_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
qbit_manage_role_traefik_enabled: true
qbit_manage_role_traefik_api_enabled: true
qbit_manage_role_traefik_api_endpoint: "PathPrefix(`/api`)"

################################
# Docker
################################

# Container
qbit_manage_role_docker_container: "{{ qbit_manage_name }}"

# Image
qbit_manage_role_docker_image_pull: true
qbit_manage_role_docker_image_repo: "ghcr.io/hotio/qbitmanage"
qbit_manage_role_docker_image_tag: "release"
qbit_manage_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='qbit_manage') }}:{{ lookup('role_var', '_docker_image_tag', role='qbit_manage') }}"

# Ports
qbit_manage_role_docker_ports_default: []
qbit_manage_role_docker_ports_custom: []
qbit_manage_role_docker_ports: "{{ lookup('role_var', '_docker_ports_default', role='qbit_manage')
                                   + lookup('role_var', '_docker_ports_custom', role='qbit_manage') }}"

# Envs
qbit_manage_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  QBT_WEB_SERVER: "true"
  QBT_RUN: "{{ lookup('role_var', '_qbt_run', role='qbit_manage') }}"
  QBT_SCHEDULE: "{{ lookup('role_var', '_qbt_schedule', role='qbit_manage') }}"
  QBT_CONFIG: "{{ lookup('role_var', '_qbt_config', role='qbit_manage') }}"
  QBT_LOGFILE: "{{ lookup('role_var', '_qbt_logfile', role='qbit_manage') }}"
  QBT_CROSS_SEED: "{{ lookup('role_var', '_qbt_cross_seed', role='qbit_manage') }}"
  QBT_RECHECK: "{{ lookup('role_var', '_qbt_recheck', role='qbit_manage') }}"
  QBT_CAT_UPDATE: "{{ lookup('role_var', '_qbt_cat_update', role='qbit_manage') }}"
  QBT_TAG_UPDATE: "{{ lookup('role_var', '_qbt_tag_update', role='qbit_manage') }}"
  QBT_REM_UNREGISTERED: "{{ lookup('role_var', '_qbt_rem_unregistered', role='qbit_manage') }}"
  QBT_REM_ORPHANED: "{{ lookup('role_var', '_qbt_rem_orphaned', role='qbit_manage') }}"
  QBT_TAG_NOHARDLINKS: "{{ lookup('role_var', '_qbt_tag_nohardlinks', role='qbit_manage') }}"
  QBT_SKIP_RECYCLE: "{{ lookup('role_var', '_qbt_skip_recycle', role='qbit_manage') }}"
  QBT_DRY_RUN: "{{ lookup('role_var', '_qbt_dry_run', role='qbit_manage') }}"
  QBT_LOG_LEVEL: "{{ lookup('role_var', '_qbt_log_level', role='qbit_manage') }}"
  QBT_DIVIDER: "{{ lookup('role_var', '_qbt_divider', role='qbit_manage') }}"
  QBT_WIDTH: "{{ lookup('role_var', '_qbt_width', role='qbit_manage') }}"
  QBT_DEBUG: "{{ lookup('role_var', '_qbt_debug', role='qbit_manage') }}"
  QBT_TRACE: "{{ lookup('role_var', '_qbt_trace', role='qbit_manage') }}"
qbit_manage_role_docker_envs_custom: {}
qbit_manage_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='qbit_manage')
                                  | combine(lookup('role_var', '_docker_envs_custom', role='qbit_manage')) }}"

# Volumes
qbit_manage_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='qbit_manage') }}:/config"
qbit_manage_role_docker_volumes_custom: []
qbit_manage_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='qbit_manage')
                                     + lookup('role_var', '_docker_volumes_custom', role='qbit_manage') }}"

# Hostname
qbit_manage_role_docker_hostname: "{{ qbit_manage_name }}"

# Networks
qbit_manage_role_docker_networks_alias: "{{ qbit_manage_name }}"
qbit_manage_role_docker_networks_default: []
qbit_manage_role_docker_networks_custom: []
qbit_manage_role_docker_networks: "{{ docker_networks_common
                                      + lookup('role_var', '_docker_networks_default', role='qbit_manage')
                                      + lookup('role_var', '_docker_networks_custom', role='qbit_manage') }}"

# Restart Policy
qbit_manage_role_docker_restart_policy: on-failure
qbit_manage_role_docker_restart_retries: 3

# State
qbit_manage_role_docker_state: started
