##########################################################################
# Title:            Sandbox: qBit Management   | Default Variables       #
# Author(s):        kowalski                                             #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

qbit_manage_name: qbit-manage

################################
# Paths
################################

qbit_manage_paths_folder: "{{ qbit_manage_name }}"
qbit_manage_paths_location: "{{ server_appdata_path }}/{{ qbit_manage_paths_folder }}"
qbit_manage_paths_folders_list:
  - "{{ qbit_manage_paths_location }}"

################################
# Docker
################################

# Container
qbit_manage_docker_container: "{{ qbit_manage_name }}"

# Image
qbit_manage_docker_image_pull: true
qbit_manage_docker_image_tag: "release"
qbit_manage_docker_image: "ghcr.io/hotio/qbitmanage:{{ qbit_manage_docker_image_tag }}"

# Ports
qbit_manage_docker_ports_defaults: []
qbit_manage_docker_ports_custom: []
qbit_manage_docker_ports: "{{ qbit_manage_docker_ports_defaults
                              + qbit_manage_docker_ports_custom }}"

# Envs
qbit_manage_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  QBT_RUN: "{{ qbit_manage.qbt_run }}"
  QBT_SCHEDULE: "{{ qbit_manage.qbt_schedule }}"
  QBT_CONFIG: "{{ qbit_manage.qbt_config }}"
  QBT_LOGFILE: "{{ qbit_manage.qbt_logfile }}"
  QBT_CROSS_SEED: "{{ qbit_manage.qbt_cross_seed }}"
  QBT_RECHECK: "{{ qbit_manage.qbt_recheck }}"
  QBT_CAT_UPDATE: "{{ qbit_manage.qbt_cat_update }}"
  QBT_TAG_UPDATE: "{{ qbit_manage.qbt_tag_update }}"
  QBT_REM_UNREGISTERED: "{{ qbit_manage.qbt_rem_unregistered }}"
  QBT_REM_ORPHANED: "{{ qbit_manage.qbt_rem_orphaned }}"
  QBT_TAG_NOHARDLINKS: "{{ qbit_manage.qbt_tag_nohardlinks }}"
  QBT_SKIP_RECYCLE: "{{ qbit_manage.qbt_skip_recycle }}"
  QBT_DRY_RUN: "{{ qbit_manage.qbt_dry_run }}"
  QBT_LOG_LEVEL: "{{ qbit_manage.qbt_log_level }}"
  QBT_DIVIDER: "{{ qbit_manage.qbt_divider }}"
  QBT_WIDTH: "{{ qbit_manage.qbt_width }}"
  QBT_DEBUG: "{{ qbit_manage.qbt_debug }}"
  QBT_TRACE: "{{ qbit_manage.qbt_trace }}"

qbit_manage_docker_envs_custom: {}
qbit_manage_docker_envs: "{{ qbit_manage_docker_envs_default
                             | combine(qbit_manage_docker_envs_custom) }}"

# Commands
qbit_manage_docker_commands_default: []
qbit_manage_docker_commands_custom: []
qbit_manage_docker_commands: "{{ qbit_manage_docker_commands_default
                                 + qbit_manage_docker_commands_custom }}"

# Volumes
qbit_manage_docker_volumes_default:
  - "{{ qbit_manage_paths_location }}:/config"
qbit_manage_docker_volumes_custom: []
qbit_manage_docker_volumes: "{{ qbit_manage_docker_volumes_default
                                + qbit_manage_docker_volumes_custom }}"

# Devices
qbit_manage_docker_devices_default: []
qbit_manage_docker_devices_custom: []
qbit_manage_docker_devices: "{{ qbit_manage_docker_devices_default
                                + qbit_manage_docker_devices_custom }}"

# Hosts
qbit_manage_docker_hosts_default: {}
qbit_manage_docker_hosts_custom: {}
qbit_manage_docker_hosts: "{{ docker_hosts_common
                              | combine(qbit_manage_docker_hosts_default)
                              | combine(qbit_manage_docker_hosts_custom) }}"

# Labels
qbit_manage_docker_labels_default: {}
qbit_manage_docker_labels_custom: {}
qbit_manage_docker_labels: "{{ docker_labels_common
                               | combine(qbit_manage_docker_labels_default)
                               | combine(qbit_manage_docker_labels_custom) }}"

# Hostname
qbit_manage_docker_hostname: "{{ qbit_manage_name }}"

# Networks
qbit_manage_docker_networks_alias: "{{ qbit_manage_name }}"
qbit_manage_docker_networks_default: []
qbit_manage_docker_networks_custom: []
qbit_manage_docker_networks: "{{ docker_networks_common
                                 + qbit_manage_docker_networks_default
                                 + qbit_manage_docker_networks_custom }}"

# Capabilities
qbit_manage_docker_capabilities_default: []
qbit_manage_docker_capabilities_custom: []
qbit_manage_docker_capabilities: "{{ qbit_manage_docker_capabilities_default
                                     + qbit_manage_docker_capabilities_custom }}"

# Security Opts
qbit_manage_docker_security_opts_default: []
qbit_manage_docker_security_opts_custom: []
qbit_manage_docker_security_opts: "{{ qbit_manage_docker_security_opts_default
                                      + qbit_manage_docker_security_opts_custom }}"

# Restart Policy
qbit_manage_docker_restart_policy: on-failure
qbit_manage_docker_restart_retries: 3

# State
qbit_manage_docker_state: started
