##########################################################################
# Title:            Sandbox: immich | Default Variables                  #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

immich_name: immich

################################
# Settings
################################

immich_role_photos_location: "/mnt/unionfs/Media/Photos"
immich_role_postgres_deploy: true
immich_role_postgres_name: "{{ immich_name }}-postgres"
# If empty it will fallback to postgres role default
immich_role_postgres_user: ""
# If empty it will fallback to postgres role default
immich_role_postgres_password: ""
immich_role_postgres_docker_env_db: "{{ immich_name }}"
immich_role_postgres_docker_image_tag: "14-vectorchord0.4.3-pgvectors0.2.0"
immich_role_postgres_docker_image_repo: "ghcr.io/immich-app/postgres"
immich_role_postgres_docker_healthcheck:
  test: ["CMD-SHELL", "pg_isready -d {{ lookup('role_var', '_postgres_docker_env_db', role='immich') }} -U {{ lookup('role_var', '_postgres_user', role='immich') if (lookup('role_var', '_postgres_user', role='immich') | length > 0) else lookup('role_var', '_docker_env_user', role='postgres') }}"]
  start_period: 20s
  interval: 30s
  retries: 5
  timeout: 5s
immich_role_postgres_docker_shm_size: "128M"
immich_role_postgres_paths_folder: "{{ immich_name }}"
immich_role_postgres_paths_location: "{{ server_appdata_path }}/{{ immich_role_postgres_paths_folder }}/postgres"
immich_role_postgres_docker_envs_custom:
  POSTGRES_INITDB_ARGS: '--data-checksums'

################################
# Paths
################################

immich_role_paths_folder: "{{ immich_name }}"
immich_role_paths_location: "{{ server_appdata_path }}/{{ immich_role_paths_folder }}"
immich_role_paths_folders_list:
  - "{{ immich_role_paths_location }}"
  - "{{ immich_role_paths_location }}/machine-learning"
  - "{{ lookup('role_var', '_photos_location', role='immich') }}"

################################
# Web
################################

immich_role_web_subdomain: "{{ immich_name }}"
immich_role_web_domain: "{{ user.domain }}"
immich_role_web_port: "8080"
immich_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='immich') + '.' + lookup('role_var', '_web_domain', role='immich')
                      if (lookup('role_var', '_web_subdomain', role='immich') | length > 0)
                      else lookup('role_var', '_web_domain', role='immich')) }}"

################################
# DNS
################################

immich_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='immich') }}"
immich_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='immich') }}"
immich_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

immich_role_traefik_sso_middleware: ""
immich_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
immich_role_traefik_middleware_custom: ""
immich_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
immich_role_traefik_enabled: true
immich_role_traefik_api_enabled: false
immich_role_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
immich_role_docker_container: "{{ immich_name }}"

# Image
immich_role_docker_image_pull: true
immich_role_docker_image_repo: "ghcr.io/imagegenius/immich"
immich_role_docker_image_tag: "latest"
immich_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='immich') }}:{{ lookup('role_var', '_docker_image_tag', role='immich') }}"

# Envs
immich_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  DB_HOSTNAME: "{{ lookup('role_var', '_postgres_name', role='immich') }}"
  DB_USERNAME: "{{ lookup('role_var', '_postgres_user', role='immich')
                 if (lookup('role_var', '_postgres_user', role='immich') | length > 0)
                 else lookup('role_var', '_docker_env_user', role='postgres') }}"
  DB_PASSWORD: "{{ lookup('role_var', '_postgres_password', role='immich')
                 if (lookup('role_var', '_postgres_password', role='immich') | length > 0)
                 else lookup('role_var', '_docker_env_password', role='postgres') }}"
  DB_DATABASE_NAME: "{{ lookup('role_var', '_postgres_docker_env_db', role='immich') }}"
  REDIS_HOSTNAME: "{{ immich_name }}-redis"
  DISABLE_MACHINE_LEARNING: "false"
  MACHINE_LEARNING_WORKERS: "1"
  MACHINE_LEARNING_WORKER_TIMEOUT: "120"
immich_role_docker_envs_custom: {}
immich_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='immich')
                             | combine(lookup('role_var', '_docker_envs_custom', role='immich')) }}"

# Volumes
immich_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='immich') }}:/config"
  - "{{ lookup('role_var', '_photos_location', role='immich') }}:/photos"
immich_role_docker_volumes_custom: []
immich_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='immich')
                                + lookup('role_var', '_docker_volumes_custom', role='immich') }}"

# Hostname
immich_role_docker_hostname: "{{ immich_name }}"

# Networks
immich_role_docker_networks_alias: "{{ immich_name }}"
immich_role_docker_networks_default: []
immich_role_docker_networks_custom: []
immich_role_docker_networks: "{{ docker_networks_common
                                 + lookup('role_var', '_docker_networks_default', role='immich')
                                 + lookup('role_var', '_docker_networks_custom', role='immich') }}"

# Restart Policy
immich_role_docker_restart_policy: unless-stopped

# State
immich_role_docker_state: started

# Dependencies
immich_role_depends_on: "{{ lookup('role_var', '_postgres_name', role='immich') }},{{ immich_name }}-redis"
immich_role_depends_on_delay: "0"
immich_role_depends_on_healthchecks: "false"
